### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by wenmhan** [allure-framework/allure-js#1022]
**Describe the bug**

When I used cy.fixture() to read a picture file of about 1.76M, an error of "RangeError: Maximum call stack size exceeded" was reported
,
**To Reproduce**
import { epic, attachment, parameter } from "allure-js-commons"

describe('Attachment Test', () => {

  it("attach", () => {
    cy.fixture("/base2/fleetmap.png", null).then((file) => {
      attachment("My image", file, "image/png")
    })

  })
}

**Screenshots**

![Uploading 20240627195536.png…]()

**Desktop (please complete the following information):**
 - node: v20.12.2
 - cypress: ^13.12.0
 - allure-cypress: ^3.0.0-beta.3

**Comment by epszaw** [comment]
The feature works well in the next `3.0.0` version.

An example of code which processes cypress fixture:

```js
import { attachment } from "${allureCommonsModulePath}";

it("with commands", () => {
  cy.fixture("sample.json").then((data) => {
    attachment("foo", JSON.stringify(data, null, 2), "application/json");
  })
});
```
