### ISSUE TITLE
[Cypress + Cucumber] Execution commands are not grouped into Given-When-Then steps

### ISSUE THREAD

**Issue by ameduza** [allure-framework/allure-js#1059]
**Describe the bug**
Execution commands are not grouped into Given-When-Then steps

Project structure: Cypress (latest) + @badeball/cypress-cucumber-preprocessor (latest )+ allure-cypress (latest: 3.0.0-beta.6)

**To Reproduce**
1. Open attached project [cypress-cucumber-allure.zip](https://github.com/user-attachments/files/16192580/cypress-cucumber-allure.zip)
2. `npm install` to initialize 
3. run `cypress run`  to run all tests and produce allure-results
4. generate AllureReport and open test result

**Expected behavior**
Scenario commands are grouped as per Given-When-Then steps like it was in a previous Cypress-Allure adapter  (@shelex/cypress-allure-plugin).

**Screenshots**
![image](https://github.com/user-attachments/assets/4d391107-c978-417c-b87e-594e819614e2)

**Additional context**
I do understand that I can wrap commands into allure.step() but this doesn't make any sense in case of Cucumber. GWT steps are already containers for the commands.

**Comment by jhilimirejc** [comment]
Can confirm that i am seeing the same results
├── allure-commandline@2.30.0
├─┬ allure-cypress@3.0.0-beta.12
│ ├── allure-js-commons@3.0.0-beta.12
│ └── cypress@13.6.1

**Comment by HabibMokhtar** [comment]
We're facing the same issue as well:

- allure-cypress: 3.0.4
- cypress: 13.15.0
- cypress-cucumber-preprocessor: 20.1.2

**Comment by baev** [comment]
We're already looking into the issue and will provide the fix as soon as possible

**Comment by baev** [comment]
The fix is available in the [allure-cypress@3.0.7](https://www.npmjs.com/package/allure-cypress/v/3.0.7)

**Comment by ameduza** [comment]
Thanks a lot, guys! Really appreciate for your efforts! Already tested in our project. From what I see you even group steps a bit better than previous plugin, that we used. 
It was a real blocker for us to upgrade to Cypress v.13x and now we unlocked for several pending changes.
