### ISSUE TITLE
[allure-js-commons][allure-jest] Possibility to rename steps attachments

### ISSUE THREAD

**Issue by lifanov-rza** [allure-framework/allure-js#1062]
Sometimes I have several attachments for 1 step and it would be more convenient to have possibility to define names for these attachments. As far as I know API is almost ready for that - just check below

![image](https://github.com/user-attachments/assets/ced7c989-fac0-429e-b998-b9af493ccfeb)

![image](https://github.com/user-attachments/assets/a8d52d37-b2f0-44aa-8a2e-2d92c7cd3141)

**Additional context**
```
"devDependencies": {
    ...
    "allure-jest": "^2.15.1",
    "jest": "^29.7.0",
    "typescript": "^5.5.3"
    ....
  },
```

If you need more details - just let me know please

**Comment by baev** [comment]
Fixed as for `allure-jest@3.0.0-beta.6`. Note that since 3.0.0, Allure Runtime API is exposed via `allure-js-commons` for all the frameworks:

``` ts
import { attachment } from "allure-js-commons";
test("some test", async () => {
  await attachment("name", "content", "text/plain");
});
```
