### ISSUE TITLE
allure-cypress test failures in before & beforeEach blocks are not reported

### ISSUE THREAD

**Issue by iamrragu** [allure-framework/allure-js#1072]
**Describe the bug**
If the cypress tests fail in the `before` or `beforeEach` block, they are not being reported in the allure-results.

**To Reproduce**
```
describe('Test Suite', { tags: '@test' }, () => {
  before(() => {
    expect(false).to.eq(true);
  });

  it('should pass', () => {
    expect(true).to.eq(true);
  });
});
```

When the test passes we get 2 files under allure-results

```
{
  "uuid": "de42dc8f-5fc6-4b23-84eb-2c49b0024fca",
  "name": "\"before all\" hook",
  "children": [
    "8496a4a2-bfff-4334-b446-febbbb83b73c"
  ],
  "befores": [
    {
      "status": "passed",
      "statusDetails": {},
      "stage": "finished",
      "steps": [],
      "attachments": [],
      "parameters": [],
      "start": 1721890224434,
      "name": "\"before all\" hook",
      "stop": 1721890224653
    }
  ],
  "afters": []
}
```
```
{
  "uuid": "8496a4a2-bfff-4334-b446-febbbb83b73c",
  "name": "should pass",
  "historyId": "7deea96eaba6ccacf320023fe1e01d97:d41d8cd98f00b204e9800998ecf8427e",
  "status": "passed",
  "statusDetails": {},
  "stage": "finished",
  "steps": [],
  "attachments": [],
  "parameters": [],
  "labels": [
    {
      "name": "language",
      "value": "javascript"
    },
    {
      "name": "framework",
      "value": "cypress"
    },
    {
      "name": "parentSuite",
      "value": "Test Suite"
    }
  ],
  "links": [],
  "start": 1721890224325,
  "fullName": "cypress/e2e/test.cy.ts#Test Suite should pass",
  "testCaseId": "7deea96eaba6ccacf320023fe1e01d97",
  "stop": 1721890224651
}
```
and when the test fails in `before` or `beforEach` block the `allure-results` folder is empty

**Expected behavior**
Test failures in test hooks should be available in allure-results and reports.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - `Mac OS Sonoma 14.5`
 - Browser [e.g. chrome, safari] - `Chrome`, `Electron`
 - Version - `cypress@13.13.0` and `allure-cypress@3.0.0-beta.7`

**Additional context**
-  `allure-results` gets generated if the test fails in `it` block or `after` or `afterEach`
- `allure-results` folder is empty if the test fails in `before` or `beforeEach`

Tried to switch to `allure-cypress@3.0.0-beta.7` since with the example spec mentioned above with `allure-cypress@2.15.1` it gets stuck and never reports a failure with the below error message.

Right now, we can't use the`allure-cypress@2.15.1` version due to below issue(from screenshot) and can't use `allure-cypress@3.0.0-beta.7` due to the current issue and https://github.com/allure-framework/allure-js/issues/1070

<img width="482" alt="image" src="https://github.com/user-attachments/assets/a6a3985e-b151-4d77-a97a-ea8fcabc6b66">

**Comment by iamrragu** [comment]
Tried updating to the @3.0.0-beta.10 version, the issue is still reproducible with the original example spec. No allure results generated for a test that fails in `before` hooks.

**Comment by baev** [comment]
@iamrragu thanks for the info
