### ISSUE TITLE
allure-codecpetjs: Allow spaces in label values provided via the tags API

### ISSUE THREAD

**Issue by delatrie** [allure-framework/allure-js#1074]
**Is your feature request related to a problem? Please describe.**
When adding a label using the tags API, the label's value cannot contain a space.

Given the following scenario:

```js
Scenario('foo', () => {}).tag('@allure.label.epic:My epic');
```

The corresponding result file will contain the `epic=My` label instead of `epic=My epic`.

**Describe the solution you'd like**
Since CodeceptJS tags are already separated, there is no need to further limit the value to non-space characters only. We may use a slightly different regular expression instead of this one:

https://github.com/allure-framework/allure-js/blob/e4e77f74c2c47751085b43f4afa27c1d90ae7769/packages/allure-codeceptjs/src/helpers.ts#L6

**Comment by baev** [comment]
It's more complex. Codecpetjs adds tags to test titles, joining them via space. Besides, Codeceptjs allows tags to be provided in titles as well and doesn't allow spaces in that case — https://github.com/codeceptjs/CodeceptJS/blob/3.5.14/lib/ui.js#L61 

The main issue is that the title is modified each time a tag is added to the scenario — https://github.com/codeceptjs/CodeceptJS/blob/3.x/lib/interfaces/scenarioConfig.js#L97

Currently, metadata from titles is already processed at the time we have access to the tags. In theory, we can undo the title modification, but that increases complexity significantly.
