### ISSUE TITLE
[v.3.0.0-beta.7][allure-jest][allure-js-commons] The error text in the test step is logged with extra characters

### ISSUE THREAD

**Issue by lifanov-rza** [allure-framework/allure-js#1076]
**Describe the bug**
The error text in the test step is logged with extra characters. I suspect that the problem is in the meta information about the text color

**To Reproduce**
1. Create test using **JEST** with steps containing substeps
2. run test with failure 
3. open allure report

```
[2mexpect([22m[31mreceived[39m[2m).[22mtoStrictEqual[2m([22m[32mexpected[39m[2m) // deep equality[22m

Expected: [32m1[39m
Received: [31m2[39m
```

**Expected behavior**
error text without meta information

**Screenshots**
![image](https://github.com/user-attachments/assets/f77008fa-cec9-445e-a20f-466aff9717f6)

**Comment by baev** [comment]
@lifanov-rza please specify the test framework you're using.

**Comment by lifanov-rza** [comment]
> @lifanov-rza please specify the test framework you're using.

done
