### ISSUE TITLE
Problem on allure-jest/dist/AllureJestApi sendMetadata

### ISSUE THREAD

**Issue by lihailewodedai** [allure-framework/allure-js#1086]
using allure-jest version 2.15.1, I encountered a bug where when I call any method, e.g. allure.label which calls sendMetadata, and in sendMetadata, line 11 in AllureJestApi.js under dist, it calls this.context.expect.getState(), for my project, i found out that it needs to be this.context.expect.expext.getState() in order to retrieve the currentTestName. Is this something related to potential conflict with other packages?

**Comment by baev** [comment]
Could you please verify `allure-jest@3.0.0-beta.7`?
