### ISSUE TITLE
allure-codeceptjs version: 3.0.0-beta.7: Could not load plugin allure from module 'allure-codeceptjs': Cannot find module 'node:path'

### ISSUE THREAD

**Issue by sandeep-teegala** [allure-framework/allure-js#1090]
**Describe the bug**
When using allure-codeceptjs version: 3.0.0-beta.7 getting this below error

Could not load plugin allure from module 'allure-codeceptjs':
Cannot find module 'node:path'

Steps to reproduce the behaviour:
1. Node: 18.18.2
2. Codeceptjs Version: 3.6.5
3. Playwright Helper Version: 1.45.3
4. Plugin: allure: {
      enabled: true,
      require: "allure-codeceptjs",
      outputDir: "./output/allure/allure-results",
    },
5. Run the Test you will get the error

**Desktop (please complete the following information):**
 - OS: Windoes
 - Browser  chrome

**Comment by baev** [comment]
Are you using Codecept UI?

**Comment by sandeep-teegala** [comment]
No

**Comment by sandeep-teegala** [comment]
"allure-commandline": "2.21.0",

**Comment by baev** [comment]
could you please specify full codecept config & run options?

**Comment by sandeep-teegala** [comment]
The issue is from my side this is working fine now.
