### ISSUE TITLE
3.0.0-beta.7 allure-codeceptjs: generated allure-results are not getting stored in the given path in plugin

### ISSUE THREAD

**Issue by sandeep-teegala** [allure-framework/allure-js#1093]
**Describe the bug**
Allure Results which are generated after the text execution are not stored in the path which is given in the plugin

Steps to reproduce the behaviour:
1. Allure Plugin: 
allure: {
      enabled: true,
      require: "allure-codeceptjs",
      outputDir: "output/allure/allure-results",
    },
2. Run Codeceptjs Test
3. Verify the allure-results folder path is not stored in the outputtDir.

Versions:
1. "allure-commandline": "2.29.0"
2.  "allure-codeceptjs": "3.0.0-beta.7",

**Expected behaviour**
Allure Results should be stored in the desired path

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium

**Comment by sandeep-teegala** [comment]
Node Version: 18.17.0
Framework: Codeceptjs with Playwright
Codeceptjs version: 3.6.5
Playwright Version: 1.45.3

**Comment by baev** [comment]
starting with 3.0.0 `outputDir` renamed to `resultsDir` to align the naming across different integrations
