### ISSUE TITLE
3.0.0-beta.7 allure-codeceptjs: Failed ScreenShots are not getting displayed in the report

### ISSUE THREAD

**Issue by sandeep-teegala** [allure-framework/allure-js#1095]
Describe the bug
When the Test fails screenshots are not attached/displayed in the report

Steps to reproduce the behaviour:
1. Generate an allure report.
2. Verify the report steps.

Framework: Codeceptjs with Playwright
Versions: 
1. "allure-commandline": "2.29.0"
2. "allure-codeceptjs": "3.0.0-beta.7",
3. Node Version: 18.17.0
4. Codeceptjs version: 3.6.5
5. Playwright Version: 1.45.3

Expected behaviour
The failed screenshot should also be displayed when the Test fails along with the steps and error.

Desktop (please complete the following information):
- OS: Windows
- Browser: Chromium

**Comment by baev** [comment]
Could you please specify the way screenshots are taken?

**Comment by sandeep-teegala** [comment]
screenshotOnFail: {
      enabled: true,
    },
