### ISSUE TITLE
outputFolder is not working in allure-playwright v3.0.0-*

### ISSUE THREAD

**Issue by tmantis01** [allure-framework/allure-js#1118]
**Describe the bug**
Although I configured an _outputFolder_ in the _playwright.config.ts_
It doesn't take into consideration my configuration but creates a folder named _allure-results_ in the root folder.

My configuration is this:
    outputFolder: path.resolve(__dirname, 'allure-results-new'),
    
 

It is **working** in **allure-playwright v2.15.1** -> creates the folder allure-results-new in the path of the playwright.config.ts and adds the files in there

but in **v3.0.0-*** is **failing** (I tried in v3.0.0-beta.10 and v3.0.0-beta.1) -> creates an allure-results folder in the root.

**To Reproduce**
1. Go in the playwright.config.ts
2. add an allure-playwright reporter 
3. add an outputFolder which is different from allure-results

**Expected behavior**
Allure should create the folder and add the results in the path that the user has configured

**Comment by baev** [comment]
Since 3.0.0 the configuration output property has been renamed to `resultsDir` for all the integrations:

```
  reporter: [
    [
      "allure-playwright",
      {
        resultsDir: "./out/allure-results",
      },
    ],
  ],
```

**Comment by tmantis01** [comment]
Thank you!
This is working! :)
