### ISSUE TITLE
Make limits configurable

### ISSUE THREAD

**Issue by brunabrk** [allure-framework/allure-js#1137]
**Describe Feature**
Right now, the History entries are limited to 20 and thread columns in each graph (https://allurereport.org/docs/history-and-retries/#how-to-enable-history). It would be nice if this could be configurable and not a fixed value.

**Describe the solution**
Allure could make this limit configurable via `vitest.config.ts`

Example: 

```

import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    dir: "./test/spec",
    testTimeout: 20000,
    setupFiles: ["allure-vitest/setup"],
    reporters: ["basic", ["allure-vitest/reporter", { resultsDir: "./out/allure-results",  allureResultsLimit: "100"}]],
    typecheck: {
      enabled: true,
      tsconfig: "./tsconfig.test.json",
    },
  },
});
```

Thank you!

**Comment by baev** [comment]
The limits are enforced by the allure report generator and can't be changed via reporter config. 

closed as a duplicate of https://github.com/allure-framework/allure2/pull/1331

**Comment by brunabrk** [comment]
@baev is the plan to work on this https://github.com/allure-framework/allure2/pull/1331? This is opened June 23 2021

**Comment by baev** [comment]
The issue will be addressed in the upcoming Allure 3.
