### ISSUE TITLE
[Playwright] - Error reading LabelName.PACKAGE

### ISSUE THREAD

**Issue by harmin-parra** [allure-framework/allure-js#1142]
**Describe the bug**
Since `allure-playwright@3.0.0`, **LabelName.PACKAGE** is undefined

**To Reproduce**
Execute this playwright test
```
const { test, expect, Page } = require('@playwright/test');
import { allure, LabelName } from "allure-playwright";
import AjaxPage from '../pages/ajax.page';
const assert = require('assert');

  test.beforeEach(async ({ page }) => {
    await page.goto("https://harmin-demo.gitlab.io/reports/web/ajax.html");
  });


  test('Ajax verification with intercept', async ({ page }) => {
    await allure.description("Testing a webpage using AJAX");
    await allure.epic("Web interface (Playwright)");
    await allure.story("Ajax");
    await allure.parentSuite("Web interface (Playwright)");
    await allure.suite("Ajax");
    await allure.label(LabelName.PACKAGE, "web_playwright.ajax.spec.ts");
    // rest of test
  });
```

Result:

```
    TypeError: Cannot read properties of undefined (reading 'PACKAGE')

      22 |     await allure.parentSuite("Web interface (Playwright)");
      23 |     await allure.suite("Ajax");
    > 24 |     await allure.label(LabelName.PACKAGE, "web_playwright.ajax.spec.ts");
         |                                  ^
```

This error didn't happen in `allure-playwright@2.15.1`

**Expected behavior**.
**LabelName.PACKAGE** is defined

**Comment by baev** [comment]
Since 3.0.0 Runtime API is exposed from "allure-js-commons" for all the frameworks, so instead of doing 

```ts
import { allure, LabelName } from "allure-playwright";
```

you should do 

```ts
import * as allure from "allure-js-commons";
```

`LabelName` should be imported from "allure-js-commons" as well

**Comment by baev** [comment]
The recommended way is to import only functions you need, eg:

```ts
import { label, link, issue, tms, step, attachment, logStep, LabelName } from "allure-js-commons";
```

**Comment by harmin-parra** [comment]
I am getting other errors with the import statement `import { allure, LabelName } from "allure-js-commons";`

```
    TypeError: Cannot read properties of undefined (reading 'description')

      13 |
      14 |   test('Ajax verification with intercept', async ({ page }) => {
    > 15 |     await allure.description("Testing an AJAX page\n\nTest using ``page.waitForResponse()``");
         |                  ^

```

**Comment by delatrie** [comment]
@harmin-parra 
Use `import { description } from "allure-js-commons";` and call `description` directly.
Or use `import * as allure from "allure-js-commons";`

**Comment by harmin-parra** [comment]
Thanks @delatrie and @baev 
I used `import * as allure from "allure-js-commons";`
and replaced `LabelName.PACKAGE` by `allure.LabelName.PACKAGE`

I also noted that `allure-js-commons` is not a dependency of `allure-playwright.`
I had to install `allure-js-commons` manually after installing `allure-playwright`.

Maybe the documentation needs to be updated to clarify the new form of adding the metadata and indicating that `allure-js-commons` needs to be installed manually.

**Comment by baev** [comment]
@harmin-parra documentation update is WIP. We're expecting to land most of the changes this week
