### ISSUE TITLE
[v.3.0.1][allure-jest][allure-js-commons] Allure report contains an extra nested step when adding attachments

### ISSUE THREAD

**Issue by lifanov-rza** [allure-framework/allure-js#1160]
**Describe the bug**
We use [Allure Server](https://github.com/kochetkov-ma/allure-server/blob/ef4f2d37666b85a98e8b1eb0bc437695aaca3472/README.md#allure-portal-allure-report-server) in ci. When viewing reports in it, in each step containing attachments, an extra nested step is displayed.

![image](https://github.com/user-attachments/assets/4bcde87d-a590-4da4-b580-c555d96eef3b)

After looking at the json, I found this structure of the report. It seems that the nested substep is redundant information, which leads to such a display

![image](https://github.com/user-attachments/assets/12349aa7-8d0a-47b4-8b46-5681d2003edd)

**To Reproduce**
- run jest test with attachment steps
- run [Allure Server](https://github.com/kochetkov-ma/allure-server/blob/ef4f2d37666b85a98e8b1eb0bc437695aaca3472/README.md#allure-portal-allure-report-server)
- open report in [Allure Server](https://github.com/kochetkov-ma/allure-server/blob/ef4f2d37666b85a98e8b1eb0bc437695aaca3472/README.md#allure-portal-allure-report-server)

**Expected behavior**
Report is displayed without nested steps

**Versions (please complete the following information):**
- kochetkovma/allure-server: 2.11.4
- allure-jest: 3.0.1
- allure-js-commons: 3.0.1,

**Comment by baev** [comment]
> kochetkovma/allure-server: 2.11.4

It's a third-party module, and it seems that it doesn't support [attachments meta steps](https://github.com/allure-framework/allure2/pull/2107).
