### ISSUE TITLE
allure-playwright v3.0.5 adds trace attachment as it's own step

### ISSUE THREAD

**Issue by eklmv** [allure-framework/allure-js#1177]
**Describe the bug**
allure-playwright v3.0.5 report contains trace as it's own step, when in v2.15.1 it was in top level `attachments`.
v2.15.1:
```json
{
  ...
    "attachments": [
        {
            "name": "trace",
            "type": "application/zip",
            "source": "54102549-fbff-469c-bd7c-e2883ec4d78f-attachment.zip"
        }
    ],
  ...
}
```
v3.0.5:
```json
{
    ...
    "steps": [
        ...
        {
            "statusDetails": {},
            "stage": "finished",
            "steps": [],
            "attachments": [
                {
                    "name": "trace",
                    "source": "fbe94b36-040d-43a2-9523-03ec6dcdbd32-attachment.zip",
                    "type": "application/zip"
                }
            ],
            "parameters": [],
            "start": 1729583159883,
            "name": "trace",
            "stop": 1729583159883
        }
    ],
    "attachments": [],
    ...
}
```
**To Reproduce**
1. Clone repo https://github.com/eklmv/allure-playwright-bare-trace-as-step
2. Run `yarn && yarn allure-playwright:all` in it.
3. Examine `*-result.json` files in `allure/playwright/v2.15.1/` and `allure/playwright/v3.0.5/` directories.

**Expected behavior**
trace to be top level attachment, and not it's own step.

**Additional context**
Minimal repo to reproduce that bug: https://github.com/eklmv/allure-playwright-bare-trace-as-step

**Comment by baev** [comment]
Since 3.0.0, Allure uses [attachments meta steps](https://github.com/allure-framework/allure2/pull/2107) by default for all the attachments.
