### ISSUE TITLE
Testplan.json parse error on gitlab ci when using allurectl

### ISSUE THREAD

**Issue by aletzal** [allure-framework/allure-js#1183]
**Describe the bug**

Problem occures on Gitlab CI when using [allurectl_linux_386](https://github.com/allure-framework/allurectl/releases/download/2.15.1/allurectl_linux_386) (2.15.1)

(it can be reproduced locally, just add to env `GITLAB_CI=true`)

Typescript + Playwright

**To Reproduce**
1. use dependency `"allure-playwright": "3.0.5"`
2. integration with Allure TestOps is needed
3. must be executed on Gitlab CI
4. run `allurectl watch -- npx playwright test`

**Expected behavior**
NO exceptions related to `testplan.json` in logs

**Actual behavior**
```
Session [32146] started
Report link: https://allure.myserver.com/jobrun/19572
could not parse test plan /usr/src/app/.allure/testplan.json Error: ENOENT: no such file or directory, open '/usr/src/app/.allure/testplan.json'
    at readFileSync (node:fs:448:20)
    at parseTestPlan (/usr/src/app/node_modules/allure-js-commons/src/sdk/reporter/testplan.ts:14:30)
    at AllureReporter.onConfigure (/usr/src/app/node_modules/allure-playwright/src/index.ts:93:35)
    at /usr/src/app/node_modules/playwright/lib/reporters/multiplexer.js:32:65
    at wrap (/usr/src/app/node_modules/playwright/lib/reporters/multiplexer.js:86:5)
    at Multiplexer.onConfigure (/usr/src/app/node_modules/playwright/lib/reporters/multiplexer.js:32:45)
    at InternalReporter.onConfigure (/usr/src/app/node_modules/playwright/lib/reporters/internalReporter.js:45:20)
    at Runner.runAllTests (/usr/src/app/node_modules/playwright/lib/runner/runner.js:74:14)
    at runTests (/usr/src/app/node_modules/playwright/lib/program.js:207:85)
    at t.<anonymous> (/usr/src/app/node_modules/playwright/lib/program.js:54:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/usr/src/app/.allure/testplan.json'
```

**Additional context**
- There are NO variable `ALLURE_TESTPLAN_PATH` in `Session variables`
- `ALLURE_TESTPLAN_PATH` is not set in environment variable
- tests are not executed from Allure Testops by trigger

[v3.0.5](https://github.com/allure-framework/allure-js/releases/tag/v3.0.5) - ERROR
...
[v3.0.0-beta.8](https://github.com/allure-framework/allure-js/releases/tag/v3.0.0-beta.8) - ERROR
[v3.0.0-beta.7](https://github.com/allure-framework/allure-js/releases/tag/v3.0.0-beta.7) - OK

**Comment by cheshi-mantu** [comment]
hi there
on your machine, do you have path: '/usr/src/app/.'?
if not, then you have correct behaviour (and the error message says so: could not parse test plan /usr/src/app/.allure/testplan.json Error: ENOENT: no such file or directory, open '/usr/src/app/.allure/testplan.json').

for local executions you need to do as follows:
```shell
 export ALLURE_TESTPLAN_PATH=./testplan.json
```
then execute your command for running the tests.

See here: https://allurereport.org/docs/playwright/#select-tests-via-a-test-plan-file

**Comment by aletzal** [comment]
Hi! Thanks for the answer

1. It executed inside docker container
2. Why does it works for `v3.0.0-beta.7`?

Dockerfile
```
ARG DOCKER_IMAGE_PLAYWRIGHT_VERSION=mcr.microsoft.com/playwright:v1.45.0-noble

FROM ${DOCKER_IMAGE_PLAYWRIGHT_VERSION}

RUN apt-get update && apt-get install -y build-essential

ADD https://github.com/allure-framework/allurectl/releases/download/2.15.1/allurectl_linux_386 /bin/allurectl

RUN chmod +x /bin/allurectl \
    && allurectl --version

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN yarn clean && yarn start:ci && ls -la

CMD ["/bin/sh"]

```
