### ISSUE TITLE
Can I send allure report via email through Jenkins?

### ISSUE THREAD

**Issue by gauravgandhi15** [allure-framework/allure-js#122]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [x] support request => Please do not submit support request here, see note at the top of this template.

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | jest@latest |
| Allure adaptor | allure-mocha@latest |
| Generate report using | allure-jenkins@latest |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by korobochka** [comment]
I'd say this question is unrelated to this repo.
There is a jenkins plugin which can generate reports: https://plugins.jenkins.io/allure-jenkins-plugin/
Alternatively, look at 'allure-commandline' npm package.

When your static HTML files are generated you can send them as any other static content.
