### ISSUE TITLE
allure-mocha example is not using allure-mocha

### ISSUE THREAD

**Issue by iamolegga** [allure-framework/allure-js#135]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

[`allure-mocha`'s example](https://github.com/allure-framework/allure-js/tree/master/packages/allure-mocha#examples) is not not using module `allure-mocha`

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Example repository is [mocha-allure2-example](https://github.com/sskorol/mocha-allure2-example).

It's [package.json](https://github.com/sskorol/mocha-allure2-example/blob/master/package.json) has only one package from allure ecosystem: [mocha-allure2-reporter](https://www.npmjs.com/package/mocha-allure2-reporter).

[mocha-allure2-reporter](https://www.npmjs.com/package/mocha-allure2-reporter)'s [the only one dependecy](https://www.npmjs.com/package/mocha-allure2-reporter?activeTab=dependencies) is [allure**2**-js-commons](https://www.npmjs.com/package/allure2-js-commons).

But [allure-mocha's dependecy](https://www.npmjs.com/package/allure-mocha?activeTab=dependencies) is [allure-js-commons](https://www.npmjs.com/package/allure-js-commons).

So there is nothing in common, and current example link leads to wrong example.

#### What is the expected behavior?

`allure-mocha` should provide correct example

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | jest@latest |
| Allure adaptor | allure-mocha@latest |
| Generate report using | allure-jenkins@latest |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by sskorol** [comment]
`allure-js` was assembled from different repositories.
`allure-mocha` was created at the beginning of Jul, 19.
`mocha-allure2-example` was created at the end of Oct, 18. And as you already noticed, it's based on a core from a different repository, which was copy-pasted into `allure-js-commons` after a while, as well as `mocha-allure2-reporter` was migrated to `allure-mocha`. Due to historical circumstances, examples were not updated. I'll do that when I have time. Thanks for reporting.

**Comment by iamolegga** [comment]
Hi, @iamolegga thanks for your clarification.

Btw, I'm interested in using your `ts-test-decorators` which is relied on `mocha-allure2-reporter`, so, do I understand correctly that using it is safe now, and you are going to migrate it's deps to _official_ packages soon?

**Comment by sskorol** [comment]
Depending on how you gonna use it. If you want to access decorators together with WDIO framework, then I'd recommend to take a look at https://github.com/sskorol/wdio-testdeck-allure-examples, as WDIO maintains their own Allure-package. Otherwise, yes, I'll updated `ts-test-decorators` soon. But note that `mocha-typescript` is deprecated. `testdeck` evolved from this project. So when `ts-test-decorators` is updated, it'll include not only new Allure deps.

**Comment by iamolegga** [comment]
No, we gonna use it with [https://github.com/wix/Detox](Detox). And I'm also forked [mocha-allure2-reporter](https://github.com/iamolegga/mocha-allure2-reporter), [allure2-js-commons](https://github.com/iamolegga/allure2-js-commons) and [ts-test-decorators](https://github.com/iamolegga/ts-test-decorators) already, I've updated deps, gonna improve global `allure` declaration and get rid of that part:
```
"typeRoots": [
      "./node_modules/@types/",
      "./node_modules/allure2-js-commons/dist/declarations/**/"
    ]
```

I could live with my own forks, but if you are interested in updating those libs, I can make PRs to original repos

**Comment by sskorol** [comment]
PRs are always welcome. :)

**Comment by sskorol** [comment]
@iamolegga will update `ts-test-decorators` as soon as #138 is merged and a new allure-js version is released. Already tested is locally. So stay tuned.

**Comment by sskorol** [comment]
@iamolegga I haven't updated allure-mocha README yet, but all the related repositories (ts-test-decorators / mocha-allure2-example) are now using latest allure-js / testdeck dependencies. Check if it meets your needs, so that we could close this issue.

**Comment by iamolegga** [comment]
Thanks!
