### ISSUE TITLE
Support for Cucumber.js version 5

### ISSUE THREAD

**Issue by korobochka** [allure-framework/allure-js#14]
Currently allure-cucumberjs works with version `"cucumber": "^4.2.1"` at most.

With Cucumber.js 5+ reporter fails with the message:
`Error: TypeError: Class constructor Formatter cannot be invoked without 'new'
at new CucumberJSAllureFormatter`

Some additional information:
https://github.com/korobochka/cucumberjs-allure2-reporter/issues/4

**Comment by fescobar** [comment]
Hi @korobochka 
Do you have any update about this?
Thank you

**Comment by fescobar** [comment]
I tried with all version and It worked.
The problem is only in the last version **5.1.0** >  https://www.npmjs.com/package/cucumber/v/5.1.0

https://www.npmjs.com/package/cucumber

**Comment by sseliverstov** [comment]
There were wrong compile options. Fixed in beta.2
