### ISSUE TITLE
Support Jest table tests

### ISSUE THREAD

**Issue by kirill-konshin** [allure-framework/allure-js#141]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Jest has a functionality similar to https://github.com/junit-team/junit4/wiki/Parameterized-tests where you can define a number of tests using a table: https://jestjs.io/docs/en/api#testeachtablename-fn-timeout

```js
test.each([
  [1, 1, 2],
  [1, 2, 3],
  [2, 1, 3],
])('.add(%i, %i)', (a, b, expected) => {
  expect(a + b).toBe(expected);
});
```

Currently it will result in 3 tests in Allure report: `.add(1,1)`, `.add(1,2)` and `.add(2,1)`. It would be nice to have some way to group these tests in report.

**Comment by noomorph** [comment]
Is it possible at all? That `.add(%i, %i)` information is lost very early – there's no chance you could do it without patching or contributing to Jest.

https://github.com/jestjs/jest/blob/0fd5b1c37555f485c56a6ad2d6b010a72204f9f6/packages/jest-each/src/bind.ts#L50

**Comment by epszaw** [comment]
Our official jest integration (`allure-jest`) supports table tests. Please use it

**Comment by noomorph** [comment]
@epszaw, sorry for nudging, but are you sure you understood clearly what's been asked here in the issue? The question inquires about placing all the there tests under a single sub-subsuite.
