### ISSUE TITLE
allure-jest wrong example in README

### ISSUE THREAD

**Issue by adelin-b** [allure-framework/allure-js#166]
#### I'm submitting a ... 
  - [x] bug report

#### What is the current behavior?

The jest example from the page https://github.com/allure-framework/allure-js/blob/master/packages/allure-jest/README.md

 don't compile and seem outdated when we compare it to https://github.com/allure-framework/allure-js/blob/master/packages/allure-jest/test/default-runner/allure-report.ts

#### What is the expected behavior?
It should be working

**Comment by vovsemenv** [comment]
resolved in https://github.com/allure-framework/allure-js/pull/513
