### ISSUE TITLE
How to add test-steps under test body in allure-nightwatch

### ISSUE THREAD

**Issue by govind413** [allure-framework/allure-js#167]
#### What is the current behavior?
If i generate allure report from default xml generated from nightwatch.js then test steps are not getting added under test body. 

#### What is the expected behavior?
I want allure report having test steps , substeps under test body, just like below screenshot. I am able to add steps in allure-mochasome but not in allure-nightwatch
<img width="1440" alt="Screenshot 2020-06-06 at 3 09 19 PM" src="https://user-images.githubusercontent.com/60140375/84026338-ca318980-a9aa-11ea-83fd-981bc0d87e6a.png">

#### What is the motivation / use case for changing the behavior?
It gives more clarity in reports about steps taken in test cases. 

#### Please tell us about your environment:

Allure-nightwatch-adapter 1.2.4
nightwatch v0.9.21

#### Other information 

can we have supported framework for nightwatch same way as for cucumber, mocha, etc? 

Although used one adapter(allure-nightwatch-adapter) for nightwatch but it adds all test cases under test body. and total count of test cases becomes total count of suits.
<img width="1173" alt="Screenshot 2020-06-08 at 4 54 41 PM" src="https://user-images.githubusercontent.com/60140375/84033427-74fb7500-a9b6-11ea-8c38-132b1b733616.png">

**Comment by vovsemenv** [comment]
Right now nightwatch integration lives in https://github.com/kushmangal/Nightwatch-Allure-Reporter
Please consider leaving your feedback there.
