### ISSUE TITLE
Provide a static method to write environment info

### ISSUE THREAD

**Issue by just-boris** [allure-framework/allure-js#181]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?

In case of parallel test runs, there is no clear place where to put `allure.writeEnvironmentInfo()` call.

In the parent process, there is no `allure` object, it fails.

In child processes, you have a race condition, where multiple tests are writing to the same file. This may not end well.

### Proposed API

```js
import Allure from "allure-js-commons";

Allure.writeEnvironmentInfo();
```

**Comment by just-boris** [comment]
TODO: we also need to check, how this will change with Mocha v8 release which has built-in parallel tests

**Comment by maks-rafalko** [comment]
@baev could you please explain why is it not planned and how this can be achieved?

**Comment by baev** [comment]
The next release will provide a way to supply environment info for all the supported test frameworks

**Comment by maks-rafalko** [comment]
are there any docs/links you can share to investigate?

**Comment by baev** [comment]
Not yet. We plan to release a preview version (3.0.0-beta.0) by the end of this week (or maybe early next week). After then, we will start our work on docs and examples
