### ISSUE TITLE
Add support for cucumber-js v7

### ISSUE THREAD

**Issue by damonpam** [allure-framework/allure-js#227]
#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Not support for cucumber-js v7.

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
After updating cucumberjs to v7 the report is not generated anymore.

#### What is the expected behavior?
As per cucumber changelog:
```
Formatters: 

- Events are now based on cucumber-messages
- event-protocol formatter has been removed and replaced with message
- Custom formatters will need to migrate
- json formatter is deprecated and will be removed in next major release. Custom formatters should migrate to use the message formatter, or the standalone JSON formatter as a stopgap.
```

#### What is the motivation / use case for changing the behavior?
Ability to use the latest features of cucumber-js

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | cucumber@7 |
| Allure adaptor | allure-cucumberjs@latest |
| Generate report using | allure-commandline@latest |

#### Other information 
[Changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#breaking-changes)
[cucumber-messages](https://github.com/cucumber/cucumber/tree/master/messages)

**Comment by EdvinasGl** [comment]
Hi, @korobochka, are you planning a new version of Allure to support cucumber-js v7? When we can expect it?

**Comment by vctrmn** [comment]
Hello, any news on this ?

**Comment by yevhenchmykhunserve** [comment]
Hi! Any news on this?

**Comment by just-boris** [comment]
Cucumber integration is a community-driven project. There will be no news until some enthusiast would contribute this.

PRs are welcome

**Comment by baev** [comment]
btw, I already started my work on that #346 . Feel free to contribute to cucumberjs7 branch as well, that will speedup a progress a bit.

From my side I expect to finish the work by the end of September (I'm pretty busy on my schedule :( )

**Comment by yugasun** [comment]
Any update on this fix?

**Comment by Alje001** [comment]
Any update for this task? Schould I use the previous version of Cucumber? 

Thank you for supporting.

**Comment by ctorresMural** [comment]
Hi,  Any update on this issue?  It's necessary to generate a new version that supports the newest cucumber versions.

**Comment by itstoocloudy** [comment]
Still looking forward for solution!

**Comment by skfaisalt** [comment]
Facing the same issue, tried with cucumber versions 8 and 7. Can anyone please state the last compatible cucumber version with allure? thanks in advance.

**Comment by fguidobaldi** [comment]
Hi @skfaisalt! I was able to run Cucumber v6.0.7 with Allure successfully. I think that v7 and 8 are still not compatible due to this issue.

**Comment by arjanassink1978** [comment]
Is there any progress on adding support for cucumber 7.

**Comment by Alje001** [comment]
Hi @baev 
I would like to ask you whether we have any update on this task. 

Thank you for your support.

**Comment by Tallyb** [comment]
I have published a temp fix, if anyone is interested: https://www.npmjs.com/package/allure-cucumberjs8

**Comment by arjanassink1978** [comment]
> I have published a temp fix, if anyone is interested: https://www.npmjs.com/package/allure-cucumberjs8

Great i am going to give it a try

**Comment by baev** [comment]
2.0.0-beta.18 adds support for cucumberjs 8

**Comment by skfaisalt** [comment]
@baev indeed. I gave it a try and it works perfectly. Cheers!
