### ISSUE TITLE
[feature requests] Create document for new Allure-JS - All document refers to Allure1

### ISSUE THREAD

**Issue by pulack** [allure-framework/allure-js#233]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

#### What is the current behavior?
Allure-JS document not found.

#### What is the expected behavior?
Create document for new Allure-JS, it is confusing because all document refers to Allure1

#### What is the motivation / use case for changing the behavior?
Document how to use with Allure-JS in JavaScript project and create or use @Step Annotation

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | jest@latest |
| Allure adaptor | allure-mocha@latest |
| Generate report using | allure-jenkins@latest |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
https://allurereport.org/docs/
