### ISSUE TITLE
Allure report counts  failed/broken "after all"  , "before all" tests to total test counts

### ISSUE THREAD

**Issue by etom123** [allure-framework/allure-js#237]
I am new to Allure reports and WebdriverIO 
I'm submitting a  - [ ] bug report

Current Behavior : Allure report counts all after, all before all tests in the total test count which are not passed . If these are passed  it will not add up to the total test count
![image](https://user-images.githubusercontent.com/31858448/111706303-6cbf4880-8818-11eb-84dd-916f59f114a4.png)

Expected behavior : Show all individual test cases , not "after all", "before all" test cases . And if _After all_ _Before All_ test cases failed show the details in the skipped test cases , as we see for passed test cases 

#### Please tell us about your environment:

| Allure version | 6.11.0" |
| --- | --- |
| Test framework | mocha-framework": 6.11.0 |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by sskorol** [comment]
@etom123 WDIO maintains their own Allure implementation. So it's better to report this issue in their [repo](https://github.com/webdriverio/webdriverio/issues).

**Comment by vovsemenv** [comment]
Closed as not related to other repo https://github.com/webdriverio/webdriverio
