### ISSUE TITLE
Please add jest-circus support

### ISSUE THREAD

**Issue by azakordonets** [allure-framework/allure-js#282]
#### I'm submitting a ... 
  - [x] feature request

#### What is the current behavior?
Currently allure-js supports only Jasmine test results. Jest-circus apperantly has a different format and therefore when I try to run my tests with jest-circus runner, I get 
```
    ReferenceError: jasmine is not defined

      at registerAllureReporter (node_modules/jest-allure/dist/setup.js:62:5)
      at Object.<anonymous> (node_modules/jest-allure/dist/setup.js:65:1)
```
error

#### What is the motivation / use case for changing the behavior?

I would like to run our E2E API tests with latest jest test runner. 

#### Please tell us about your environment:

| Allure version | 2.7.0 |
| --- | --- |
| Test framework | jest@latest |
| Allure adaptor | allure-jest@latest |

**Comment by saritvakrat** [comment]
Hi, any update on that issue?

**Comment by vovsemenv** [comment]
Hello @saritvakrat right now we didn't have official package but you can use one from community https://github.com/ryparker/jest-circus-allure-environment
ist pretty good TBH and maybe in future we will use it as foundation for our official circus reporter

**Comment by KillWolfVlad** [comment]
> https://github.com/ryparker/jest-circus-allure-environment

This repo is archived (have bugs and don't support latest versions of Jest). We use this fork https://github.com/c4lifa/jest-allure-circus.
