### ISSUE TITLE
Add allure-playwright

### ISSUE THREAD

**Issue by pavelfeldman** [allure-framework/allure-js#296]
There is a popular request for Allure reporting at https://github.com/microsoft/playwright/issues/7034.

I have it working locally, it is only ~120 lines of code. Are you interested in a PR that adds it here?

**Comment by sseliverstov** [comment]
@pavelfeldman It will be very good, tnx!

**Comment by kshrestha99** [comment]
@pavelfeldman  Thank you for implementing the allure reporting to playwright! Its fantastic! My only question is regarding the location of the allure-reports and allure-results, which goes by default to the root of my project. I am using playwright.config.ts file where I declare the reporter. I did not understand how to use ALLURE_RESULTS_DIR as a environment variable. Can someone please help me out?

**Comment by hananmalka** [comment]
> @pavelfeldman Thank you for implementing the allure reporting to playwright! Its fantastic! My only question is regarding the location of the allure-reports and allure-results, which goes by default to the root of my project. I am using playwright.config.ts file where I declare the reporter. I did not understand how to use ALLURE_RESULTS_DIR as a environment variable. Can someone please help me out?

Take a look here: 
https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md
It mentioned that you should use the env variable in the command line of executing the tests:
`ALLURE_RESULTS_DIR=my-allure-results npx playwright test --reporter=line,allure-playwright`
