### ISSUE TITLE
Get this error `Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-16-openjdk-amd64/lib/libawt_xawt.so` while running `allure open ./allure-report` in ubuntu 20

### ISSUE THREAD

**Issue by ssurabhi10** [allure-framework/allure-js#311]
Get this error
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-16-openjdk-amd64/lib/libawt_xawt.so`
while running `allure open ./allure-report` in ubuntu 20

Is there any other way to open reports other than `allure open ./allure-report`?

**Comment by vovsemenv** [comment]
java generator related issues discussed in https://github.com/allure-framework/allure2
