### ISSUE TITLE
[allure-playwright]: Artifacts have fullpath in allure results

### ISSUE THREAD

**Issue by pavelfeldman** [allure-framework/allure-js#326]
Mirroring https://github.com/microsoft/playwright/issues/8079

@baev should I be calling writeAttachment with relative file name? If yes, relative to what?

**Comment by baev** [comment]
The problem is that using addAttachment method you can only link attachments from `allure-results` directory by file name. So you need to copy attachment file to results directory first. So I did in #329

**Comment by baev** [comment]
I wish to add a test for that change, but I have no idea how to add attachment to playwright so it have no body and only path. I'll be grateful If you suggest me a solution
