### ISSUE TITLE
Playwright support TestCaseID functionality

### ISSUE THREAD

**Issue by cardinalX** [allure-framework/allure-js#331]
We want to use [Test-Case-ID](https://github.com/allure-framework/allure1/wiki/Test-Case-ID) functionality like in another programming languages like Java.

Have some functionality to use it with Playwright (allure-playwright)

**Comment by vovsemenv** [comment]
resolved by #408

**Comment by vovsemenv** [comment]
resolved. example usage https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md#proving-extra-information
