### ISSUE TITLE
Playwright support Issues functionality

### ISSUE THREAD

**Issue by cardinalX** [allure-framework/allure-js#332]
We want to use [Issues](https://github.com/allure-framework/allure1/wiki/Issues) functionality like in another programming languages like Java.

Have some functionality to use it with Playwright (allure-playwright)

**Comment by vovsemenv** [comment]
@pavelfeldman Hi! I want to add issues functionality by adding issues to test result attachments. It will be ok? Or maybe wait until this fields will add to playwright itself
