### ISSUE TITLE
[Question] allure-playwright release cadence

### ISSUE THREAD

**Issue by pavelfeldman** [allure-framework/allure-js#342]
Playwright releases once a month and we are likely to add / improve allure integration with every release for several months. How should we go about pushing these updates? For example, Playwright 1.14 introduced steps and they are supported in this repo now, but users won't be able to use them until npm is published.

**Comment by baev** [comment]
yeah, Allure team is agree on that. And we are so excited to support you. You can always DM me ( or even better mail to allure at qameta.io ) in case of some problems, and we'll do our best to help you ;)

I tried to release the changes this weekend, but the release pipeline is broken again for some reason. I'm so tired of all the lerna related issues, so I decided to change to yarn workspaces. The change is almost done and I expect the release later this week. 

BTW  From our side, the goal is to push allure js integrations out of beta as soon as possible. So I'll add additional focus on JS integrations next few month, and we should be good on releases

**Comment by baev** [comment]
btw we all set, all the changes released, and, finally, the release flow is fully automated 🎉
