### ISSUE TITLE
flag to merge stdout events or turn them off as attachments

### ISSUE THREAD

**Issue by ajaskolski** [allure-framework/allure-js#356]
I use allure-playwright.

At the moment every stdout event create new attachment to allure which can be annoying when You some loggers on. 

As user we also want to have 1 gathered file with all logs or possibility to turn it off.

Add flag/options to turn off stdout from tests or possibility to merge them into 1 file.
st here.

**Comment by vovsemenv** [comment]
duplicate of https://github.com/allure-framework/allure-js/issues/500 fill be fixed soon

**Comment by vovsemenv** [comment]
PR is ready guys 😻
https://github.com/allure-framework/allure-js/pull/580
