### ISSUE TITLE
[Playwright] create custom Allure steps

### ISSUE THREAD

**Issue by VolodymyrDmytriukhinDevPro** [allure-framework/allure-js#373]
I want to have possibility to add allure steps in the PageObject
If I have page object class I want to log it  in allure reporter for example
```
class LoginPage {
   public async fillUserName(name: string): Promise<void> {
      allure.step(`Fill user name "${name}"`);
      ....
   }
}
```

I saw in [playwright reporter](https://github.com/allure-framework/allure-js/blob/a9218f440588ad3e8cfba9755ea29584dfa44ade/packages/allure-playwright/src/index.ts#L49) that AllureRuntime is created after test execution end so as far there is no global variable `allure` - I can't add custom step to the report

**Comment by hananmalka** [comment]
@VolodymyrDmytriukhinDevPro 

I found a solution for this issue. You should just use **test.step** provided by `@playwright-test`

For example:

```
test('Override playwright steps', async ({ page }) => {
  await test.step("Navigate to playwright web site", async()=>{
    await page.goto("https://www.playwright.dev");
  })
});
```

Then, the result will be:

![Screen Shot 2021-12-22 at 12 58 56](https://user-images.githubusercontent.com/14985481/147082684-c0379416-5747-43b3-9aca-89fdd7fb67c7.png)

So in your case you should do:

```
const { test } = require('@playwright/test');

class LoginPage {
   public async fillUserName(name: string): Promise<void> {
      await test.step(`Fill user name "${name}"`, async()=>{
        ....
        ....
   }
}
```

**Comment by baev** [comment]
> You should just use **test.step** provided by `@playwright/test`

yep, thats the way. And we are not going to add separate API for allure-only steps.

**Comment by VolodymyrDmytriukhinDevPro** [comment]
that doesn't help with adding steps to page object,  but anyway thanks for your answer.

**Comment by hananmalka** [comment]
@VolodymyrDmytriukhinDevPro - Why not? 
I implemented it with page object and It works fine.
Take a look on how I did it on the example you provided above. 
This is how it should be done for page object. 

Can you provide an example where it doesn't work?

**Comment by arekon7** [comment]
I solved this for myself as follows: 
```
public static step(stepInfo: string) {
        test.step(stepInfo, async () => {});
    }
```

**Comment by baev** [comment]
update from 2024

There are now two functions Allure provides, `step` and `logStep`:

```ts
import { test } from "@playwright/test";
import * as allure from "allure-js-commons";
import { Status } from "allure-js-commons";

test("Test Authentication", async () => {
  await allure.step("Step 1", async () => {
    await allure.step("Sub-step 1", async (ctx) => {
      await ctx.parameter("foo", "1");
      // ...
    });
    await allure.step("Sub-step 2", async (ctx) => {
      await ctx.parameter("foo", "2");
      // ...
    });
  });
  await allure.logStep("Step 2", Status.SKIPPED);
});
```

See https://allurereport.org/docs/playwright/#divide-a-test-into-steps
