### ISSUE TITLE
Allure support for Jest Testing Framework

### ISSUE THREAD

**Issue by satyabratasaha-me** [allure-framework/allure-js#4]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [x] feature request

#### What is the current behavior?
Currently we have support of Allure with Jasmine Testing Framework.Can we have a feature to support the Jest Testing Framework in the javascript ecosystem.

Link of Jest - (https://facebook.github.io/jest/docs/en/tutorial-react.html)

#### What is the motivation / use case for changing the behavior?
Jest is preferred unit testing tool for React Applications. Having Allure  compatible with Jest can add more nice reports at the end of the execution.

#### Please tell us about your environment:

| Allure version | 2.2.0 |
| --- | --- |
| Test framework | Jest |

#### Other information 

[//]: # (
. e.g. detailed explanation, stacktraces, related issues, suggestions 
. how to fix, links for us to have more context, eg. Stackoverflow, Gitter etc
)

**Comment by baev** [comment]
fixed in #752 & #764
