### ISSUE TITLE
Generate allure report for Playwright + Cucumber combination

### ISSUE THREAD

**Issue by alikhanm86** [allure-framework/allure-js#400]
**Is your feature request related to a problem? Please describe.**
Unable to generate allure report in case of playwright + cucumber combination

**Describe the solution you'd like**
Should be able to generate allure report in case of playwright + cucumber combination

**Steps that I tried**
I'm trying to generate allure reports for my automation framework which is on playwright + cucumber combination. But for me, "allure-results" folder is generated but its blank. Not sure if I'm doing something wrong. Could you anyone pls suggest?

**GitHub Template that I used**: https://github.com/Tallyb/cucumber-playwright
**Cucumber Allure Integration link**: https://github.com/allure-framework/allure-js/blob/master/packages/allure-cucumberjs/README.md

FYI, I don’t have any issues in case of playwright test runner. Above problem is ONLY in case of cucumber playwright.

**Comment by ejunior-trimble** [comment]
I'm using the workaround below as the issue #227 is not implemented yet. It might be helpful for you too.
    "allure-cucumberjs": "^2.0.0-beta.11",
    "cucumber": "^6.0.5",
    "playwright": "^1.14.0",

**Comment by sonalidwivedi** [comment]
I am also working on the Cucumber+Playwright framework using typescript. I am getting the cucumber-html report. Allure report is getting generated, but it is empty. I am using "playwright": "^1.26.0","allure-cucumberjs": "^2.0.0-beta.19". Please let me know if i need to use older versions?

**Comment by epszaw** [comment]
@sonalidwivedi, could you please try the last release?

**Comment by vovsemenv** [comment]
Tested with the latest https://github.com/Tallyb/cucumber-playwright and report creation works fine.

Please update deps and try again 👏
