### ISSUE TITLE
[Playwright] A lot of "route.continue" in allure report after successful test run

### ISSUE THREAD

**Issue by qakos** [allure-framework/allure-js#414]
**Describe the bug**
A lot of "route.continue" in allure report after the successful test run

**To Reproduce**
1. after the successful test run generate and open the allure report

**Screenshots**
![k_n_13-01-2022_01](https://user-images.githubusercontent.com/93794669/149369290-0483515f-95b3-49a9-bef9-cb502317cfdf.png)

**Desktop (please complete the following information):**
Playwright Version: [1.16.2, 1.16.3, 1.17.0, 1.17.1, 1.17.2]
Operating System: [Windows 10, Linux]
Node.js version: [16.13]
Browser: [All, Chromium, Firefox, WebKit]

**Comment by mxschmitt** [comment]
Probably the same as https://github.com/microsoft/playwright/issues/11248

**Comment by ecchochan** [comment]
@qakos
Have you found a workaround or fix for this?
