### ISSUE TITLE
Multiple screen diff sections

### ISSUE THREAD

**Issue by grybykm** [allure-framework/allure-js#416]
**Is your feature request related to a problem? Please describe.**
I'd like to compare screenshots of multiple areas in the page within the same test.

At the moment only it should be only one diff per test otherwise screen diff section is not shown

![image](https://user-images.githubusercontent.com/91597806/150795182-e857febf-f9f1-4ecb-afcd-cecea45b897f.png)

**Describe the solution you'd like**
I'd like to see multiple collapsible screen diff entries ideally with the screenshot name

![image](https://user-images.githubusercontent.com/91597806/150796088-bcc06e20-2146-4397-9987-e6bb0f73ee6c.png)

**Describe alternatives you've considered**
any other options to see multiple screen diffs per test

**Comment by baev** [comment]
BTW multiple image diffs are supported by Allure for a while https://github.com/allure-framework/allure2/pull/1145

**Comment by grybykm** [comment]
For some reason it doesn't work for me with `"@playwright/test": "^1.18.0"` and `"allure-playwright": "^2.0.0-beta.15"`

**Comment by baev** [comment]
that's because playwright by default doesn't support soft assertions. So we expect only one diff per test. It could (and probably will) be changed at some point, but for now I can only suggest crafting your own image diff attachments:

```ts
testInfo.attach('Image Diff', {
  body: Buffer.from(JSON.stringify({
    actual: 'data:image/png;base64,' + actual.toString("base64"),
    expected: 'data:image/png;base64,' + expected.toString("base64"),
    diff: 'data:image/png;base64,' + diff.toString("base64")
  })),
  contentType: 'application/vnd.allure.image.diff'
})
```

**Comment by grybykm** [comment]
Thanks for the tip, let me try. I'd really like to have it working out of the box!

**Comment by mxschmitt** [comment]
Just as a heads up, Soft assertions are coming with Playwright 1.19 https://github.com/microsoft/playwright/issues/7819

**Comment by amrsa1** [comment]
@mxschmitt when do we expect to have this release

**Comment by mxschmitt** [comment]
> @mxschmitt when do we expect to have this release 

We release every month, so probably in 2 weeks it's stable.
