### ISSUE TITLE
After running the test which fails, allure-report folder is not created

### ISSUE THREAD

**Issue by mareru** [allure-framework/allure-js#421]
**Describe the bug**
This is my package.json:  
```
{
  "name": "test-automation",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "allure:generate": "npx allure generate ./allure-results --clean",
    "allure:open": "npx allure open ./allure-report",
    "allure:serve": "npx allure serve",
    "test": "npx playwright test --project=chromium",
    "posttest": "npm run allure:generate"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.18.1",
    "allure-commandline": "^2.17.2",
    "allure-playwright": "^2.0.0-beta.15",
    "playwright": "^1.18.1",
    "prettier": "2.5.1"
  }
}
```
When I run `npm test` and the test fails, I don't have allure-report folder created.   
I get this weird three Y commands in the console.  
 
![image](https://user-images.githubusercontent.com/6464981/152688758-b876e069-9b78-4178-8ecd-83df1652e9c7.png)

If I do manually `npm run allure:generate` and afterwords `npm run allure:open`, then the allure-report is created and I can open the report. 

This is my `playwright.config.ts`:  
```
import { PlaywrightTestConfig, devices } from '@playwright/test';

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
  testDir: './tests',

  /* Maximum time one test can run for. */
  timeout: 5 * 60 * 1000,

  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 15000,
  },

  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,

  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,

  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,

  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'allure-playwright',

  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,

    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'https://my-app.com',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    screenshot: 'on',

    video: 'retain-on-failure',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',

      /* Project-specific settings. */
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    },

    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: {
    //     ...devices['Pixel 5'],
    //   },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: {
    //     ...devices['iPhone 12'],
    //   },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: {
    //     channel: 'msedge',
    //   },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: {
    //     channel: 'chrome',
    //   },
    // },
  ],

  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  // outputDir: 'test-results/',

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   port: 3000,
  // },
};
export default config;
```
If the test passes then everything is fine. 
I have to mention I have one test that I am skipping -` test.skip(...)`
Also I use` test.step()` inside my `test()`

**Expected behavior**
I would expect that the report gets generated even when there is a failure in the test

Can you please help?  
Thanks

**Comment by mareru** [comment]
@serembon It didn't help. The behavior is still the same.  
Do you have another idea?

**Comment by nehasangwan1** [comment]
> Try to set `outputDir: 'allure-results',`

where to set this variable?

**Comment by miguelofbc** [comment]
I am seeing the same issue on my end. Is there any update?

**Comment by hsuraweera** [comment]
Did anyone solve this? Especially with Gitlab CI, this is not working. It only generates the allure-results folder but not the report folder.

**Comment by vrinda-cmd** [comment]
Any one found the solution because I am having same problem If one test case fails it is generating allure results but not report

**Comment by epszaw** [comment]
Firstly, could you update `allure-playwright` to the latest version (`2.12.0`) and try to run tests again?

**Comment by Sanberqui18** [comment]
I just tried using the latest version (2.13.0) and was able to reproduce it:

`"test": "npx playwright test",`
`"allure-generate": "npx allure generate allure-results --clean && npx allure open",`
`"allure-clean": "rm -r allure-results/ allure-report test-results",`
`"test:allure": "npm run allure-clean && npm run test && npm run allure-generate"`

When all tests pass:
<img width="740" alt="Screen Shot 2024-03-05 at 10 32 29 PM" src="https://github.com/allure-framework/allure-js/assets/119998036/c7885d92-51fd-4aee-9bff-9870a3a72af4">

When at least one test fails:
<img width="1124" alt="Screen Shot 2024-03-05 at 10 38 37 PM" src="https://github.com/allure-framework/allure-js/assets/119998036/f407ba12-935f-42f0-a7b4-84f188a5f19e">
<img width="218" alt="Screen Shot 2024-03-05 at 10 43 52 PM" src="https://github.com/allure-framework/allure-js/assets/119998036/5bd8e4e9-8368-46d4-b105-8bc05f23434c">

After this I have to manually run `"allure-generate": "npx allure generate allure-results --clean && npx allure open"` to generate the report folder and open the Allure report.

**Comment by epszaw** [comment]
I see. Will try to figure out, what's going wrong there

**Comment by baev** [comment]
That's the way npm works. The suggested way would be to use [npm-run-all](https://www.npmjs.com/package/npm-run-all) with the `--continue-on-error` option:

```json
"allure:clean": "rimraf ./out/allure-results ./out/allure-report"
"allure:report": "allure generate --single-file ./out/allure-results -o ./out/allure-report"
"pw:test": "playwright test"
"test": "run-s -c allure:clean pw:test allure:report"
```
