### ISSUE TITLE
Allure test steps don't shows in beforeAll

### ISSUE THREAD

**Issue by sedoy604** [allure-framework/allure-js#422]
**I am calling beforeAll hook.**
`test.beforeAll(async ({`
		`browser,`
	`}) => {`
		`const context = await browser.newContext()`
		`page = await context.newPage()`
		`await Login(page, 'some url')`
	`})`

In `await Login(page, 'some url'])` i have several steps which is not shows in allure report
I have to say that these steps are showing in allure report when I call my Login function in a test body

**Comment by vovsemenv** [comment]
This works in the latest version of `allure-playwright`. if this still not work for you case consider opening new issue with more detailed info about your Login method 🙏

```
    "@playwright/test": "^1.24.2",
    "allure-playwright": "^2.0.0-beta.18"
```

maybe you forgot `await` somewhere?


## Demo

```ts
import test, { expect } from "@playwright/test";

const testStep = async () =>
  await test.step("beforeEach 1", async () => {
    await test.step("beforeEach 1.1", async () => {
      await test.step("beforeEach 1.1.1", async () => {
        expect(5).toBe(7);
      });
    });
  });

test.beforeAll(async () => {
  await testStep();
});

test("test-main-body", () => {});
```
