### ISSUE TITLE
Test case status was passed ,even though couple of steps were failed

### ISSUE THREAD

**Issue by RollerIn** [allure-framework/allure-js#425]
Hello Team,

Even there re couple of steps were failed, the test cases displaying as passed on the reports.

![image](https://user-images.githubusercontent.com/17290705/155517427-9f1e157c-a7f7-46e4-8728-cc3bfa20f1bb.png)

Is there any way to fix this or can we write override the test case status?

**Comment by baev** [comment]
BTW Allure doesn't control test flow. You can consider it as a logger - we only display the information that provided to us by test framework. For example, you can use try-catch block and ignore the exception. In that case test will be passed but some steps marked as failed
