### ISSUE TITLE
Can't open allure report in browser

### ISSUE THREAD

**Issue by kitoymonster** [allure-framework/allure-js#426]
**Describe the bug**
Whenever I try to open the report, all I see is this error in chrome. This was working previously.

<img width="663" alt="Screen Shot 2022-03-01 at 11 39 02 AM" src="https://user-images.githubusercontent.com/18339541/156100396-d7fd2e66-2251-4441-8f50-667280109ed2.png">

This page isn’t working
192.168.254.108 didn’t send any data.
ERR_EMPTY_RESPONSE

The files are there in the allure reports folder.
<img width="364" alt="Screen Shot 2022-03-01 at 11 41 05 AM" src="https://user-images.githubusercontent.com/18339541/156100579-1fa28545-c556-4e31-aa55-66b9222086f7.png">

**To Reproduce**
1. Run a test that will generate files in allure results
2. Create allure report
3. Open allure report

**Expected behavior**
Allure results will show up in the browser

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome Version 98.0.4758.109 (Official Build) (x86_64)
 - Used as part of Webdriverio v7.16.14 (allure-js-commons v1.3.2)

**Comment by krrishna1** [comment]
What is the solution for this issue. What is the cause for such issues firstly? I'm facing the same issue at my work. Unable to open the Allure reports and get this error in the browser - 

"This site can’t be reachedThe webpage at http://192.168.4.23:55882/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SOCKET_NOT_CONNECTED"

 Please help.

**Comment by wilson-viva** [comment]
Same I'm getting the same issue can someone please help!
