### ISSUE TITLE
QUESTION(playwright) Add a description of the running test?

### ISSUE THREAD

**Issue by DvDream** [allure-framework/allure-js#427]
I don't know if it is already implemented, but since I couldn't figure it out, is there a way to add a description about the running test?
Something like this: https://docs.qameta.io/allure/#_test_case_page where you can find to the right a description of the test.

If it already exists, what function should I use?

**Comment by Mictim** [comment]
https://github.com/allure-framework/allure-js/pull/417
But we are still waiting for the next version.

**Comment by DvDream** [comment]
> #417 But we are still waiting for the next version.

Yes I know. Actually I've seen that commit after I posted this question..I suppose we need to wait..
