### ISSUE TITLE
(allure-playwright) Add "major" and "medium" severity levels?

### ISSUE THREAD

**Issue by DvDream** [allure-framework/allure-js#428]
Is it possible to add "Major" and "Medium" as severity levels? I'm asking since they're also used at my office to tag an issue. a VERY BRIEF detail of these kinds of tag:

"Major" :  "Major loss of function".
"Medium": "Has the protential to affect progress."

in this way, one should be able to see also this levels on the severity graph just by setting:

`allure.severity("major")`
`allure.severity("medium")`

Thank you for your attention

**Comment by vuk12** [comment]
Which string values are supported for "severity" since whatever I put it will print me "Severity: normal".
Entering parameter is string type, that gives flexibility, someone will use "minor","medium","high",
but others will use "P4","P3","P2",...

Currently it is not working if I put:
allure.severity("P1");

**Comment by DvDream** [comment]
> Which string values are supported for "severity" since whatever I put it will print me "Severity: normal". Entering parameter is string type, that gives flexibility, someone will use "minor","medium","high", but others will use "P4","P3","P2",...
> 
> Currently it is not working if I put: allure.severity("P1");

According to allure-js-commons library, these are the supported strings:

https://github.com/allure-framework/allure-js/blob/bb43bf51228c17a22b798d97bae3e13cfeca8f97/packages/allure-js-commons/src/model.ts#L130

I also tried to modify some parts of the code in linked files to see If I could manage to add new severity levels on graph, but with no results. I'm starting to think that the rendering part comes from the original Allure Framework, which cannot be directly modified I suppose.

**Comment by vovsemenv** [comment]
@DvDream is right. This field is processed with reporter side. If you want this thing to happen consider opening issue to actual framework https://github.com/allure-framework/allure2 . If you using TestOps you can use this functionality already with custom fields
