### ISSUE TITLE
[allure-playwright]: Need a new feature to add an attachment to a step.

### ISSUE THREAD

**Issue by autTestUser** [allure-framework/allure-js#436]
**Is your feature request related to a problem? Please describe.**
Attaching a screenshot to an allure step is not working as the screenshots are being added at the end of the test instead of in the step in the allure reports.

**Describe the solution you'd like**
Add a new feature to add an attachment to a step.

**Additional context**
The below code should add an attachment to the step "MyStep"
```
await test.step('MyStep', async () => {
	const screenshot = await page.screenshot();
        testInfo.attach('screenshot', { body: screenshot, contentType: 'image/png' });
	throw new Error("MyCustomError"); // this step is added to mark the test step as fail
});
```

**Comment by baev** [comment]
what version of allure-playwright are you using?

**Comment by autTestUser** [comment]
^2.0.0-beta.15

**Comment by baev** [comment]
allure-playwright was reworked in 2.0.0-beta.16, could you please confirm that issue still exists

**Comment by autTestUser** [comment]
Yes, the issue still exists on 2.0.0-beta.16.

**Comment by autTestUser** [comment]
Any updates on this?

**Comment by baev** [comment]
https://github.com/microsoft/playwright/issues/14364

**Comment by Mealinda** [comment]
Do we have any updates regarding this issue ?

**Comment by wtclark** [comment]
This would be a great feature and very helpful if implemented!
