### ISSUE TITLE
Can the default steps be disabled from allure-playwright reports?

### ISSUE THREAD

**Issue by autTestUser** [allure-framework/allure-js#437]
We would like to add our own steps in allure reports using "test.step" instead of having the built-in detailed steps which are already added by the playwright for every browser action performed. Is there a way to disable it?

**Comment by autTestUser** [comment]
Any updates on this?

**Comment by Agustin-DeLuca** [comment]
I also want to know about this. I would like to customize the reporter. For instance, I don't want to have every browser action in the report as a step or attach every stdout

**Comment by StasGrishaevTutu** [comment]
any updates ?

**Comment by baev** [comment]
There is a reporter option called `detail`. You can set it to false to disable reporting of playwright API calls and only include `test.step` actions in the report.

See https://github.com/allure-framework/allure-js/tree/master/packages/allure-playwright#reporter-options for details

**Comment by StasGrishaevTutu** [comment]
alright ! thanks for quick response.

**Comment by epszaw** [comment]
@autTestUser, @StasGrishaevTutu does the [proposed solution](https://github.com/allure-framework/allure-js/issues/437#issuecomment-1584614080) solve the initial problem?

**Comment by StasGrishaevTutu** [comment]
> @autTestUser, @StasGrishaevTutu does the [proposed solution](https://github.com/allure-framework/allure-js/issues/437#issuecomment-1584614080) solve the initial problem?

yep, solution works for me.
