### ISSUE TITLE
[QUESTION] - How to correctly generate issue links on allure-cucumberjs?

### ISSUE THREAD

**Issue by DvDream** [allure-framework/allure-js#456]
Hi, thank you for the brand new support for cucumberjs 8+. I'm using cucumber 8.3.1 + playwright 1.22.2 and I'm trying to generate an allure report with an issue link doing like in the documentation: 

```
export default class Reporter extends CucumberJSAllureFormatter {
  constructor(options) {
    super(
      options,
      new AllureRuntime({ resultsDir: "./allure-results" }),
      {
        labels: {
          epic: [/@feature:(.*)/],
          severity: [/@severity:(.*)/]
        },
        links: {
          issue: {
            pattern: [/@issue=(.*)/],
            urlTemplate: "https://jira_url/browse/%s"
          }
        }
      }
    );
  }
}
```
but when I try to use the @issue annotation before the Scenario:

```    
@issue=issue_name
Scenario:
#Whatever
```

in the report I only see a tag labeled '@issue=issue_name' instead of a link. I used to use allure-playwright which comes with the function

```
    allure.issue({
        url: "https://jira_url/browse/issue_name",
        name: "issue_name",
    });
```

effectively generating me a link in the final report. So how should I correctly use this functionality with cucumber?

**Comment by lamartire** [comment]
@DvDream the PR was merged. Check the config's updates in the linked PR or README file

**Comment by DvDream** [comment]
Thank you! I appreciate that, I'll wait for the next release then ;D
