### ISSUE TITLE
[allure-js] Is it possible to add actual request and response in the steps? 

### ISSUE THREAD

**Issue by gg-jaycee-suarez** [allure-framework/allure-js#469]
Is it possible to attach actual request and response in the test steps? 

`e.g in Python

allure.attach() ?`

**Comment by gg-jaycee-suarez** [comment]
I want to add in the report that each time I send request  from a test endpoint I can add it in the report both  request and response.

**Comment by vovsemenv** [comment]
you can use playwright attachments and is will aper in you allure report

```ts
import { test } from "@playwright/test";
import { allure } from "allure-playwright";
test("simpleTest", async ({ page }, testInfo) => {
  allure.epic("this test is epic");
  testInfo.attach("filename.txt"); // attach any files like this

  await page.goto("https://web.telegram.org/k/");
  test.expect(true).toBe(false);
});

```

**Comment by gg-jaycee-suarez** [comment]
@vovsemenv thank you, I am able to attach the payload request and response of the API. However it should be inside the Given, When and Then test steps only. The 'this.attach()' is available only inside the Given.. 


And also the attachments are added after the last step of the feature.

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/104751000/181865080-74adb29b-b84a-4f37-8d66-f19fd8a04575.png">

**Comment by vovsemenv** [comment]
For now you can't see step attachments due to https://github.com/microsoft/playwright/issues/14364 .
also added more detailed info of steps and attachments usage in README

**Comment by vovsemenv** [comment]
@gg-jaycee-suarez with the new version on cucumber-integration `this.attach` will be available inside Given, When and Then

**Comment by vovsemenv** [comment]
Now you can use `this.atach()` in cucumber integration.
update and read more https://github.com/allure-framework/allure-js/tree/master/packages/allure-cucumberjs#using-allure-api
