### ISSUE TITLE
Does playwright  support allure reporting features like addstep,adddescription,addfeature etc

### ISSUE THREAD

**Issue by jyotibora-sap** [allure-framework/allure-js#476]
I have install npm install @wdio/allure-reporter --save-dev this dependency and imported allure-reporter to use above feature.

Try adding these steps in my code:
      //allureReporter.addStep('Enter UserID as',await basemethod.readDataFromExcel("TestData.xlsx","Login",2, 1));

      //allureReporter.addStep('Enter Password as',await basemethod.readDataFromExcel("TestData.xlsx","Login",2, 1));

but this addstep is not working

**Comment by vovsemenv** [comment]
`@wdio/allure-reporter` is a separate reporter from other repo with other maintainers.
You can use https://github.com/allure-framework/allure-js/tree/master/packages/allure-playwright where these features already available.

**Comment by jyotibora-sap** [comment]
@vovsemenv  : Thanks for the update.It did help
