### ISSUE TITLE
Generating correct report for cucumber used in wdio

### ISSUE THREAD

**Issue by akshay-sanganwar** [allure-framework/allure-js#483]
**Describe the bug**
Not gtting correct cucumber report. Generated report is showing each cucumber step as test case. Each cucumber feature as Test suite. Please find attached the screen shots,

<img width="448" alt="features" src="https://user-images.githubusercontent.com/27959886/185622646-968761d3-b9d0-43d0-8509-bf9e109f0906.PNG">
<img width="443" alt="suites-Should be scenarios" src="https://user-images.githubusercontent.com/27959886/185622649-d6ed9ba2-a2aa-487f-815c-6f021cf150c1.PNG">

**To Reproduce**
run the simple test case using wdio, cucumber, Jest, chai, Please find the dependency file which package.json. as below,

`{
  "name": "@rcg/testing-automation-core",
  "version": "1.0.33",
  "description": "Testing Automation Core Framework",
  "repository": "bitbucket:rccl/rccl-rdm-testing-automation-core",
  "publishConfig": {
    "registry": "https://rccl.jfrog.io/artifactory/api/npm/rcg-npm/"
  },
  "main": "index.js",
  "scripts": {
    "build": "tsc --build && npm run copy-files-dist",
    "clean": "rimraf dist/ && rimraf reports/ && rimraf hiptest/*.xml && rimraf *.tmp",
    "clean-build": "npm run clean && npm run build && npm run lint",
    "local": "npm run clean-build && wdio ./e2e/conf/wdio.conf.local.js",
    "test": "npm run clean-build && wdio ./e2e/conf/wdio.conf.js",
    "lint": "eslint ./e2e ./api ./common",
    "lint-fix": "eslint --fix ./e2e ./api ./common",
    "api": "npm run clean-schema && jest --coverage api/test-suites/GlobalizationServices.spec.ts api/test-suites/SchemaGenerator.spec.ts",
    "unit-test": "jest --detectOpenHandles --coverage",
    "prepare": "husky install",
    "clean-schema": "rimraf JsonSchema/schema.json",
    "copy-files-dist": "npx copyfiles .npmrc dist",
    "release": "npx release-it --ci"
  },
  "keywords": [
    "automated-testing",
    "framework"
  ],
  "author": "Royal Caribbean",
  "license": "ISC",
  "devDependencies": {
    "@babel/plugin-transform-modules-commonjs": "^7.17.7",
    "@babel/preset-env": "^7.16.11",
    "@types/jsonpath": "^0.2.0",
    "@typescript-eslint/eslint-plugin": "^5.15.0",
    "@typescript-eslint/eslint-plugin-tslint": "^5.15.0",
    "@typescript-eslint/parser": "^5.15.0",
    "eslint": "^8.11.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-cucumber": "^2.0.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-wdio": "^7.19.4",
    "husky": "^7.0.4",
    "lint-staged": "^12.3.6",
    "prettier": "^2.6.0",
    "rimraf": "^3.0.2",
    "typescript": "^4.6.2"
  },
  "dependencies": {
    "@types/chai": "^4.3.0",
    "@types/jest": "^27.4.1",
    "@types/node": "^17.0.21",
    "@types/node-fetch": "^2.6.1",
    "@wdio/browserstack-service": "^7.17.4",
    "@wdio/cli": "^7.17.4",
    "@wdio/cucumber-framework": "^7.17.3",
    "@wdio/dot-reporter": "^7.17.3",
    "@wdio/junit-reporter": "^7.17.3",
    "@wdio/local-runner": "^7.17.4",
    "@wdio/selenium-standalone-service": "^7.17.3",
    "@wdio/spec-reporter": "^7.17.3",
    "ajv": "^8.10.0",
    "chai": "^4.3.6",
    "csv-parser": "^3.0.0",
    "dotenv": "^16.0.0",
    "jest": "^27.5.1",
    "json-schema-generator": "^2.0.6",
    "jsonpath": "^1.1.1",
    "log4js": "^6.4.3",
    "mkdirp": "^1.0.4",
    "module-alias": "^2.2.2",
    "moment": "^2.29.2",
    "node-fetch": "2.6.6",
    "ts-jest": "^27.1.3",
    "wdio-chromedriver-service": "^7.3.0",
    "wdio-cucumberjs-json-reporter": "^4.4.0",
    "wdio-ms-teams-service": "^0.1.9",
    "yaml-reader": "^1.0.3"
  },
  "_moduleAliases": {
    "@check": "e2e/support/check",
    "@config": "e2e/config",
    "@pages": "e2e/pages",
    "@helpers": "e2e/helpers",
    "@steps": "e2e/steps",
    "@utils": "e2e/support/utils",
    "@actions": "e2e/support/actions",
    "@assertions": "e2e/assertions",
    "@support": "e2e/support",
    "@resources": "e2e/resources"
  },
  "eslintIgnore": [
    "e2e/conf/wdio.conf.js",
    "e2e/conf/wdio.conf.local.js"
  ],
  "lint-staged": {
    "*.{js,css,md}": "prettier --write",
    "*.ts": "eslint --cache --fix"
  }
}
`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - windows
 - Browser is chrome
 - Version of chrome is 104

**Smartphone (please complete the following information):**

**Additional context**
XML file from generated Allure-Results folder,

`<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1659514457373' stop='1659514571813'>
    <name>LAF USA: Cruise Search: LAF Pricing on Itinerary Card (uid:98751415-532e-4a61-875d-c1fb8c4284b7)</name>
    <title>LAF USA: Cruise Search: LAF Pricing on Itinerary Card (uid:98751415-532e-4a61-875d-c1fb8c4284b7)</title>
    <test-cases>
        <test-case start='1659514457374' status='passed' stop='1659514481208'>
            <name></name>
            <title></title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-5'/>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-5'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-102.0.5005.63'/>
                <parameter kind='argument' name='browser' value='chrome-102.0.5005.63'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1659514481209' status='passed' stop='1659514558616'>
            <name>Given I am on country "USA" Cruise Search</name>
            <title>Given I am on country "USA" Cruise Search</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-5'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-102.0.5005.63'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1659514558616' status='passed' stop='1659514570569'>
            <name>When I select an itinerary card with ten or more sailings</name>
            <title>When I select an itinerary card with ten or more sailings</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-5'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-102.0.5005.63'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1659514570569' status='passed' stop='1659514571609'>
            <name>Then the LAF for the Right Panel should match the price on the itinerary card</name>
            <title>Then the LAF for the Right Panel should match the price on the itinerary card</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-5'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-102.0.5005.63'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1659514571609' status='passed' stop='1659514571812'>
            <name>And the LAF date for the Right Panel should match the date on the itinerary card</name>
            <title>And the LAF date for the Right Panel should match the date on the itinerary card</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-5'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-102.0.5005.63'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1659514571812' status='passed' stop='1659514571812'>
            <name></name>
            <title></title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-5'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='chrome-102.0.5005.63'/>
            </parameters>
            <steps/>
            <attachments/>
        </test-case>
    </test-cases>
</ns2:test-suite>`

**Comment by lamartire** [comment]
Could you please tell your `@cucumber/cucumber`, `allure-cucumberjs` versions?
I've tried to reproduce the problem with following feature:

```feature
@foo
Feature: startpage example search
  Scenario: performs search by given query
    Given open "https://www.startpage.com/"
    When type "hello world" into search input
    And click search button
    Then results page loaded
    And it contains more than 1 result
```

And the result looks correct:

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/13414205/185636513-1579eeca-cd06-4dfc-ac84-563082175f0d.png">

The best option would be an example project from your side.

**Comment by akshay-sanganwar** [comment]
"devDependencies": {
    "@types/chai": "^4.3.1",
    "@types/chai-string": "^1.4.2",
    "@typescript-eslint/eslint-plugin": "^5.15.0",
    "@typescript-eslint/eslint-plugin-tslint": "^5.15.0",
    "@typescript-eslint/parser": "^5.15.0",
    "@wdio/allure-reporter": "^7.20.7",
    "@wdio/cli": "^7.19.5",
    "@wdio/cucumber-framework": "^7.19.5",
    "@wdio/dot-reporter": "^7.19.5",
    "@wdio/local-runner": "^7.19.5",
    "@wdio/selenium-standalone-service": "^7.20.3",
    "@wdio/spec-reporter": "^7.19.5",
    "chai": "^4.3.6",
    "chai-sorted": "^0.2.0",
    "chai-string": "^1.5.0",
    "chromedriver": "^102.0.0",
    "date-and-time": "^2.3.1",
    "eslint": "^8.11.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-react": "^7.29.4",
    "husky": "^7.0.4",
    "lint-staged": "^12.3.6",
    "module-alias": "^2.2.2",
    "prettier": "^2.6.0",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.3",
    "wdio-chromedriver-service": "^7.3.2",
    "wdio-cucumberjs-json-reporter": "^4.4.1"
  },

> Could you please tell your `@cucumber/cucumber`, `allure-cucumberjs` versions? I've tried to reproduce the problem with following feature:
> 
> ```
> @foo
> Feature: startpage example search
>   Scenario: performs search by given query
>     Given open "https://www.startpage.com/"
>     When type "hello world" into search input
>     And click search button
>     Then results page loaded
>     And it contains more than 1 result
> ```
> 
> And the result looks correct:
> 
> <img alt="image" width="1401" src="https://user-images.githubusercontent.com/13414205/185636513-1579eeca-cd06-4dfc-ac84-563082175f0d.png">
> 
> The best option would be an example project from your side.

"devDependencies": {
    "@types/chai": "^4.3.1",
    "@types/chai-string": "^1.4.2",
    "@typescript-eslint/eslint-plugin": "^5.15.0",
    "@typescript-eslint/eslint-plugin-tslint": "^5.15.0",
    "@typescript-eslint/parser": "^5.15.0",
    "@wdio/allure-reporter": "^7.20.7",
    "@wdio/cli": "^7.19.5",
    "@wdio/cucumber-framework": "^7.19.5",
    "@wdio/dot-reporter": "^7.19.5",
    "@wdio/local-runner": "^7.19.5",
    "@wdio/selenium-standalone-service": "^7.20.3",
    "@wdio/spec-reporter": "^7.19.5",
    "chai": "^4.3.6",
    "chai-sorted": "^0.2.0",
    "chai-string": "^1.5.0",
    "chromedriver": "^102.0.0",
    "date-and-time": "^2.3.1",
    "eslint": "^8.11.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-react": "^7.29.4",
    "husky": "^7.0.4",
    "lint-staged": "^12.3.6",
    "module-alias": "^2.2.2",
    "prettier": "^2.6.0",
    "ts-node": "^10.7.0",
    "typescript": "^4.6.3",
    "wdio-chromedriver-service": "^7.3.2",
    "wdio-cucumberjs-json-reporter": "^4.4.1"
  },

**Comment by lamartire** [comment]
Is it possible to use original cucumber runner instead of wdio one in your case?

**Comment by akshay-sanganwar** [comment]
"@wdio/cucumber-framework": "^7.19.5",
    "@wdio/dot-reporter": "^7.19.5",
    "@wdio/local-runner": "^7.19.5",
    "@wdio/selenium-standalone-service": "^7.20.3",
======================================
    "wdio-chromedriver-service": "^7.3.2",
    "wdio-cucumberjs-json-reporter": "^4.4.1"

**Comment by akshay-sanganwar** [comment]
> Is it possible to use original cucumber runner instead of wdio one in your case?

will try and let you know.

**Comment by akshay-sanganwar** [comment]
> Is it possible to use original cucumber runner instead of wdio one in your case?

How do you run your tests to produce this result.

**Comment by akshay-sanganwar** [comment]
> > Is it possible to use original cucumber runner instead of wdio one in your case?
> 
> will try and let you know.

This is our hooks file for each scenerio, Can you please try it, also the way you run your scenarios...

import { Base } from '@pageObjects/base/basePage';
import * as baseConfig from '@conf/base.config.json';
import * as buildConfig from '@conf/buildConfig.json';
import {
  Before,
  setDefaultTimeout
} from '@cucumber/cucumber';
const basePage = new Base();
setDefaultTimeout(baseConfig.cucumberDefaultTimeOut);

/**
 * check for a valid browser session before each step
 */
Before(async (scenario) => {
  const env = await basePage.getEnvironment();
  if (env !== 'DY') {
    const initialUrl = '/?country=USA&autsession=1';
    let url: string =
      buildConfig.extraCookie && buildConfig.extraCookie.length > 0
        ? `${initialUrl}&${buildConfig.extraCookie.replace(/,/g, '&')}`
        : initialUrl;
    await browser.url(url);
  } else {
    await browser.url('');
  }
  await basePage.addAutomationCookie();
  await basePage.addExtraCookie(buildConfig.extraCookie);
});

**Comment by akshay-sanganwar** [comment]
Any update on the issue?

**Comment by lamartire** [comment]
Sorry for delay. We need to contribute to `wdio` to fix the issue. It'll take some time. Now I can recommend to run the tests with cucumber runner. Bear with me, I plan to research possible solutions very soon

**Comment by akshay-sanganwar** [comment]
Can you suggest a way, any link(which will tell how to) or command , we can run the cucumber scenarios which are built with wdio with cucumber runner.

**Comment by lamartire** [comment]
Does `npx cucumber-js` work for you?

**Comment by akshay-sanganwar** [comment]
Any update? Sorry but,  Our management is asking us the questions.

**Comment by akshay-sanganwar** [comment]
Any Update??

**Comment by baev** [comment]
@akshay-sanganwar we do have this issue on radar, no need to create extra notifications, it will not change anything. That's open source, you can create a patch by yourself and provide us a PR. 

For urgent requests there is a paid support available (mail to allure at qameta.io)

**Comment by cheshi-mantu** [comment]
@akshay-sanganwar 
there was a question towards you Aksahy
> Does npx cucumber-js work for you?
could you please revert to it?

**Comment by jperozo-zaelot** [comment]
@akshay-sanganwar 
Use this:
reporters: ['spec', 'dot', ['allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: true,
        **useCucumberStepReporter: true,**
    }]],

**Comment by akshay-sanganwar** [comment]
> @akshay-sanganwar there was a question towards you Aksahy
> 
> > Does npx cucumber-js work for you?
> > could you please revert to it?

Sorry for late reply, I was offline for awhile. we can not use this, as our project is using '@wdio/cucumber' all over instead of '@cucumber/cucumber'. we can not change the the legacy code.

**Comment by akshay-sanganwar** [comment]
> @akshay-sanganwar we do have this issue on radar, no need to create extra notifications, it will not change anything. That's open source, you can create a patch by yourself and provide us a PR.
> 
> For urgent requests there is a paid support available (mail to allure at qameta.io)

May I know the proc to go through the relevant code and process which I can follow to work on it myself.

**Comment by cheshi-mantu** [comment]
Hi, the faulty part is the 3rd party legacy integration developed by wdio, you need to consult them on how to proceed.

**Comment by epszaw** [comment]
As far as I see, the problem relates to `wdio`. They have [`addFeature`](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-allure-reporter/src/index.ts#L415) event handler what calls manually by the user or by the [`wdio-cucumber-framework`](https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-cucumber-framework) integration. From my point, the problem relates to `wdio-cucumber-framework` and better to ask guys to check feature processing order, the allure integration looks pretty nice and shouldn't have any problem, except migration to the lastest version of `allure-js-commons`, but anyway, it shouldn't be a problem.

**Comment by epszaw** [comment]
I opened an issue. Stay in touch! 🙏

**Comment by epszaw** [comment]
So, I did the fix. Let's wait for the decision from `wdio` side. Of course, you can clone my revision and test it locally on your project to be sure, that everything works as expected

**Comment by epszaw** [comment]
The fix was merged. Please, follow `wdio` for updates. When the new version will be released, the problem should disappear
