### ISSUE TITLE
Show playwright annotations in report

### ISSUE THREAD

**Issue by vovsemenv** [allure-framework/allure-js#490]
Currently playwright annotations don't appear in report.
Allure need to show them as parameters.

**Comment by vovsemenv** [comment]
None actually need it i guess.

**Comment by zzoubian** [comment]
Sorry, to reopen this ticket, but this would be useful if it was added. Currently, to integrate playwright with Xray, you need to add annotations to your test.

**Comment by zzoubian** [comment]
It would be nice to be able to see these annotations in the allure reports.
