### ISSUE TITLE
Playwright | Hovering over a graph and fetching value from Tooltip doesn't work

### ISSUE THREAD

**Issue by jyotibora-sap** [allure-framework/allure-js#497]
Please find the below code and attach Screenshot for same.

import test from "../src/1-Base/utils/Fixtures";

let portfolioid,fixedincomevalue,equityvalue :any;
const xpathgraphele = `(//*[local-name()='svg']//*[name()='g' and @class='highcharts-series-group']//*[@class='highcharts-markers highcharts-series-0 highcharts-line-series highcharts-tracker']//*)`;

const xpathgraphportfolioId= `(//*[local-name()='svg' and @class='highcharts-root']//*[starts-with(text(),'P')])[2]`;
const xpathfixedincometext = `//span[text()='Fixed Income']`;
const xpathfixedincomevalue = `//span[text()='Fixed Income']//following-sibling::span`;
const txpathequitytext = `//span[text()='Equity']`;
const xpathequityvalue = `//span[text()='Equity']//following-sibling::span`
test('homepage has Playwright in title and get started link linking to the intro page', async ({ basemethod,page,loginPageLocator,dashboardLocator,saveForFutureLocator }) => {

   //await page.waitForEvent()
   await basemethod.gotoURL("https://goedemoqa.ftwealth.com/");
   await basemethod.filltextbox(loginPageLocator.EMAIL_ID, await basemethod.readDataFromExcel("TestData.xlsx","Login",2, 2));     //positive 
   //fill - password
   await basemethod.filltextbox(loginPageLocator.PASSWORD_ID, await basemethod.readDataFromExcel("TestData.xlsx","Login",2, 3));   //positive
   //click - login button
   await (await basemethod.clickbutton(loginPageLocator.LOGIN_BUTTON_ID)).click();  
   await (await basemethod.clickbutton(dashboardLocator.CREATE_DASHBOARD)).click(); 

   await (await basemethod.clickbutton(saveForFutureLocator.EXPAND_ROW_ID)).click();
   await (await basemethod.clickbutton(dashboardLocator.BUTTON_VIEWPROJECTIONS)).click();
   await (await basemethod.clickbutton(saveForFutureLocator.PROJECTED_GOAL_PATH)).click();

   const elegraphs = await page.$$(xpathgraphele);
   console.log(elegraphs.length);
   
   for (var index= 2; index < elegraphs.length ; index++) {
     // xpathgraphele = xpathgraphelestart.concatindex+xpathgrapheleend;
   //  await page.waitForTimeout(100);
     await page.locator(xpathgraphele+"["+index+"]").click;
      await page.locator(xpathgraphele+"["+index+"]").highlight();
      await page.locator(xpathgraphele+"["+index+"]").hover();
      //await page.waitForTimeout(100);
      portfolioid= page.locator(xpathgraphportfolioId).textContent();
      console.log(portfolioid);
      fixedincomevalue = page.locator(xpathfixedincomevalue).textContent();
      console.log(fixedincomevalue);
     equityvalue= page.locator(xpathequityvalue).textContent();
     console.log(equityvalue);
}        

});
<img width="461" alt="app_graph1" src="https://user-images.githubusercontent.com/110669095/189586470-519b10e2-648e-404d-bdac-4baaf6a98f1e.PNG">

<img width="574" alt="app_graph2" src="https://user-images.githubusercontent.com/110669095/189586514-700f224f-c30d-40b3-b3fc-5c273faa7763.PNG">

**Comment by vovsemenv** [comment]
Allure-js repo is is not meant to be playwright support page. Feel free to open Issues here if you have only allure-reporter specific problems

P.s playwright have awesome slack community https://aka.ms/playwright-slack where you can ask you questions

**Comment by jyotibora-sap** [comment]
@vovsemenv : Sorry for the wrong folder description, can you just check the query which i have posted,it is related to Playwright
