### ISSUE TITLE
Selective launch of autotests for the Playwright framework

### ISSUE THREAD

**Issue by snata97** [allure-framework/allure-js#498]
At the moment, the possibility of selective launch is not implemented at the adapter level of the Playwright framework, so Allure TestsOps runs all tests.

**Comment by ryust-ax** [comment]
I don't have experience with Playwright as a primary runner.  But check out my post(s) as possible work-around or inspiration perhaps?
https://github.com/allure-framework/allure-js/issues/442
https://github.com/codeceptjs/CodeceptJS/issues/3544
