### ISSUE TITLE
Ansi color shown as characters [playwright]

### ISSUE THREAD

**Issue by eyalf007** [allure-framework/allure-js#499]
**Describe the bug**
ANSI color shown as characters 

**Expected behavior**
Shown ANSI colors same as in build in playwright report
![image](https://user-images.githubusercontent.com/110524000/191739620-baecbe5e-6b48-4560-90d9-220f10357a12.png)

Actual:
![image](https://user-images.githubusercontent.com/110524000/191739462-b3f14e90-85ea-42b2-b8b6-49f87780d595.png)

**Comment by OShalaby** [comment]
same issue, any help with this one?
