### ISSUE TITLE
allure-mocha - TypeError: Cannot read property 'epic' of undefined

### ISSUE THREAD

**Issue by fescobar** [allure-framework/allure-js#50]
I'm trying to do this configuration, but allure is undefined. Do you have any example calling allure method from mocha tests using TypeScript?
```
    "allure-mocha": "2.0.0-beta.6",
```

```
// es-modules
import { allure } from 'allure-mocha/runtime';
// or commonjs
const { allure } = require('allure-mocha/runtime');

it('is a test', () => {
  allure.epic('Some info');
});
```

```
TypeError: Cannot read property 'epic' of undefined
```
Thank you

**Comment by just-boris** [comment]
It worked in my project.

Can you share your tech stack? What bundlers, compilers or other tools do you use?

**Comment by fescobar** [comment]
I've added it a simple example. Install and execute the test (follow the README.md)
[example-mocha.zip](https://github.com/allure-framework/allure-js/files/3569557/example-mocha.zip)
Thank you so much

**Comment by fescobar** [comment]
Hi @just-boris did you check my project? Thanks in advance.

**Comment by fescobar** [comment]
@sseliverstov can you check the example to reproduce the error? 
https://github.com/allure-framework/allure-js/issues/50#issuecomment-527450874

Thanks

**Comment by ryparker** [comment]
Same issue here. Is typescript a requirement?

**Comment by ryparker** [comment]
Can we get an update on this? This is blocking my ability to use this library. I've even cloned the allure-mocha example just to test this in a typescript environment and it is also giving this same error. Is the allure-mocha library not meant to be used outside of typescript??

**Comment by dzotovwork** [comment]
the same problem

**Comment by dzotovwork** [comment]
![image](https://user-images.githubusercontent.com/43908260/80400690-d3b3d600-88c3-11ea-9e83-0d58ed99cd13.png)
it is master branch from https://github.com/sskorol/mocha-allure2-example
just add     "allure-mocha": "^2.0.0-beta.6", in devdeps and run `yarn` then `test` script from package.json and try allure.createStep and catch error :(

**Comment by ostul** [comment]
I have the same problem

**Comment by dzotovwork** [comment]
Total, would like a working example with mocha-allure, ts-test-decorators or @ testdeck / mocha, it would be ideal with multi-threading) I think everyone will be very grateful)

**Comment by sskorol** [comment]
I'll take a look at it. But probably only by the end of this week.

**Comment by sskorol** [comment]
Should work as soon as #138 is merged and a new version is released. I've added epic tests and tested it locally with decorators as well. So stay tuned.

**Comment by tims-j** [comment]
I am also having this issue ( using version 2.0.0-beta.7 ).

**Comment by fescobar** [comment]
@sskorol @just-boris After installing `2.0.0-beta.7` and update some dependencies, the same error persists. I'm using typescript:

```
     TypeError: Cannot read property 'epic' of undefined
      at Context.it (dist/test1.js:4:12)
```
Check the example please.
[example-mocha.zip](https://github.com/allure-framework/allure-js/files/4680532/example-mocha.zip)

```
> quality-automation@1.0.0 mocha-test /Users/frank.escobar/Downloads/example-mocha
> npm run clean && npm run build && npm run mocha --config .mocharc.js dist/test1.js --reporter node_modules/allure-mocha


> quality-automation@1.0.0 clean /Users/frank.escobar/Downloads/example-mocha
> rm -rf ./allure-results/* ./dist/


> quality-automation@1.0.0 build /Users/frank.escobar/Downloads/example-mocha
> tsc


> quality-automation@1.0.0 mocha /Users/frank.escobar/Downloads/example-mocha
> mocha ".mocharc.js" "dist/test1.js" "node_modules/allure-mocha"



  1) is a test

  0 passing (5ms)
  1 failing

  1) is a test:
     TypeError: Cannot read property 'epic' of undefined
      at Context.it (dist/test1.js:4:12)



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quality-automation@1.0.0 mocha: `mocha ".mocharc.js" "dist/test1.js" "node_modules/allure-mocha"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quality-automation@1.0.0 mocha script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frank.escobar/.npm/_logs/2020-05-26T07_26_35_607Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! quality-automation@1.0.0 mocha-test: `npm run clean && npm run build && npm run mocha --config .mocharc.js dist/test1.js --reporter node_modules/allure-mocha`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the quality-automation@1.0.0 mocha-test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/frank.escobar/.npm/_logs/2020-05-26T07_26_35_641Z-debug.log
```

**Comment by sskorol** [comment]
@fescobar @tims-j is there any reason you can't use es6 import syntax?

The problem here is in a combination of Mocha specifics and plain-old JS `require` syntax.

First of all, we have to use default export for reporter itself to be able to include it via -R option. On the other hand, we can't make `allure` default as well, as `allure-runtime` makes 3 exports.

So what's wrong with `require` syntax then? Nothing special, except the fact that when you destructure `allure` via `require`, it detaches it from the reporter context.

The problem here is that this variable's value is populated in runtime, when AllureReport is initialized by Mocha. So when you detached it via `require` you couldn't track any changes anymore. That's why you got `epic of undefined` error. However, it would fail the same way for any other property as well.

You may wonder how to fix that? Either use es6 import syntax, which correctly handles destructuring without detaching object from its parent context, or operate with a root runtime object. But in the latter case you can access `allure` only within test.

```js
import { allure } from "allure-mocha/runtime";

it('is a test', () => {
    allure.epic('Some info');
});

// or
const runtime = require('allure-mocha/runtime')

it('is a test', () => {
    runtime.allure.epic('Some info');
});
```

**Comment by just-boris** [comment]
@fescobar you are missing the reporter in your configuration. You need to enable it, for example: `mocha --reporter=allure-mocha`

Working example can be found here: https://github.com/allure-examples/allure-mocha-example

It is for allure1, but this particular part did not change.

**Comment by fescobar** [comment]
@just-boris that part is already there in the script from my example in the ending part `--reporter node_modules/allure-mocha`
```
"mocha-test": "npm run clean && npm run build && npm run mocha --config .mocharc.js dist/test1.js --reporter node_modules/allure-mocha"
```

That example https://github.com/allure-examples/allure-mocha-example is not using this component `"allure-mocha": "2.0.0-beta.7"`. It's using another `"mocha-allure-reporter": "^1.2.0"`. Also it's not a typescript example.
```
  "devDependencies": {
    "allure-commandline": "^2.0.0",
    "chai": "^4.0.2",
    "mocha": "^3.3.0",
    "mocha-allure-reporter": "^1.2.0",
    "mocha-multi": "^0.11.0",
    "npm-run-all": "^4.0.2",
    "selenium-standalone": "^6.2.0",
    "webdriverio": "^4.8.0"
  }
```

**Comment by fescobar** [comment]
> ```js
> import { allure } from "allure-mocha/runtime";
> 
> it('is a test', () => {
>     allure.epic('Some info');
> });
> ```

@sskorol I can use `"target": "ES6"`, the same problem persists. I tried both implementations suggested. Can you fix the problem in my small example?

**Comment by tims-j** [comment]
@sskorol i am using ES6 syntax for importing the allure runtime. 

I have tried both default exports to delve into the root export and access the runtime that way.

`import runtime from “allure-mocha/runtime”`

as well as using the named allure export.

`import { allure } from “allure-mocha/runtime”`

Both instances return undefined for me.

I have also also added the allure-mocha reporter to the mocha.opts file. 

I can provide code specifics if you would like.

**Comment by sskorol** [comment]
@fescobar in your case the issue is trivial: reporting option you're passing to Mocha is ignored. You need to specify it next to the binary (not via npm run reference). Or just move the entire config to .mocharc.js. There's no need to mix cli options with `.mocharc`.
```json
"mocha": "./node_modules/.bin/mocha --config .mocharc.js dist/test1.js --reporter node_modules/allure-mocha",
"mocha-test": "npm run clean && npm run build && npm run mocha"
```
Btw, as far as I remember, `.mocharc` should be detected automatically, so you don't need to provide it explicitly.
```js
module.exports = {
    timeout: 60000,
    spec: 'dist/**/*.js',
    reporter: 'allure-mocha'
};
```
```json
"test": "npm run clean && npm run build && mocha"
```
P.S. I couldn't compile it with TS version, you've specified in package.json. So please try to upgrade it as well.

@tims-j yes, please show me some example project. Most likely it's configuration issue.

**Comment by sskorol** [comment]
So based on the attached project, here are fixes:

*package.json*
```json
  "scripts": {
    "clean": "rm -rf ./allure-results/* ./dist/",
    "test": "npm run clean && tsc && mocha"
  },
  "dependencies": {
    "mocha": "6.2.0",
    "allure-mocha": "2.0.0-beta.7",
    "@types/mocha": "5.2.7",
    "ts-node": "8.1.0",
    "typescript": "3.9.3",
    "@types/node": "11.13.4"
  }
```

*.mocharc.js*
```js
module.exports = {
    timeout: 60000,
    spec: 'dist/**/*.js',
    reporter: 'allure-mocha'
};
```

*test1.ts*
```ts
import { allure } from 'allure-mocha/runtime';

it('is a test', () => {
  allure.epic('Some info');
})
```
P.S. I'd also use Mocha 7.2.0. But it's you own choice of course.

**Comment by sskorol** [comment]
@fescobar btw, if you want to use TS with decorators, I've already updated [ts-test-decorators](https://www.npmjs.com/package/ts-test-decorators), which refers to the latest Allure. There's also a reference to an example project.

**Comment by fescobar** [comment]
Thank you so much @sskorol . Now it's working, just I added the reporter in the mocha file configuration.
```
module.exports = {
  timeout: 60000,
  spec: 'dist/**/*.js',
  reporter: 'allure-mocha'
};
```
Here is the example working in case someone need it.

[example-mocha(fixed).zip](https://github.com/allure-framework/allure-js/files/4681663/example-mocha.fixed.zip)

**Comment by sskorol** [comment]
@ryparker @tims-j @ostul @dzotovwork please check if it works for you as well, so that we could close this issue.

**Comment by tims-j** [comment]
@sskorol after much trial and error I ended up upgrading to the latest mocha version and converting my mocha.opts file over to the new configuration format.

Updating the configs to use similar settings and packages as @fescobar mentioned above as well must have shook something loose as i now have it working.

Thanks everyone!

**Comment by fescobar** [comment]
@sskorol @just-boris are you planning to release a no beta version?

**Comment by sskorol** [comment]
@fescobar I'm just a common contributor. So I have no idea about Allure milestones. :)

**Comment by fescobar** [comment]
Here a complete example creating steps, attachments, etc
https://github.com/fescobar/allure-docker-service/tree/master/allure-docker-nodejs-typescript-mocha-example
Thank you to everybody involved.

**Comment by egorvas** [comment]
Hi, seems that same issue still reproducing... 
Code of the my test is:

`const { allure } = require('allure-mocha/runtime');

describe('Test', function() {
    it('should work', async function() {
        console.log(1)
        allure.epic('Some info');
        console.log(2)
    });
});`

How I am running the test:

```bash
npx mocha tests -R allure-mocha
```

Version of the nodejs is 14, but I tried 12 and 10 also
Version of the allure-mocha is 2.0.0-beta.9
This is full project for reproducing(but it contains only npm modules and test provided below)
[allure-issue-example.zip](https://github.com/allure-framework/allure-js/files/6404429/allure-issue-example.zip)

**Comment by fescobar** [comment]
@egorvas I've updated the link for the solution
https://github.com/fescobar/allure-docker-service-examples/tree/master/allure-docker-nodejs-typescript-mocha-example

**Comment by egorvas** [comment]
After show analysis I can say that this module works only with es-modules, importing by require('allure-mocha/runtime').allure not working for me.

**Comment by just-boris** [comment]
@egorvas and this is totally correct observation!

Runtime export is instantiated asynchronously and not available when you require the module. ES modules allow late export re-assignment, but require does not.

You can get it around with the following code:

```
const runtime = require('allure-mocha/runtime');

it('example', () => {
   runtime.allure.epic('demo')
})
```

**Comment by egorvas** [comment]
Hi @just-boris thx for your explanation, that works fine.

**Comment by jee-lee** [comment]
Hello!
I am seeing this occurring when I try to run mocha in my es6 js project. The allure object is undefined while running mocha.
I am using node 16.13.1
mocha 9.2.0 and allure-mocha 2.0.0-beta.19

I've attached my example project.
[example-js-allure.zip](https://github.com/allure-framework/allure-js/files/9478923/example-js-allure.zip)
