### ISSUE TITLE
every console.log wrap individually 

### ISSUE THREAD

**Issue by eyalf007** [allure-framework/allure-js#500]
**Describe the bug**
every console.log wrapped individually 

**Expected behavior**
![image](https://user-images.githubusercontent.com/110524000/191740252-1b7ff222-cd14-459b-ba28-034a9e54f107.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/110524000/191740453-a3d9a255-56d8-48db-bd85-c72627b005a1.png)

**Comment by epszaw** [comment]
Hello! Which runner and integration do you use?

**Comment by eyalf007** [comment]
Hello,
Playright

**Comment by vovsemenv** [comment]
@eyalf007 hello, thanks for the feedback, will fix this as soon as possible.

**Comment by vovsemenv** [comment]
For the record right now this code will create three different stdout attachments

```ts
import { test } from "@playwright/test";

test("Demo test", async () => {
  console.log("Test log");
  console.log("Test log 2");
  await test.step("nested", async () => {
    console.log("Test nested log");
  });
});
```

**Comment by sridharreddysuram123** [comment]
Hi @vovsemenv , any update on this?

**Comment by g7skim** [comment]
@vovsemenv  Hi. Any news on this issue?

**Comment by vovsemenv** [comment]
@g7skim PR ready will be merged soon

**Comment by vovsemenv** [comment]
thank you for activity))

**Comment by g7skim** [comment]
Hi @vovsemenv 
I've just updated "allure-playwright" to the "2.0.0-beta.24" version and it still generates separate .txt files for every concole.log event in the ./allure directory.

**Comment by baev** [comment]
The fix is not yet released

**Comment by g7skim** [comment]
> 
Oh, got it, thank you.
In which version is it planned to be released?
