### ISSUE TITLE
Integration with test framework

### ISSUE THREAD

**Issue by krishnastest** [allure-framework/allure-js#501]
This is not an issue but more of a query.
I'm using jest and allure for testing and reports in JavaScript based framework, but when running the allure-generate command in pipeline(bitbucket) I'm getting an error for JAVA_HOME.
![image](https://user-images.githubusercontent.com/98147661/191991212-9459c4db-d3b4-40b0-99f2-0727848567cb.png)

Will this repo be helpful in solving this problem?
If yes, how do I integrate it with my current framework?

**Comment by arukiidou** [comment]
- use atlassian/default-image:3 ? it would not work
  - it also requires java（JRE is OK）
  - use timbru31/java-node

**Comment by krishnastest** [comment]
timbru was working fine, the environment itself was having issues so I missed that. 
Thanks for your reply.
