### ISSUE TITLE
When WDIO Fails on Any Hook (before, after) but Passes on Retry, Allure Still Shows as Failed

### ISSUE THREAD

**Issue by awhisler** [allure-framework/allure-js#502]
**Describe the bug**
When WDIO/Mocha Fails on Any Hook (before, after) but Passes on Retry, Allure Still Shows as Failed. There is a `specFileRetries` config in WDIO that can be set and if you have that set and the test fails in the before/after on one run but passes on the second run, the Allure report will still show at failed

**To Reproduce**
1. Use WDIO/Mocha framework
2. Add `specFileRetries` config in wdio.conf and set to > 1
3. Add a before or after hook in addition to an `it` (mocha)
4. Have the test fail on one of the hooks the first time but pass the second time (probably need to do something with the app itself vs the framework to get this to happen)

**Expected behavior**
* Allure report shows does not show as failed as the end result if the retry actually passed
![image](https://user-images.githubusercontent.com/2396250/193060757-733e6f6c-8fb4-4f94-bb2e-bb0dbe55a585.png)

**Desktop (please complete the following information):**
 - OS: Irrelevant - happens on all OSs
 - Browser: Chrome (any version)

**Additional context**
In Jenkins, it shows as 'unstable' but passing
![image](https://user-images.githubusercontent.com/2396250/193061202-8d5649f5-c469-45c0-a0be-3c86fbf51f5a.png)
The report (image above) shows some failed even though Jenkins shows as passing (as it should)

**Comment by dwagner003** [comment]
I also ran into this issue using Allure. Would be great to see a fix come through!

**Comment by awhisler** [comment]
@epszaw Any update on this? My team is anxiously waiting for this fix. We are constantly show failed on the Allure Report even if it passed on rerun and our audit log looks messy

**Comment by awhisler** [comment]
@epszaw Hoping for a status update here. We are anxiously waiting for this fix

**Comment by 2erix** [comment]
This would be a good fix, one my team would be happy to have as well, but is it allure-js issue or @wdio/allure-reporter implementation issue?

**Comment by timbochamp** [comment]
running into this as well with the wdio allure reporter

**Comment by jma65** [comment]
Also running into this, this would be a great fix!

**Comment by epszaw** [comment]
Could you check once more? Tested the latest reporter version with allure report and allure test ops, but can't reproduce the problem.

Could you create an example repository, where I can reproduce the problem?

<img width="1334" alt="image" src="https://github.com/allure-framework/allure-js/assets/13414205/8594094f-33c4-4cf0-b331-215455ddc87d">

<img width="1335" alt="image" src="https://github.com/allure-framework/allure-js/assets/13414205/b063ae47-e3da-44c1-8abe-74dc44f6d7b3">

**Comment by epszaw** [comment]
@awhisler if the problem is actual for you, feel free to reopen the issue
