### ISSUE TITLE
Screenshots not displayed in report

### ISSUE THREAD

**Issue by anagnxt** [allure-framework/allure-js#503]
I'm using Allure in combination with Cucumber+Playwright and there are no screenshots shown

![Screenshot 2022-10-05 111024](https://user-images.githubusercontent.com/78973138/194027875-d2573e32-5ae0-4dc2-a763-02f01879e840.png)

In common-hooks.ts file there is @After function, where taking screenshot after each failed scenario
![Screenshot 2022-10-05 112744](https://user-images.githubusercontent.com/78973138/194028878-a1438316-766a-46a3-93d9-3a2341181387.png)

**Comment by epszaw** [comment]
Could you please check the screenshot image inside `allure-results` folder? Does it render?

**Comment by epszaw** [comment]
Was fixed in the last release with a high probability. Feel free to reopen the issue, if the problem still exists for you.
