### ISSUE TITLE
Steps, video and screenshots are not displayed when Playwright test timeouts after multiple attempt to perform action

### ISSUE THREAD

**Issue by VinayKumarBM** [allure-framework/allure-js#504]
Steps video and screenshots are not displayed when Playwright test fails due timeout after multiple attempt to perform action on the element.

Please find the attached screenshot of the issue.
![Timeout](https://user-images.githubusercontent.com/41902979/195059681-1d3d6aa7-f0f1-4ced-a5fc-4d15ec019dc8.JPG)
![Timeout end](https://user-images.githubusercontent.com/41902979/195059689-3e39a632-faa2-4605-a05f-ad9ebc9f5237.JPG)

Please suggest a way to resolve this issue.

**Comment by VinayKumarBM** [comment]
Can you please provide some input on this issue.

**Comment by vovsemenv** [comment]
Hello @VinayKumarBM can you please provide reproduction of your case?
I created demo where tests failed by timeout and my video and sreenshot attachments are fine https://github.com/vovsemenv/pw-504-bug/blob/master/tests/all-completed.test.ts

**Comment by VinayKumarBM** [comment]
@vovsemenv  Thanks for responding to my query. 

In my cases it is trying click on some element but it is blocked by some pop up/ alert. I have action wait time on 2 min, so it keeps retrying to click element with message as shown in my screenshots and eventually it times out.

I cases, where we don't have selector on dom, it times out and fails and I can see that attachments correctly.  Only in above scenario I only see error message without any steps or attachments.

Please let me know, if you need any additional details.

**Comment by baev** [comment]
I can't reproduce the error using `allure-playwright@3.0.0-beta.4`
