### ISSUE TITLE
How to get Total, Passed, Failed, Skipped test cases count in custom reporter in playwright(typescript)

### ISSUE THREAD

**Issue by anjireddy5817** [allure-framework/allure-js#505]
Below is the my code:
import { FullConfig, FullResult, Reporter, Suite, TestCase, TestError, TestResult } from "@playwright/test/reporter";
class MyReporter implements Reporter{
   onBegin(config: FullConfig, suite: Suite): void {
        console.log(`: Starting the run with : ${suite.allTests().length} : tests`)
    }
    onTestBegin(test: TestCase): void {
        console.log(`: Test started : ${test.title}`)
    }
    onTestEnd(test: TestCase, result: TestResult): void {
        console.log(`: Test ended: ${test.title} : ${result.status}`)
    }
    onError(error: TestError): void {
        console.log(error.message);
    }
    onEnd(result: FullResult): void{
        console.log(`: Finished the run :  ${result.status}`)
    }
}
export default MyReporter;

**Comment by vovsemenv** [comment]
This question not related to `allure-js` at all but you can use our AllureTestops solution where you can easily filter and count you tests by status field.

More about testOps: https://qameta.io/
