### ISSUE TITLE
A single JSON file is created in allure-results folder on executing cucumber tests in parallel mode. 

### ISSUE THREAD

**Issue by SDETQATestAutomation** [allure-framework/allure-js#506]
**Describe the bug**
A single JSON file is created in allure-results folder on executing cucumber tests in parallel mode.  Whereas the same is not true when the test case is executed sequentially.

**To Reproduce**
1. Execute cucumber test in parallel mode

**Expected behavior**
Multiple JSON files based on a number of test cases should be created on executing the test in parallel mode.

**Screenshots**
attached recording

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version  106.0.5249.119
 

**Smartphone (please complete the following information):**
NA

**Additional context**
"@cucumber/cucumber": "^8.5.0",
"allure-commandline": "^2.18.1",
"allure-cucumberjs": "^2.0.0-beta.18",

**Comment by epszaw** [comment]
Should be fixed in the latest release. Reopen the issue if not.
