### ISSUE TITLE
allure-playwright: Suppress passing suite parameter from playwright itself to Allure TestOps

### ISSUE THREAD

**Issue by dasshit** [allure-framework/allure-js#512]
**Is your feature request related to a problem? Please describe.**
Question: how can i suppress setting script module name as Suite Custom field in Allure TestOps?

Test case example:
```typescript
test.describe.parallel('Чаты: информация о чате', () => {
    test.beforeEach(async({ page, baseURL }, testInfo) => {
        allure.label({ name: LabelName.LANGUAGE, value: 'typescript' });
        allure.suite('Чат');
        allure.feature('Информация в сайдбаре чата');
        console.log(`Running test: ${testInfo.titlePath.join(' -> ')}`);
        await e2eAuth(baseURL, page);
    });

    test('Включение автоподписки на треды', async ({ page }) => {})
});
```

Allure TestOps:
<img width="159" alt="image" src="https://user-images.githubusercontent.com/56739036/201411427-2da244be-7b90-4f21-866d-0996fb19dc55.png">

**Describe the solution you'd like**
If the suite has already been assigned to the test through the code, forward its value as a suite to the TestOps, one and only.
Otherwise - pass module name as suite field value

**Comment by dasshit** [comment]
In my default value is superfluous. Target is to replace with human-readable value, like it's working for allure-pytest.

Option or default behavior - it does not matter, the main thing is that there is such a setting. 😀

**Comment by baev** [comment]
you can use any other label instead of the suite and create a custom tree in Allure TestOps

**Comment by dasshit** [comment]
We separated autotests to several projects in Allure TestOps by platform and are trying to use fields in all projects, guided by common rules for all projects.

So using different field than suite to build new tree is not an option:(

**Comment by baev** [comment]
if you have separate project for playwright tests, you may simply change the mapping to Suite field from `suite` label to any other custom label

**Comment by epszaw** [comment]
@dasshit could you provide any information? Did the proposed solution help you?
