### ISSUE TITLE
[Allure-playwright] Set the path of my test file as the label of the results in report from the config file?

### ISSUE THREAD

**Issue by DvDream** [allure-framework/allure-js#520]
Hi, I remember that in the previous versions of allure Playwright, the labels of the tests results in the report where equal to the path of my test file in my filesystem by default. This was useful to me but Now by default the name of the title of the test is appearing. I've already tried to set to false suitTitle in the config file but maybe isn't the right solution and I would like to avoid on directly setting the label from every single test tha I've written. How can this be done? thank you!

**Comment by vovsemenv** [comment]
In the next version of playwright integration `fullName` field of test will be `path/to/resultfile#testname` is it satisfy you needs or you need to do something more specific?

**Comment by epszaw** [comment]
@DvDream could you provide any information about the proposed solution here?

**Comment by baev** [comment]
Since 3.0.0, you may use the Packages report tab to see the tests grouped by test file paths.
