### ISSUE TITLE
Allure-cucumber7-jvm depenedency conflicts with Cucumber version 7

### ISSUE THREAD

**Issue by hemanshurana** [allure-framework/allure-js#533]
I was using following dependencies to create the project and allure report 

  <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>6.10.4</version>
        </dependency>
  <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>6.10.4</version>
        </dependency>
  <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>6.10.4</version>
        </dependency>
  <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-cucumber6-jvm</artifactId>
            <version>2.14.0</version>
  </dependency>

I am trying to update cucumber 7.9.0 but it's start throwing error message following 

Could not resolve dependencies for project com.test.automation.core:test_core_automation_framework:jar:2.5.0-SNAPSHOT: Failed to collect dependencies for com.test.automation.core:test_core_automation_framework:jar:2.5.0-SNAPSHOT: Could not resolve version conflict among [io.cucumber:cucumber-core:jar:7.9.0 -> io.cucumber:messages:jar:19.1.4, io.cucumber:cucumber-core:jar:7.9.0 -> io.cucumber:html-formatter:jar:20.1.0 -> io.cucumber:messages:jar:[19.0.0,20.0.0), io.qameta.allure:allure-cucumber6-jvm:jar:2.14.0 -> io.cucumber:gherkin:jar:18.0.0 -> io.cucumber:messages:jar:[15.0.0,16.0.0)] -> [Help 1]

I removed allure dependency and this conflict resolved but as i am using allure dependency to create the allure report i will need this dependency.  i also check with allure-cucumber7-jvm latest version but still i am getting this issue.

**Comment by vovsemenv** [comment]
Hello @hemanshurana this repo only for javascript issues. I guess you using java so consider creating issue in this repo https://github.com/allure-framework/allure-java

**Comment by hemanshurana** [comment]
Thank you
