### ISSUE TITLE
Using a subfolder as outputfolder  in Playwright config will not show all substeps in report

### ISSUE THREAD

**Issue by shizzleliz** [allure-framework/allure-js#539]
**Describe the bug**
We wanted to set the output of the test results and report to a test-results folder. After running the tests and creating the report, the report does not show all the substeps, just the steps we added to the Playwright tests. When we set the output to the root, all the steps are shown in the report

**To Reproduce**
1. Set up Playwright config: Part of the Playwright config:
```
const testDirBase = path.join(__dirname, 'tests');
const outputDirBase = path.join('..', 'test-results', 'allure-results');

reporter: [['line'], ['allure-playwright', {outputFolder: outputDirBase}]],

testDir: testDirBase,
outputDir: outputDirBase,
projects: [
    {
      name: 'E2E',
      testDir: path.join(testDirBase, 'e2e'),
      outputDir: path.join(outputDirBase, 'e2e'),
    },
    {
      name: 'Integration',
      testDir: path.join(testDirBase, 'integration'),
      outputDir: path.join(outputDirBase, 'integration'),
    },
    {
      name: 'Visuals',
      testDir: path.join(testDirBase, 'visuals'),
      outputDir: path.join(outputDirBase, 'visuals'),
    },
 ],
```
2. run the tests
3. create the report using: "allure generate ./test-results/allure-results --clean -o test-results/allure-report",

**Expected behavior**
All the steps are visible, see screenshots for actual en expected reports

**Screenshots**
report when outputfolder is set to subfolder
![actual-report](https://user-images.githubusercontent.com/52817183/205274361-d3aac9db-31fe-46f8-b4a2-05b1f70c4003.png)
report when outputfolder is set to root
![expected-report](https://user-images.githubusercontent.com/52817183/205274363-060220a9-91d1-4b17-a745-c4d97934e7ab.png)

**Additional context**
The expected scenario works when the config is modified to:
```
const outputDirBase = path.join('..', 'allure-results');
reporter: [['line'], ['allure-playwright']],
```

**Comment by baev** [comment]
should be fixed in 3.0.0-beta
