### ISSUE TITLE
Unable to generate Allure Report

### ISSUE THREAD

**Issue by keshavjha06** [allure-framework/allure-js#541]
Playwright Version: [1.28.1]
Operating System: [Mac]
Node.js version: [19.2.0]
Browser: [Chromium, Firefox, WebKit]
"allure-playwright": "^2.0.0-beta.20"
I have installed allure and also ran the test cases with npx playwright test --grep @web --reporter=line,allure-playwright

allure-results folder got generated

But unable to generate the report using the below command

allure generate ./allure-results --clean

getting the error - zsh: command not found: allure

**Comment by vovsemenv** [comment]
Hello, to generate this report you need to install https://github.com/allure-framework/allure2 generator or you can use [allure testOps](https://qameta.io/) solution
