### ISSUE TITLE
Ability to set Environment Section values

### ISSUE THREAD

**Issue by vovsemenv** [allure-framework/allure-js#552]
> Is it possible to take advantage of the "Environment" section of the allure reports? Is there any feature on this tool that allow to set values in the "Environment" section.
> 
> https://docs.qameta.io/allure/#_environment ![image](https://user-images.githubusercontent.com/77497631/173041415-5fb98303-3cbf-4a5c-a57f-a86aee8801d4.png)

from https://github.com/ervirendersingh/newman-reporter-allure/issues/25

**Comment by bushra0722** [comment]
I would like to set environment URL in the Allure Report. I am able to set other parameters in the environment section but URL is not displayed.

**Comment by baev** [comment]
fixed in 3.0.0
