### ISSUE TITLE
[Feature] Add the ability to set up labels from environment variables

### ISSUE THREAD

**Issue by vovsemenv** [allure-framework/allure-js#559]
Proposed solution:
env variable `ALLURE_LABEL_{labelname}={labelValue}`  will add this label to all tests in this run

**Comment by Mohd-Sarik-tfs** [comment]
can you please write an example of this

**Comment by vovsemenv** [comment]
hello @Mohd-Sarik-tfs since allure-js-commons@2.0.0-beta.22 you can set enviorment variables like this
`ALLURE_LABEL_EPIC="epicName" npm test` and all of your tests will have this epic value

**Comment by vovsemenv** [comment]
closed via https://github.com/allure-framework/allure-js/pull/561
