### ISSUE TITLE
Unexpected endStep() check

### ISSUE THREAD

**Issue by 2erix** [allure-framework/allure-js#565]
**Is your feature request related to a problem? Please describe.**

`allure-js-commons: Unexpected endStep(). There are no any steps running` is appearing in my logging however I have no ability to check if there is a Step active or not. 

**Describe the solution you'd like**

I am using AllureReporter from @wdio/allure-reporter. 

Before I close/end steps I would like a method to check if a step is active. This would allow me to not close steps unnecessarily.  

In allure-commons there is `Allure.prototype.getCurrentSuite`. If it was available to me it would allow me to  create a check I require like the following:
`const suite = AllureReporter.getCurrentSuite()`

`if (suite && suite.currentStep instanceof Step) {
// end step here
}`

**Describe alternatives you've considered**

Attempted to capture the endpoint of steps in tests throughout solution however the dynamic nature of our method usage means we have use cases where the step is started in one method and closed in another and it is impossible to track every scenario. 

Attempted try catch block for the end step call however the message is still reported. 

Attempted to access the suite/getCurrentSuite method to create own check and the method is not accessible. 

**Additional context**

This is to provide an Annotation for Steps similar to the Java capability for Typescript/JavaScript users however this, somewhat preventable, issue stops me for sharing the solution with the community. 

Once/if this solution is available I can propose an implementation for the @wdio/allure-reporter solution.

**Comment by epszaw** [comment]
@2erix could you please confirm the issue status?

**Comment by epszaw** [comment]
@2erix if the problem is still actual, feel free to reopen the issue
