### ISSUE TITLE
one expression fails in one step but the cucumber scenario is marked pass

### ISSUE THREAD

**Issue by bodycombathuang** [allure-framework/allure-js#574]
**Describe the bug**

**To Reproduce**

```ts
Given('given', async function (this: ICustomWorld) {
   await this.step("step1", async () => {
     expression1
  });
  await this.step("open location", async () => {
    expression 2
  });
   
 expression 3
});
```

expression 2 throws exception, and in allure report, I can see the second step fails, but the scenario is marked PASS, it is so strange
if I change the code to 
```
Given('given', async function (this: ICustomWorld) {

     expression1


    expression 2

   
 expression 3
});
```

the scenario is marked FAIL

I am using typescript+@cucumber/cucumber and allure-cucumberjs

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by baev** [comment]
the issue is fixed in allure-cucumberjs@3.0.0-beta
