### ISSUE TITLE
Change test layers programmatically

### ISSUE THREAD

**Issue by kodeshPapaya** [allure-framework/allure-js#575]
We have a few types of tests and need to order the tests while they executed

maybe you can add to allure-playwright some function that can update the layer of the test?

for example:
  allure.layer('API')
  allure.layer('UI')

**Comment by vovsemenv** [comment]
Hello @kodeshPapaya . Good catch, this thing will be released soon as part of https://github.com/allure-framework/allure-js/pull/576
