### ISSUE TITLE
A stripped-down User role is needed, allowing you to restart and run tests

### ISSUE THREAD

**Issue by snataCRPO** [allure-framework/allure-js#587]
A reduced User role is needed only for developers so that they:
1. Could run tests from the total number of test cases;
2. Could restart the tests from the launchers;
3. Could not make any changes to test cases, test plans, etc.

**Comment by vovsemenv** [comment]
Sorry i don't understand the problem. If you need support with Allure TestOps please contact us via https://help.qameta.io/ or hello@qameta.io or open more detaild issue
