### ISSUE TITLE
newman-reporter-allure generates step stop time only if step fails

### ISSUE THREAD

**Issue by Wanyann** [allure-framework/allure-js#589]
**Describe the bug**
Missing step stop time in passed tests in generated result.json files

**To Reproduce**
1. Run postman collection using newman with **-r allure** reporter (some tests should pass, some should fail)
2. Open generated result.json files once tests finished 
3. In passed steps there is no stop time value, only start time value

**Expected behavior**
Stop time of all tests, passed and failed, recorded to result.json

**Screenshots**
Generated result.json looks like this:
![image](https://user-images.githubusercontent.com/57600034/215481375-abb54ff6-1eac-4f9a-9f68-093294805d34.png)

This bug results in "Unknown" step time in report:
![image](https://user-images.githubusercontent.com/57600034/215480321-422ae471-636f-47e0-8c10-fbbd0f6bd38a.png)

And because of missing step stop time testit-allure-adaptor not working properly:
![image](https://user-images.githubusercontent.com/57600034/215480750-c03cd994-ceba-4ae9-be1b-59e3a7e80cc5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - newman-reporter-allure: 2.0.0-beta.25
 - Newman: 5.3.2

**Comment by vovsemenv** [comment]
Hello @Wanyann thank you for good bug explanation. I can fix this this in next release. Also it will be perfect if you create PR yourself ❤️

**Comment by vovsemenv** [comment]
PR ready. feel free to review

**Comment by Wanyann** [comment]
Thank you!
