### ISSUE TITLE
please create correct name for the issue

### ISSUE THREAD

**Issue by skurilenko** [allure-framework/allure-js#592]
Good afternoon!
It is necessary to add the ability to see only red steps (bugs) when viewing a test report.
Problem: 4. When you click on the link to the passed launch, all steps/substeps and all documents added to the report are open, which significantly loads the report itself and prevents the selection of bugs for testing.
It would be more convenient if, when viewing the steps of the test case, the successfully passed steps remained collapsed, and the failed steps (substeps with bugs) were expanded so that the focus was not lost when viewing the report.

![anim2](https://user-images.githubusercontent.com/123932241/215488548-4d0f44b2-99ac-45dd-ada4-2d259d916283.gif)

**Comment by cheshi-mantu** [comment]
Hi @skurilenko 
this repository is for allure framework's integrations with JS testing frameworks.
if you are paid or trial Allure TestOps user, please use Allure TestOps help desk to create the suggestions for the improvements.
Please also take info account, there are very strict rules for the creation of issues in allure framework repos: 
- always English language with no exceptions, 
- always the suggested format of an issue

**Comment by cheshi-mantu** [comment]
@skurilenko please file this request via https://help.qameta.io
