### ISSUE TITLE
newman-reporter-allure will not run

### ISSUE THREAD

**Issue by chyde80** [allure-framework/allure-js#596]
**Describe the bug**
When attempting to run with the newman reporter as 'allure' it throws an exception immediately

**To Reproduce**
1. Install newman-reporter-allure (`npm install -g newman-reporter-allure`)
2. Run newman against known good collection (`newman` run <collectionfile> -e <envfile> -r allure`)

**Expected behavior**
Collection will run and report files output to allure-results if output dir not specified

**Screenshots**
![image](https://user-images.githubusercontent.com/94012770/215819884-bdac3f99-010e-40c8-9e26-f7f5cf9eee6d.png)

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**

**Comment by vovsemenv** [comment]
Thank you for participation ❤️ PR ready https://github.com/allure-framework/allure-js/pull/598

**Comment by chyde80** [comment]
thanks, when will I be able to update the package?
