### ISSUE TITLE
Is mocha-allure up to date?

### ISSUE THREAD

**Issue by egorvas** [allure-framework/allure-js#601]
**Describe the bug**
Hi, trying to run mocha tests with allure-mocha and mocha latest versions but seems it doesn't work.
Im starting it with "npm test" from this repo https://github.com/egorvas/allure-mocha-error
But allure is undefined.

**To Reproduce**
1. git clone https://github.com/egorvas/allure-mocha-error
2. cd allure-mocha-error
3. npm test

Please explain what I doing wrong.

**Comment by vovsemenv** [comment]
Hello @egorvas . Thank you for the participation.
foid out that the Readme examples actually didn't work correctly. (Will be fixed in the next release)

Right now you need to change style of your imports to this because exports for mocha are little bit broken right now

```js
const allureRuntime = require("allure-mocha/runtime");
it("is a test", () => {
  allureRuntime.allure.tag("tag1");
  allureRuntime.allure.epic("epicName");
});
```

**Comment by baev** [comment]
readme is updated
