### ISSUE TITLE
attachment names while using cucumber-js with allure

### ISSUE THREAD

**Issue by bhvngt** [allure-framework/allure-js#604]
**Is your feature request related to a problem? Please describe.**
Currently, I am using cucumber-js as test runner with playwright for browser automation and allure for reporting.

I am attaching `playwright` traces while running `cucumber-js` scenarios. I would like to label my attachment. However, this does not appear to be possible currently as it seems to be hard-coded with ["attachment"](https://github.com/allure-framework/allure-js/blob/4f83dd6d3b914398f95b90a7b3a713245df62b3e/packages/allure-cucumberjs/src/CucumberAllureWorld.ts#L154). 

Is it possible to pass attachment names? Any alternate solution would also be welcomed.

Here's my code in the `After` hook method of `cucumber-js`.

```typescript
After(async function(this: CustomWorld, {result, pickle}:ITestCaseHookParameter) {
    fse.ensureDirSync(testReportFolder + "/trace")
    const hasTraceTag = pickle.tags.find(({name}) => name === "@trace");
    if (result?.status === Status.FAILED || hasTraceTag) {
        const tempFilePath = path.join(os.tmpdir(), "trace.zip")
        await instance.page.context().tracing.stop({path: tempFilePath});
        await this.attach(await fs.readFile(tempFilePath),"application/zip")
    } else {
        await instance.page.context().tracing.stop();
    }
    await instance.page.close()
})
```

**Describe the solution you'd like**
Ability to give name to attachment.

**Comment by epszaw** [comment]
The reporter [use `attach` method from cucumber World class](https://github.com/cucumber/cucumber-js/blob/main/src/runtime/attachment_manager/index.ts#L46). It doesn't allow to set any custom name to attachments.
