### ISSUE TITLE
Property 'toSatisfyAll' does not exist on type 'ArrayLikeMatchers<number>'

### ISSUE THREAD

**Issue by vzhik54** [allure-framework/allure-js#608]
**Describe the bug**
Hi, I'm currently getting the following error when using allure-js and trying to build project or run tests.
I think this error occurs due to I change testrunner property from default to jasmine2 in jest.config.js.
[Here](https://github.com/JamieMason/Jasmine-Matchers ) a list of jasmine matchers and the toSatisfyAll matcher is absent.

Our company can't change this matcher to other in current time.

Please clarify if there is any solution to this problem?

**To Reproduce**
1. Use 'expect(1).toSatisfyAll()' to any test
2. Install allure-js and configure it according to instruction
3. Run tests

**Expected behavior**
There are no errors upon build project or run test.

**Environment:**
 - "@types/jasmine": "^4.3.1",
 - "@types/jest": "^29.2.5",
 - "allure-jasmine": "^2.0.0-beta.26",
 - "allure-js-commons": "^2.0.0-beta.26",
 - "jest": "^29.3.1",
 - "jest-extended": "^3.2.2",
 - "jest-jasmine2": "^29.4.2",

**Additional context**
Error:
`ERROR in test.tsx
      TS2339: Property 'toSatisfyAll' does not exist on type 'ArrayLikeMatchers<number>'.`
If run test, will get the following error:
`TypeError: expect(...).toSatisfyAll is not a function`

**Comment by vovsemenv** [comment]
Hello, sorry for the late answer. Its just the typescript question. to solve it you need to add `jest-extended` annotations to you typescript project.
More info: https://jest-extended.jestcommunity.dev/docs/getting-started/typescript

**Comment by vovsemenv** [comment]
also you need to add this line to `tsconfig.json` to let ts know that you using `jest`

```diff
{
    "compilerOptions": {
      "moduleResolution": "node",
      "target": "es5",
      "module": "CommonJS",
      "lib": ["es2015", "es2016", "es2017", "dom"],
      "strict": true,
      "sourceMap": true,
      "declaration": true,
      "allowSyntheticDefaultImports": true,
      "experimentalDecorators": true,
      "emitDecoratorMetadata": true,
      "skipLibCheck": true,
+      "types":["jest"],
    },
  }
```

**Comment by vzhik54** [comment]
Thanks for help and apologize for the long answer. I try to use this approach but get another error.
I attached sample to demonstrate the error.
[reproductionSample.zip](https://github.com/allure-framework/allure-js/files/11051452/reproductionSample.zip)
Please take a look at the sample and tell if there is any way to fix the error?
Error:
`This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
        at FileViewer (..\src\Components\FileViewer\FileViewer.tsx:5:49)`

We tried to wrap any things in `act` and from `@testing-library/react`, and from `react-test-renderer`. Also tried to do everything async, sync, rerender the component, do `data-testid ` static. The `showOpenFilePicker` mock works, the file is read, everything happens correctly, but test breaks down.
