### ISSUE TITLE
Which library should I be using?

### ISSUE THREAD

**Issue by ryparker** [allure-framework/allure-js#62]
Hi there.

I'm struggling to figure out which allure - mocha library I should be using. There seems to be 3 and all are referenced in different areas of allure's documentation/github repo. Some guidance would be very helpful.

`yarn add allure-mocha`: https://github.com/allure-framework/allure-js/tree/master/packages/allure-mocha
`yarn add mocha-allure2-reporter`: https://github.com/sskorol/mocha-allure2-reporter
`yarn add mocha-allure-reporter`: https://github.com/allure-framework/allure-mocha

Note: I'm not using typescript. However I do like the idea of being able to use the `@` annotations.

**Comment by baev** [comment]
* `allure-mocha` - the correct reporter, you should use this one
* `mocha-allure2-reporter` - beta version of reporter for Allure 2, code moved to this repository and package renamed to allure-mocha
* `mocha-allure-reporter` - old, Allure 1 reporter, reached EOL

**Comment by ryparker** [comment]
Thank you!
