### ISSUE TITLE
Support of CodeceptJS

### ISSUE THREAD

**Issue by guiyomh** [allure-framework/allure-js#621]
**Is your feature request related to a problem? Please describe.**

I use [codeceptjs](https://codecept.io/) and it had an[ allure plugin](https://www.npmjs.com/package/@codeceptjs/allure-legacy) that was just deprecated.

**Describe the solution you'd like**

Are you open to PR adding Codeceptjs support?

**Comment by vovsemenv** [comment]
Hello @guiyomh  right now we actively working on this reporter. Estimated time of release: end of week

**Comment by guiyomh** [comment]
oh great. Thank
