### ISSUE TITLE
Results of Scenario Outline are presented as a one test instead of separate results for every row in the Examples section

### ISSUE THREAD

**Issue by DanielDelimata** [allure-framework/allure-js#625]
**Describe the bug**
Results of Scenario Outline are presented as a one test instead of separate results for every row in the Examples section.
It seems that all executions of Scenario Outline are interpreted as Retries of one Scenario.

**To Reproduce**
1. Create a project with devDependencies: `"@cucumber/cucumber": "^9.0.0", "allure-cucumberjs": "^2.0.0"`
2. Prepare feature file with a Scenario Outline and an Examples section
3. Execute the command `npm test`
4. Execute the command `allure server allure-results`

Sample code: https://github.com/DanielDelimata/sample-typescript-cucumberjs-selenium
Sample results: https://danieldelimata.github.io/sample-typescript-cucumberjs-selenium

Correctly working code for older versions: https://github.com/DanielDelimata/sample-typescript-cucumberjs-selenium-old
Correct results: https://danieldelimata.github.io/sample-typescript-cucumberjs-selenium-old/

**Expected behavior**
The number of tests cases should reflect the number of rows in Examples section. Every row defines separate test case so each result should be presented separately.

**Screenshots**
Observed results:
<img width="1245" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/23411427/222240533-443b9711-3dc3-48b7-b40b-57c387750467.png">
<img width="417" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/23411427/222240564-ac522175-02a9-4cc9-be94-e96878a7141a.png">

Expected results:
<img width="1226" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/23411427/222240407-80a85f5a-2abc-44d8-b220-f963474923a3.png">

**Additional context**
From my observation, the Allure framework works correctly for Cucumber in Java, C#, Python, Kotlin. The problem may be related to changes in Cucumber itself (precisely in js package `@cucumber/cucumber`) cause for old cucumber versions (e.g. 6.0.5) it works correctly (see e.g. https://github.com/allure-examples/allure-javascript-cucumberjs/blob/master/package.json). It does not work correctly for versions above 7.

**Comment by Jordanlosa97** [comment]
This is happening on all integrations of this version 
Also on a integration of playWright 
https://github.com/Tallyb/cucumber-playwright

**Comment by cshuiu** [comment]
Any chance this can be picked up? I upgraded today from cucumber 7 to 9 and starting having this issue. To be fair, I was using "allure-cucumberjs8": "^2.0.0-beta.15", which  had it's own issues but at least test were displaying correctly.

**Comment by baev** [comment]
Fixed in 3.0.0-beta.11
