### ISSUE TITLE
 The problem of creating duplicate autotests by fullname and id

### ISSUE THREAD

**Issue by lunin-vadim** [allure-framework/allure-js#633]
I am using playwright. There are 5 tests in one spec file. In beforeAll I prescribe precondition annotations for all tests, and allure.id in each test is different. If the test falls at the beforAll stage to an annotation with id, then the system creates a test by full name

**Comment by DmitriyKapeliukh** [comment]
Is there an option to avoid test duplication except by passing metadata to the playwright test title?

**Comment by baev** [comment]
I guess the other option is to use Playwright tags after https://github.com/allure-framework/allure-js/pull/1034 gets merged:

```ts
import { test } from '@playwright/test';
test("test with allure id", { tag: "@allure.id:123" }, async() => {
  //...
});
```
