### ISSUE TITLE
allure-js-commons + cypress+ esbuild can not resolve "fs/promises"

### ISSUE THREAD

**Issue by mysticdevx** [allure-framework/allure-js#636]
**Describe the bug**
Hi
I am using cypress+esbuild with allure-js. When I was using the `v2.0.0-beta.18` version, all was ok, But when I upgraded to `v2.1.0` I started getting: 
```shell
Error: Build failed with one error:
../../node_modules/allure-js-commons/dist/src/utils.js:8:27: ERROR: Could not resolve "fs/promises"
```

**What I tried**
When I change the 
`const promises_1 = require("fs/promises");` to  `const promises_1 = require("fs").promises;` 
in `node_modules/allure-js-commons/dist/src/utils.js` file, again, all works as expected. 

**Expected behavior**
allure-js to work with esbuild +cypress without having  the given error

**Desktop (please complete the following information):**
 - OS: MacOS 13.2
 - Browser: any - because tests are running in cypress
 - Node Version: 14.20.1
 - Esbuild Version: 0.15.13

**Comment by mysticdevx** [comment]
@vovsemenv Hi, yes, I will prepare a clean repo in a few days and will update it here. Thanks.

**Comment by kobenguyent** [comment]
![image](https://user-images.githubusercontent.com/7845001/226158258-e2c9822e-309f-4312-8844-de6d76f3ca57.jpeg)

Maybe it's a node issue? Just curious if upgrading node to v16 for instance kills the issue
