### ISSUE TITLE
BROKEN tests failure messages are incomplete with respect to the Playwright HTML report

### ISSUE THREAD

**Issue by DvDream** [allure-framework/allure-js#637]
**Describe the bug**
Details for failures of tests resulted in status BROKEN because of "timeout exceeded" shows only the message

`Test timeout of .....ms exceeded.`

and I am pretty sure that there are other informations about the reason of the failures because the Playwright HTML report shows me more "message blocks".

Those error in the Playwright reports are show as separate blocks.

**To Reproduce**
1. Execute a test with allure-playwright dependency installed. Mine at the moment is 2.0.0-beta.19
2. The test fail
3. I generate both playwright HTML report and allure report. The first says the test is failed, the second says the test is broken. Both for test timeoput exceeded
5. Viewing the reasons for the error, the playwright html report shows me more message block for the reason of the failure, the allure one shows me only the first, that is `Test timeout of .....ms exceeded.`

**Expected behavior**
I would like to view the same report failures messages as the playwright HTML reporter in case of broken tests.

**Screenshots**
![image](https://user-images.githubusercontent.com/45291289/224966318-19e4f902-745e-4d3e-aeee-171d05aab980.png)
![image](https://user-images.githubusercontent.com/45291289/224966346-13af2b0c-25d1-4525-870b-6dabf54c714d.png)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Chrome 
 - Version 111.0.5563.64 

info about my allure settings:

I got the default settings for everything, that is all the steps are shown in the report.

**Comment by vovsemenv** [comment]
The stackTrace is hidden by default. You can click to error message for full stacktrace view like in plawright-html.

**Comment by DvDream** [comment]
> The stackTrace is hidden by default. You can click to error message for full stacktrace view like in plawright-html.

I did it actually, but it shows me this 
![Immagine 2023-04-07 104802](https://user-images.githubusercontent.com/45291289/230576501-8a76b517-99ef-4373-8ca0-681f3b650734.png)

**Comment by vovsemenv** [comment]
ok, interesting one. I will investigate

**Comment by DvDream** [comment]
Hello, I would like to know if there are any news about this bug, thank you!

**Comment by baev** [comment]
To close this problem, we need to solve two issues: [support for multiple errors](https://github.com/allure-framework/allure-js/issues/704) and [support for parsed stack trace](https://github.com/allure-framework/allure-js/issues/353).
