### ISSUE TITLE
Allure-hermione doesn't match describe as suite

### ISSUE THREAD

**Issue by alenamakarovaya** [allure-framework/allure-js#643]
**Describe the bug**
Package  doesn't match describe as suite in hermione tests, it can be matched as suite if we use nesting of describes
For example, it works now 
describe('1', , function () {
 describe('2', function () {
   some code});
});
As a result: suite = describe('2')
describe('1') is ignored
**We need all describes were provided as suites(or custom fields)**

**To Reproduce**
1. Use example from https://github.com/allure-examples/allure-hermione-example/blob/main/tests/desktop/startpagePassed.mjs and add describe like:
describe("Result page", function () {
it("redirects on the results page", async ({ browser, currentTest, ...rest }) => { ...
2. Create allure report

**Expected behavior**
Describes aren't ignored and matched as suites of test(or custom fields)

**Comment by epszaw** [comment]
Probably the issues has been solved in #695
