### ISSUE TITLE
Only Trends metric is showing when using allure serve after the allure generate

### ISSUE THREAD

**Issue by kobenguyent** [allure-framework/allure-js#647]
**Describe the bug**
I noticed something which is very strange and still a mystery for me. Not sure if I did something wrong. 

After my test execution with codeceptjs and xml results are stored in output folder for example. 
- when I run allure serve output/, I could see all the tcs info, etc. but trends metric is empty. 
- then I run allure generate output/, after that I have allure-results, so I run allure serve allure-results, this time I see only trends metric but other info like tcs are all empty.

**Comment by baev** [comment]
Closed as stale, please [create a discussion](https://github.com/orgs/allure-framework/discussions/categories/questions-support) if the issue is still relevant.
