### ISSUE TITLE
Newman - Test case status is passed even with failed steps

### ISSUE THREAD

**Issue by jeremie-val** [allure-framework/allure-js#649]
**Describe the bug**
Sometimes, on our gitlab CI pipeline, we saw on allure that all tests are passed, but when we looks in detail, we see that the steps failed

**To Reproduce**
Hard to reproduce as we do not have any clue on what's happend here, but you can have information in the zip file below and in the CLI console log.

**Expected behavior**
If a step failed, we should have a failed test case

**Screenshots**
![Capture d’écran du 2023-03-27 10-04-09](https://user-images.githubusercontent.com/79636114/228482019-f78d0e7e-3a8d-4b36-9b1e-94ae1dcbee7d.png)

**Additional context**
Here are some information about how our pipeline works : 
We execute different newman collection with the newman-allure-reporter package (we also add this parameter : --reporter-allure-collection-as-parent-suite).
All of the newman command populate the allure-results directory.

After the execution is done, we run the generation of the allure-results and see the difference.
We also have a htmlextra reporter which indicate the good status.
[report.zip](https://github.com/allure-framework/allure-js/files/11098691/report.zip)

**Comment by vovsemenv** [comment]
can you please send also example collection with reproduction of this bug?

**Comment by edouard-lopez** [comment]
Got a similar situation, we caught this because the pipeline job was failing while the Allure dashboard was green.
