### ISSUE TITLE
newman allure reporter + Jenkins allure plugin cannot display historical test case result correctly

### ISSUE THREAD

**Issue by coolalexhuang** [allure-framework/allure-js#658]
**Describe the bug**
I am using "newman-reporter-allure" reporter plugin to generate allure-results folder, then use Jenkins allure report plugin https://plugins.jenkins.io/allure-jenkins-plugin/ to generate allure-report, however, I found the test case number will increase after each Jenkins build, like I have 3 test cases in newman collection json, after the 1st build, it shows 3 test cases in allure report, after 2nd build, it will show 6 test cases, then 9 , then 12..., and the history of each case is incorrectly display.

I have tried to use PyTest-Allure to generate allure-results, then use Jenkins allure plugin to generate allure-report, the report works well, so I guess it should be a bug for the newman-allure-reporter.

**To Reproduce**
1. newman run collection.json -e env.json -r allure --reporter-allure-export ./allure-results
2. allure-results  ./allure-results -c -o ./allure-report 

**Expected behavior**
Each allure report should show the same test case number, and the test result history should be correct.

**Screenshots**
Newnan allure report:
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/2528449/231467592-31aaf05d-4a78-4230-9356-71acae45832d.png">

PyTest allure report:
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/2528449/231467807-80f50334-daf9-43ba-874f-0b22ebd0a57e.png">

**Comment by delatrie** [comment]
Newman-reporter-allure used to set `historyId` randomly each run. That was fixed in `newman-reporter-allure@3.0.0-beta.1`.
If something is still wrong with the package, please, let me know here or open a new issue.
