### ISSUE TITLE
Support Vitest reports upload

### ISSUE THREAD

**Issue by alyaothman14** [allure-framework/allure-js#660]
**Is your feature request related to a problem? Please describe.**
I would like to be able to upload results from vitest to allure testops so would like this to be supported by allure-framework
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://github.com/allure-framework/allure-js/issues/415

**Comment by vanessasidrim** [comment]
Hello, any news about vitest support in allure-framework?

**Comment by epszaw** [comment]
Good news! We made official vitest reporter (#830). It will be available to install soon
