### ISSUE TITLE
Show Playwright Annotations in Report

### ISSUE THREAD

**Issue by zzoubian** [allure-framework/allure-js#661]
**Is your feature request related to a problem? Please describe.**
We recently started using Playwright, and we were planning to use the Allure framework for our reports. Additionally, we would like to pass additional test information to Xray. In order to that we use playwright annotations to pass this information.  We noticed that when we add those annotations they not appear in the Allure report.

**Describe the solution you'd like**
Show playwright annotations in report.

**Describe alternatives you've considered**
Because we aren't able to see the annotations in the report, we are currently using the built-in Html reporter.

**Additional context**
[Xray Playwright Integration](https://docs.getxray.app/display/XRAYCLOUD/Testing+web+applications+using+Playwright)

Related to: https://github.com/allure-framework/allure-js/issues/490

**Comment by mikicymulate** [comment]
When will the SKIP Annotations be fixed?
![image](https://github.com/allure-framework/allure-js/assets/106581694/54d31e77-71b7-4292-a409-8eae73a45109)

**Comment by baev** [comment]
skip and fixme annotations support: https://github.com/allure-framework/allure-js/pull/1035

**Comment by ZakiZoubian** [comment]
Can we add support for playwright runtime annotations?
https://playwright.dev/docs/test-annotations

![image](https://github.com/user-attachments/assets/0f48f19b-e286-47d8-984f-5a84ad0ec97d)

For example:

  testInfo.annotations.push({ type: 'test_key', description: 'KEY-123' });

  test.info().annotations.push( {
    type: 'browser version',
    description: '1.0.0',
  });

In the html report they show like this:
![image](https://github.com/user-attachments/assets/628a91cd-51b0-4e15-9b19-3183f9862ba4)
