### ISSUE TITLE
Don't count repeatEach as a retry

### ISSUE THREAD

**Issue by alyaothman14** [allure-framework/allure-js#663]
**Describe the bug**
We are currently using repeatEach as a measure of the testcase performance. In allure, it counts the repeatEach as a retry and would mark the testcase as passed if one of the repeatEach fails which is incorrect.
With repeatEach, each testcase should be processed separately similar to how playwright report is 
![image](https://user-images.githubusercontent.com/87079479/233395496-7f753cd9-01a3-48a7-b1cc-c091f2db0350.png)
![image](https://user-images.githubusercontent.com/87079479/233395738-8c4b69c6-920a-40b3-af31-bfc661ffdc4c.png)

**Expected behavior**
Allure reports to behave the same as the playwright where is a separation between repeatEach and retry

**Comment by baev** [comment]
already fixed
