### ISSUE TITLE
Mocha with configuration file can't correct setup the reporter

### ISSUE THREAD

**Issue by epszaw** [allure-framework/allure-js#668]
**Describe the bug**
When using mocha configuration file and run the runner via cli (not via programmatic API) – always getting an error, that the runtime API is not available in parallel mode.

**To Reproduce**
1. Create a new mocha project
2. Create `.mocharc.js` configuration file
3. Set `parallel: false` in the config
4. Run `npx mocha`

**Expected behavior**
Runtime API should work

**Comment by ValentinCondurache** [comment]
Hello, any updates regarding this issue?

**Comment by deyvisPedrosa** [comment]
I'm facing the same behavior having `.mocharc.cjs` with the following opts:
```
module.exports = {
  color: true,
  delay: false,
  diff: true,
  reporter: 'mocha-multi',
  'reporter-option': ['spec=-','allure-mocha=-'],
  require: '@babel/register',
  timeout: '50000', 
  'trace-warnings': true,
  jobs: 0,
  parallel: false,
};
```
