### ISSUE TITLE
It is not currently possible to create a substep in codeceptJS adapter

### ISSUE THREAD

**Issue by zyab1ik** [allure-framework/allure-js#674]
**Is your feature request related to a problem? Please describe.**
Add support for the createStep method in AllureCodeceptJS because the plugin has been moved to @codeceptjs/allure-legacy, and this method has been removed. It is not currently possible to create a substep in the manual test cases.

**Describe the solution you'd like**
Add implementation createStep()

**Describe alternatives you've considered**
The [stepStarted](https://github.com/allure-framework/allure-js/blob/master/packages/allure-codeceptjs/README.md)() method only creates a step, and nesting the method does not produce a result
```javascript
allure.stepStarted(step, () => {
      allure.stepStarted(subStep);
    });
``` 

doesn't work!

**Additional context**
Commit when this function was removed: 
https://github.com/codeceptjs/CodeceptJS/commit/da049146c32086c649b2dc99ef9e76a9a8ce18e8#diff-04141df5585e55f45952099d730f4a49d122d27da1ee5c4e402902dc31c0442f 
CodeceptJs adapter - 2.2.1

**Comment by baev** [comment]
fixed in allure-codeceptjs@3.0.0-beta:

```ts
import { step, attachment } from "allure-js-commons";

Feature('sample');
Scenario('test something', async ({I}) => {
  await step("step 1", async () => {
    await step("step 1.1", async () => {
      await step("step 1.1.1", async () => {
        await attachment("Sample text attachment for step", "Hello world!", "text/plain");
      });
    });
  });
});
```
