### ISSUE TITLE
Cannot see the test detail steps under the allure report test body

### ISSUE THREAD

**Issue by 100rab94** [allure-framework/allure-js#680]
The allure report generated doesnt show up the test details under test body even after using the parameter detail: true under reporter config.

_Note: The project is based on pure playwright JS_

1. Installed playwright allure - npm i -D @playwright/test allure-playwright
    "@playwright/test": "^1.33.0",
    "allure-playwright": "^2.2.1"
    
2. Installed Command line - npm i allure-commandline
"dependencies": {
    "allure-commandline": "^2.22.0"
    
3. Added the reporter config in playwright.config.js
reporter: [
    ['junit', { outputFile: './junitReports/results.xml' }],
    ['line'], ['allure-playwright',{
      detail: true,
      outputFolder: "my-allure-results",
      suiteTitle: false,
    },]
    
4. Executed the script
npx playwright test TC402_Shop_Fiber_Journey_New_Customer.spec.js --headed

5. Generated the report
npx allure generate --clean allure-results

6. Opened the generated allure report
npx allure open

**Expected behavior**
I'm expecting the test step details under test body in the allure report but currently I cannot see any
![image](https://github.com/allure-framework/allure-js/assets/61851444/9ff26a95-c2a8-4c4c-aa59-8b91629076b0)

**Screenshots**
What I see currently on the allure report generate currently is like below:
![image](https://github.com/allure-framework/allure-js/assets/61851444/edc79c16-d828-4815-bc37-f38ad16709a8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chromium

Could someone please help me? Thanks

**Comment by tmareev** [comment]
Hey, I had the same problem when ran the tests with "line" + "allure" or just with "allure". It seems weird but try to use "html" + "allure" reporters when you are running the tests. 

1. my reporter configuration (in playwright.config.js) is:

reporter: [
    ['html'],
    [
      'allure-playwright',
      {
        detail: true,
        outputFolder: 'allure-results',
        suiteTitle: true,
      },
    ],
  ],

2. Executed the script:
npx playwright test

3. Generated the report
npx allure generate ./allure-results --clean

4. Opened the generated allure report
npx allure open ./allure-report


Result:
https://github.com/allure-framework/allure-js/assets/41381148/d7906b75-c37a-41c5-879d-b27f1b3bb41f

**Comment by PRASADREDDY253** [comment]
I am also facing same issue

**Comment by 100rab94** [comment]
> I am also facing same issue

The newer version has fixed the issue and hence I'm very happy now. 
"devDependencies": {
    "@playwright/test": "^1.33.0",
    "allure-playwright": "^2.3.0"
  },
  "dependencies": {
    "allure-commandline": "^2.22.0"
  },
Thanks everyone.

**Comment by PRASADREDDY253** [comment]
yes, my issue also resolved ,Thank you

**Comment by alexviktoria** [comment]
Good day! I have the same issue.
Installed playwright allure - npm i -D @playwright/test allure-playwright
"@playwright/test": "^1.37.1",
"allure-playwright": "^2.6.0",

Installed Command line - npm i allure-commandline
"dependencies": {
"allure-commandline": "^2.24.0",

Added the reporter config in playwright.config.js
reporter: [['html'],
    ["allure-playwright", {
        detail: true,
        outputFolder: "my-allure-results",
        suiteTitle: true,
      },
    ],
  ],

Executed the script
"test:11-03-04": "npx playwright test /e2e/education/US_11-03-04.spec.js --reporter=line,allure-playwright --workers 1",

Generated the report
"allure:report": "allure generate ./allure-results -o allure-report --clean && allure open",
Desktop (please complete the following information):

OS: Windows
Browser : Chromium
Screenshots

![What I see currently on the allure report generate currently is like below:]
(https://github.com/allure-framework/allure-js/assets/119632454/eb28a611-372b-4e67-b0ac-1b7eca64e19c))
