### ISSUE TITLE
When rerunning a test, the report does not display the current status

### ISSUE THREAD

**Issue by shineqwe** [allure-framework/allure-js#693]
If the test is run once, the report shows the correct result 
[firsTimeTrue.zip](https://github.com/allure-framework/allure-js/files/11596603/firsTimeTrue.zip)

If the test fails, it automatically runs again. If the test is re-run successfully, the report shows that the test failed.
[secontTimesFalsAndTrue.zip](https://github.com/allure-framework/allure-js/files/11596631/secontTimesFalsAndTrue.zip)

In report no information available about test retries

**Comment by epszaw** [comment]
Which integration do you use?
