### ISSUE TITLE
[ALLURE -RESULT] Artifacts from git action unable to generate report

### ISSUE THREAD

**Issue by joylan2105** [allure-framework/allure-js#699]
I was trying to get the allure-results folder and put it in git action as an artifact then download the artifacts and generate a report. However, when I try to generate a report. it doesn't display records. 

1. Add step in github action to be able to get allure results artifacts
2. Download the artifacts and unzip
3. open the file folder via terminal then run command "allure serve"
4.  index.html shows no data.

I am expecting that after I extract the zip file of the allure-result artifacts and run allure serve, it would show report in
 index.html 

**Screenshots**
![image](https://github.com/allure-framework/allure-js/assets/69957490/ab994a9c-a4bb-40e9-9e79-ac574329d649)

![image](https://github.com/allure-framework/allure-js/assets/69957490/104d0148-db96-4b0d-aff2-2f95c7852eb2)

![image](https://github.com/allure-framework/allure-js/assets/69957490/55d17dc5-05d7-46db-bcd4-a870f3372861)

**Additional context**
Are there any steps that I might need to do?

**Comment by baev** [comment]
The log says `allure-results` doesn't exist. To make it work, please specify the directory with the allure-results as an argument for the `allure serve` command instead of running the command in the directory with results.
