### ISSUE TITLE
Implement @step decorator

### ISSUE THREAD

**Issue by korobochka** [allure-framework/allure-js#7]
[//]: # (
. Note: for support questions, please use Stackoverflow or Gitter**. 
. This repository's issues are reserved for feature requests and bug reports.
.
. In case of any problems with Allure Jenkins plugin** please use the following repository 
. to create an issue: https://github.com/jenkinsci/allure-plugin/issues
.
. Make sure you have a clear name for your issue. The name should start with a capital 
. letter and no dot is required in the end of the sentence. An example of good issue names:
.
. - The report is broken in IE11
. - Add an ability to disable default plugins
. - Support emoji in test descriptions
)

#### I'm submitting a ... 
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Decorators greatly reduce boilerplate required to create steps.
We should support API similar to Java decorators.

**Comment by sskorol** [comment]
I've added `AllureContainer` to `allure-js-core` in #138. It allows reporters setting `Allure` implementation in runtime.
