### ISSUE TITLE
Seems that label feature not rendering

### ISSUE THREAD

**Issue by EltonZhong** [allure-framework/allure-js#70]
The xml is generated by allure-mocha, and when transferd to html, label feature is missing.
```xml
 <?xml version='1.0'?>
 <ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1578913462617' stop='1578913466708'>
     <name>Simple login</name>
     <title>Simple login</title>
     <test-cases>
         <test-case start='1578913463776' status='broken' stop='1578913466644'>
             <name>I believe I can fly</name>
             <title>I believe I can fly</title>
             <labels>
                 <label name='feature' value='Simple loginfeature'/>
             </labels>
             <parameters>
                 <parameter kind='argument' name='env' value='test'/>
                 <parameter kind='argument' name='religion' value='ph'/>
             </parameters>
             <steps/>
             <attachments/>
             <failure>
                 <message>First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.</message>
                 <stack-trace>TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
                     at Function.Buffer.from (buffer.js:183:11)
                     at screenshot (common/hack_mocha.js:51:42)
                     at &lt;anonymous>
                     at process._tickCallback (internal/process/next_tick.js:189:7)</stack-trace>
             </failure>
             <description type='text'>Simple loginname</description>
         </test-case>
     </test-cases>
 </ns2:test-suite>
 ~
```

Report is like below:
![image](https://user-images.githubusercontent.com/20570738/72251835-61cbbf80-3639-11ea-896f-86524459d3f7.png)

**Comment by EltonZhong** [comment]
And I'm using this: 
![image](https://user-images.githubusercontent.com/20570738/72251963-89bb2300-3639-11ea-87c1-6584853683e8.png)

**Comment by korobochka** [comment]
I think "feature" (together with "story" and "epic") are used by Allure generator to determine the structure of tests in "Behaviors" view. It is not displayed on the test itself.
If you want to add some kind of a "label" to the test itself I can suggest adding "tag" label, allure will put it in the test info.

**Comment by EltonZhong** [comment]
> I think "feature" (together with "story" and "epic") are used by Allure generator to determine the structure of tests in "Behaviors" view. It is not displayed on the test itself.
> If you want to add some kind of a "label" to the test itself I can suggest adding "tag" label, allure will put it in the test info.

useful, thank u
