### ISSUE TITLE
Allow customizing the ExecutorInfo from allure-js-commons

### ISSUE THREAD

**Issue by noomorph** [allure-framework/allure-js#702]
**Is your feature request related to a problem? Please describe.**

I'd like to make it possible to **customize executor information programmatically.**

**Describe the solution you'd like**

`allure-js-commons` should export `ExecutorInfo` from its `model.d.ts`.

Ideally, `AllureWriter` should provide `writeExecutorInfo()` method as well.

**Describe alternatives you've considered**

Copy & pasting the type definition and creating a side writer to that `executor.json`, huh? 🤨  😄 

**Additional context**

![image](https://github.com/allure-framework/allure-js/assets/1962469/81fd890a-7959-406e-aa47-080ff5dfacec)

P. S. So, is there a good reason why `allure-js-commons` provides a method for writing down the environment info, but not the executor info?

**Comment by baev** [comment]
fixed in 3.0.0
