### ISSUE TITLE
Metadata appear is in test name

### ISSUE THREAD

**Issue by knysh** [allure-framework/allure-js#705]
**Describe the bug**
Metadata should not be in test name in report

**To Reproduce**
Preconditions: 
1. version of allure-js [2.3.0](https://github.com/allure-framework/allure-js/releases/tag/v2.3.0)
2. pass metadata in test title

1. run the test
3. generate allure report

**Expected behavior**
Metadata passed in title is NOT appear in test name in report

**Actual behavior**
Metadata appear in test name in report

**Screenshots**
<img width="1245" alt="Снимок экрана 2023-06-19 в 19 48 26" src="https://github.com/allure-framework/allure-js/assets/5208575/d48a8a11-8771-43d9-a866-c0ccbc25ea38">

**Versions:**
 - version of allure-js [2.3.0](https://github.com/allure-framework/allure-js/releases/tag/v2.3.0)

**Test:**
```
import { test } from '@integration-tests/fixtures/setup.fixture';
import { expect } from '@playwright/test';

test.only('Metadata in test @allure.id=1111', async () => {
  expect(true).toBeTruthy();
});

```

**Comment by baev** [comment]
Since Playwright has limited support for tags, I suggest implementing it on our side. 

1. All tags should be removed from the test name.
2. System tags (everything that starts with `@allure.`) should be processed and omitted from tags.
3. All other tags should land to test tags.

The questions -- should we include tags into testCaseId & history calculations? Should we use original name for full name or omit tags from it as well?

**Comment by vovsemenv** [comment]
I guess we need to use name with omitted tags because otherwise fullName and testcaseid/historyId will change every time when appling something like `@slow` or anything else. If user don't have `allureId` it will create new cases which is bad.

**Comment by baev** [comment]
Should we support tags at the beginning/middle of the name? or only at the end?

**Comment by angry-qa** [comment]
Can you tell me when you plan to fix this?

**Comment by epszaw** [comment]
@knysh could you answer @baev's question? It's difficult to estimate anything without vision of the whole requested feature

**Comment by knysh** [comment]
@epszaw thank you for tagged me. 
based on [the feature](https://github.com/allure-framework/allure-js/tree/master/packages/allure-playwright#passing-metadata-from-test-title) supports tags at all test name parts, I expect you will support the same,  support tags at the beginning/middle/end of the name

**Comment by lunin-vadim** [comment]
@vovsemenv @baev Can you tell me when you plan to fix this?

**Comment by knysh** [comment]
@baev @vovsemenv  I have checked the fix and everything is okay, thank you so much.
I just want remark that your fix related only @allre.id annotation, but playwright could have a lot. As you can see [here](https://playwright.dev/docs/next/test-annotations), playwright is using metadata for tagging. Maybe it is possible to improve this  fix to exclude any metadata from test name?
