### ISSUE TITLE
Allure-Playwright `detail` and `suiteTitle` options are not true by default

### ISSUE THREAD

**Issue by moondrek** [allure-framework/allure-js#710]
**Describe the bug**
The `allure-playwright` documentation indicates that the `detail` and `suiteTitle` options default to true. They behave as defaulting to false.

**To Reproduce**
1. Run a playwright test with the allure-playwright reporter, and no reporter options set.
2. Detailed steps for Before / After hooks and API calls are not present in the output

**Expected behavior**
When the `detail` key is not set in the reporter options, or no options are set for the reporter, Before / After hooks and API calls should be present in the output.
Alternatively, the documentation should be updated to reflect the observed behavior, and users should be advised that these options must be manually set true.

**Additional context**
I am using the following packages:
`allure-playwright@2.4.0`
`@playwright/test@1.33.0`

I dug a little bit -- when the playwright runner initializes the reporter, it seems to call it with an options argument that looks like: `{ configDir: '/path/to/dir' }`. The reporter sets default options parameters set here: https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/src/index.ts#L80 
Since the options object is not empty, the reporter never sets the options to the expected default `true`, leaving them falsey by default.

**Comment by nbaldzhiev** [comment]
I was wondering what I am missing while reading the documentation, because it is behaving exactly the opposite for `detail` and `suiteTitle` and can confirm as well that setting both to `true` worked as intended. By default, it didn't behave as if though they were set to `true`.
