### ISSUE TITLE
newman-allure-reporter -- custom allure labels set in postman are not displayed on the report

### ISSUE THREAD

**Issue by rsivasubramaniam** [allure-framework/allure-js#725]
**Describe the bug**
Custom allure labels set in Postman are not displayed on the report in spite of the "**/allure-results/XXXXXX-results.json --> labels[]**" containing them 

**To Reproduce**
1. Add some custom labels under the Postman test - **e.g. // @allure.label.customLabel=someCustomValue** (e.g. official test from the repo also contains a similar custom label --> https://github.com/allure-framework/allure-js/blob/master/packages/newman-reporter-allure/tests/overview.test.ts)
2. Run the test using newman cli with allure as the reporter
3. Generate the allure report locally or the report that was generated if using a CI platform like Jenkins / CircleCI
4. The report will not contain the custom label values even though the results.json contains them 

**Expected behavior**
Allure report should contain the custom label values set from the PM test tab

**Screenshots**

E.g. Custom Labels set in PM: 

![image](https://github.com/allure-framework/allure-js/assets/96515699/4aebaea2-9547-426e-a77a-3a759ab2cbac)

---------------------------------------------------------------------------------------------------------------------------
E.g. Left - Allure report | Right - Results.json: 

![image](https://github.com/allure-framework/allure-js/assets/96515699/bdd733e5-1104-4aa9-b7a2-15b5dc2e4064)

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser: [N/A]
 - Version: [N/A]

newman-allure-reporter: 

- Version: [2.4.0 - latest]

**Additional context**
N/A

**Comment by rohitvipin** [comment]
Is there any update, feedback or workaround for this?

**Comment by baev** [comment]
As for now, Allure Report only supports specific sets of labels. You can find the complete information here: https://github.com/orgs/allure-framework/discussions/2059#discussioncomment-6616266

As for today, custom labels can be displayed in [Allure TestOps](https://qameta.io/). For Allure Report, we plan to improve this functionality and introduce additional flexibility in the upcoming 3.0 release
