### ISSUE TITLE
Failed step marked as passed when we use assertView() inside 

### ISSUE THREAD

**Issue by alenamakarovaya** [allure-framework/allure-js#728]
**Describe the bug**
Failed step marked as passed when we use assertView() inside 

**To Reproduce**
1. It can be reproduced in repo https://github.com/fortrest-jr/allure-tests/tree/Steps on branch Steps
2. Switch to branch Steps
3. npm i
4. npm run test 
5. Create allure report

**Expected behavior**
Test failed on step with assertView() inside and it's marked as failed step

**Actual behavior**
Step is marked as passed

**Screenshots**
![image](https://github.com/allure-framework/allure-js/assets/128146377/c5dbbae5-678e-4510-a2c7-4721eb29433c)

**Comment by epszaw** [comment]
`assertView` doesn't throw any error, so we can't handle it in step and mark the step as failed

**Comment by epszaw** [comment]
Hermione team shall solve the problem on their side
