### ISSUE TITLE
Allure Report includes excluded tests as skipped 

### ISSUE THREAD

**Issue by ibrocodes7** [allure-framework/allure-js#729]
**Describe the bug**
We have a system in place that generates test cases and their skipped status, and then sends this information to multiple machines to execute the tests. The test extractor performs the command "npx playwright test --list "<path>" to generate a JSON file containing all the available tests. However, only a few tests are actually executed in our test impact analytics pipeline.

The issue we're facing is that the allure reporting tool generates a report for all the tests immediately after running the command "npx playwright test --list "<path>." It marks all the tests as skipped initially, and when a subset of the tests is actually executed, it updates their status accordingly. However, the overall summary report still shows the excluded tests (the ones that were not run) as skipped, which is misleading.

**Version**
Allure - latest
Playwright - "@playwright/test": "1.24.0",

**To Reproduce**
1. Configure the test extractor to generate a JSON file containing test cases and their skipped status using the command: 
npx playwright test --list "<path>"

3. Execute a subset of the tests using the command: 
npx playwright test --grep "<test_pattern>"

5. Generate the Allure report using the command:    
 "allure-report": "npx allure generate allure-results --clean -o allure-report; npx allure open allure-report",

6. See error

**Expected behavior**
The Allure report should accurately reflect the status of only the executed tests. Excluded tests should not be included in the overall summary, as they were not run during the test execution.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs (13.4.1 (c) (22F770820d))
 - Browser [chrome]
 - Version Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by ibrocodes7** [comment]
cc: @epszaw

**Comment by ibrocodes7** [comment]
Hello team, has anyone had a chance to address this bug? It's crucial for my companybthat we get this resolved, so your attention would be greatly appreciated. Thank you!

**Comment by epszaw** [comment]
Hey, @ibrocodes7! Sorry for the delay. I will investigate the problem as soon as I have time for that 🙏

**Comment by ibrocodes7** [comment]
Hello team, has anyone had a chance to look into this bug?

**Comment by andycarson182** [comment]
I got the same issue, is there any update on this?

**Comment by baev** [comment]
The issue is that reporters are still executed when running the playwright with the `--list` option. See https://github.com/microsoft/playwright/issues/30706#issuecomment-2200663138

The workaround would be to override reporters' configuration:

```baseh
$ npx playwright test --list "" --reporeter dot
```
