### ISSUE TITLE
[Allure & Cucumber-JS] In the Packages tab there is no separation by packages

### ISSUE THREAD

**Issue by Zychkov** [allure-framework/allure-js#736]
**Description**
In the Packages tab there is no separation by packages. Tests are displayed as if they were in the same package.

allure-cucumberjs: 2.4.0
@cucumber/cucumber: 9.3.0

**Steps to reproduce the behavior**
1. Create feature files with different nesting paths.
2. Add and run tests.

**Expected behavior**
allure-results json files must have entity with path &labels[*].name = package.
It would allow when we go to the "Packages" tab to see the results of the test with a tree structure.

**Screenshots**
Nesting structure:
![image](https://github.com/allure-framework/allure-js/assets/48855208/390ff4df-6cec-4d2e-b877-40d9771bf749)

Report:
![image](https://github.com/allure-framework/allure-js/assets/48855208/bdb03eaa-3966-4bd2-9ff3-833af4ad7375)

**Comment by baev** [comment]
Fixed in 3.0.0 

see https://allure-examples.github.io/cucumberjs-npm-esm-ts/11/index.html#packages/68abf559c778265fcdbf68b5a94a39e0/e2a67002f241fc8e/
