### ISSUE TITLE
[Allure & Cucumber-JS] There is no description in the Allure Report

### ISSUE THREAD

**Issue by Zychkov** [allure-framework/allure-js#740]
**Describe the bug**
All lines in feature files that come after Feature, Scenario or Scenario Outline are not displayed in the Allure report.

allure-cucumberjs: 2.4.0
@cucumber/cucumber: 9.3.0

**To Reproduce**
1. Prepare a feature file with approximately the following content
```
Feature: Some feature
  Feature's description
  
  Scenario: Some scenario
    Description of scenario

    Given some give step
    When some when step
    Then some than step
```
2. Implement the steps 
3. Run the test
4. Generate the report

**Expected behavior**
The "Description" block is expected, by analogy with how it is done in Java
![image](https://github.com/allure-framework/allure-js/assets/48855208/452059fc-bce7-4185-99a8-1b0a797af022)

**Actual behavior**
There is no "Description" block
![image](https://github.com/allure-framework/allure-js/assets/48855208/03e80fa8-5997-4333-b05c-b015276d17a8)

**Comment by varshanharshank** [comment]
@Zychkov did you notice that  feature is still showing as scenario name? https://github.com/allure-framework/allure-js/issues/739

**Comment by epszaw** [comment]
The fix is ready. Just observe the linked PR
