### ISSUE TITLE
Show path to test file in Testops, generate it with allure-hermione

### ISSUE THREAD

**Issue by fortrest-jr** [allure-framework/allure-js#750]
**Is your feature request related to a problem? Please describe.**
It'll be easier to find tests in our project if full path to test file will be provided in web-interface of testops.

**Describe the solution you'd like**
Add parameter in web-interface which shows where test is located.
Additional feature: on click open test in IDE or in VCS.

**Additional context**
It's provided in results for other adapters as I see: https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/src/index.ts#L124-L127

**Comment by baev** [comment]
The full name is reserved for the Selective Run feature, so the format differs for each test framework. 

Speaking of your original request to have the view/additional parameter show the tests the same way they are located in VCS -- I guess it's much better to create a separate support request for that
