### ISSUE TITLE
Unable to view detailed testing steps in the test body part of the allure report

### ISSUE THREAD

**Issue by alexviktoria** [allure-framework/allure-js#766]
Unable to view detailed testing steps in the test body part of the allure report
Installed playwright allure - npm i -D @playwright/test allure-playwright
"@playwright/test": "^1.37.1",
"allure-playwright": "^2.6.0",

Installed Command line - npm i allure-commandline
"dependencies": {
"allure-commandline": "^2.24.0",

Added the reporter config in playwright.config.js
reporter: [['html'],
["allure-playwright", {
detail: true,
outputFolder: "my-allure-results",
suiteTitle: true,
},
],
],

Executed the script
"test:11-03-04": "npx playwright test /e2e/education/US_11-03-04.spec.js --reporter=line,allure-playwright --workers 1",

Generated the report
"allure:report": "allure generate ./allure-results -o allure-report --clean && allure open",
Desktop (please complete the following information):

OS: Windows
Browser : Chromium

**Expected behavior**
![allure-report](https://github.com/allure-framework/allure-js/assets/119632454/fccf3cb9-feec-4a2b-a2fe-9e90a2d34552)

**Screenshots**
![What I see currently in the generated allure report looks like this:]
(https://github.com/allure-framework/allure-js/assets/119632454/eb28a611-372b-4e67-b0ac-1b7eca64e19c)

**Comment by cmecklenborg** [comment]
By specifying `--reporter=line,allure-playwright` as a command line option, you're using the default options for those reporters, instead of the configurations set in `playwright.config.js`. There's currently a bug (#710) where the `detail` option is defaulting to false. However, if you run the playwright command with the `--reporter` option, it should work as expected with the configuration you have set.

**Comment by alexviktoria** [comment]
Unfortunately, nothing helped. I tried to run tests using the --reporter: command, but the report without detailing the steps, I also ran it with parameters from the configuration file - a report without detailing the steps. Maybe I misunderstood how best to run the tests to get a report with step-by-step instructions

**Comment by alexviktoria** [comment]
Thank you very much! Everything worked out. Alur report is shown in steps

**Comment by alexviktoria** [comment]
Thank you very much! Everything worked out. Allure report is shown in steps
