### ISSUE TITLE
Release 2.7.0 allure-plugin is creating duplicates scenarios and folder with extra metadata shown in test body

### ISSUE THREAD

**Issue by testPlaywright** [allure-framework/allure-js#772]
I have observed that updating to the latest version of 2.7.0 is creating duplicate folder structure and also creating extra meta data in the test body once executed.

**To Reproduce**
1. Run a test with these parameters present say like allure.parentSuite("Name of parent folder") and allure.suite("Folder within the parent folder")
2. Once executed and allure report is run the values are duplicated in multiple places the report is altogether misaligned.

**Expected behavior**
Report structure should be as per previous versions, currently I had to move it back to 2.5 or 2.4 in which the issue is not present so that can be taken as an example to understand the current behavior.

**Screenshots**

In this screenshot you can see Prod-Na-01/core_sanity/WSTEST-3070.spec.js is duplicated and is extra 
![image](https://github.com/allure-framework/allure-js/assets/130156784/7bd155b9-1a07-47b5-8eb9-6010a57c79aa)

Extra metdata of page.evaluate and attach allure.metadata.json
![image](https://github.com/allure-framework/allure-js/assets/130156784/b16692f9-aa7f-452e-8c7b-8f7ee2c3b2dc)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browse Chromium
 - Version Latest

**Additional context**

**Comment by baev** [comment]
That's because of https://github.com/allure-framework/allure-js/issues/710

Since 2.7.0, the defaults were changed for `detail` and `suiteTitle` configuration options. Consider disabling these options. See https://github.com/allure-framework/allure-js/tree/master/packages/allure-playwright#options-usage for details
