### ISSUE TITLE
Report missing history trend and history run

### ISSUE THREAD

**Issue by user19958** [allure-framework/allure-js#796]
**Environment
"@playwright/test": "^1.39.0"
 "allure-playwright": "^2.9.2"

**Describe the bug**
We migrated test from C# using Allure.NUnit to TS using playwright. But when I generate multiple test results then in final report is missing trend history chart and history run in testcases. I found some hint that i need to copy history from report to results which helps but still is missing build number in history trend chart and retries and history run are duplicated.

When i compare history-trand.json from C# and from playwright. In C# there is buildOrder attribute which is missing in allure-js history-trand.json

C#
[{"buildOrder":27,"reportName":"AllureReport","data":{"failed":0,"broken":0,"skipped":0,"passed":2,"unknown":0,"total":2}},{"buildOrder":26,"reportName":"AllureReport","data":{"failed":0,"broken":0,"skipped":0,"passed":2,"unknown":0,"total":2}}, ... ]

Playwright:
[{"data":{"failed":0,"broken":0,"skipped":0,"passed":4,"unknown":0,"total":4}},
{"data":{"failed":0,"broken":0,"skipped":0,"passed":4,"unknown":0,"total":4}}]

**To Reproduce**
1. Run playwright tests with allure-playwright reporter
2. Run npx allure generate allure-results --clean
3. Run playwright tests again
4. Copy history folder from report to results 
5. Run npx allure generate allure-results --clean
6. npx allure open ./allure-report/
7. **in report there is no build number - cannot navigate to history reports**
![obrazek](https://github.com/allure-framework/allure-js/assets/134925911/0ad47882-61eb-4644-a74a-2fc66a575219)
8. **retries tab and history tab are duplicated**
![obrazek](https://github.com/allure-framework/allure-js/assets/134925911/bdea4287-cec6-4675-b84a-8c477c2b165a)

**Expected behavior**
When I run multiple test and multiple times run npx allure generate allure-results --clean it will generate report with correct history run like in C#
![obrazek](https://github.com/allure-framework/allure-js/assets/134925911/599f3f66-2ba2-4661-badf-cbb86c3908ea)

I will be grateful for any advice how to solve this issue.

**Comment by baev** [comment]
https://github.com/allure-framework/allure2/issues/1609
