### ISSUE TITLE
[allure-playwright] Expect message is displayed twice in the report when using a custom error message.

### ISSUE THREAD

**Issue by sam-viz** [allure-framework/allure-js#799]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

I have encountered an issue using the following packages version:
    "@playwright/test": "1.39.0"
    "allure-playwright": "2.9.2"

**The issue:**
When using expect with a custom error message, there are two lines displayed in the Allure report.
Snippet code to reproduce:
Playwright configuration:
```
reporter: [
    ['allure-playwright',
      {
        detail: true,
        outputFolder: 'allure-results',
        suiteTitle: false,
      },
    ]
]
```

Test code to reproduce:
```
import test, { expect } from '@playwright/test';

test.describe('Test scenario', async () => {
  test('Testing scenario', async ({ page }) => {
    await page.goto('https://www.google.com');
    await expect(page, 'User should land on homepage').toHaveURL('/');
  });
});
```
The report
<img width="619" alt="Screenshot 2023-10-31 at 18 34 52" src="https://github.com/allure-framework/allure-js/assets/6889963/b56fdb85-32b3-4778-a9b0-d08196786a39">

As you can see, there are two lines added in the report. What's confusing is that's one is marked as passed.

After some investigation, i realized there were two step objects. One with expect type and the other was a 'pw:api' type.

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `allure-playwright@2.9.2` for the project I'm working on.
Here is the diff that solved my problem:

```diff
diff --git a/node_modules/allure-playwright/dist/index.js b/node_modules/allure-playwright/dist/index.js
index 008957d..7f7a26d 100644
--- a/node_modules/allure-playwright/dist/index.js
+++ b/node_modules/allure-playwright/dist/index.js
@@ -83,6 +83,16 @@ class AllureReporter {
         if (!allureTest) {
             return;
         }
+
+        if(step.title && step.category ===  'pw:api' && _result.steps.find(
+            stepResult => stepResult.category === 'expect' 
+            && step.title.includes(stepResult.title)
+            && step.location.line === stepResult.location.line
+            && step.location.column === stepResult.location.column
+        )){
+            return;
+        }
+        
         if (!this.options.detail && step.category !== "test.step") {
             return;
         }
```

This is my first time contributing to this repository, I would love to have guidance as to how to fix it more properly.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by gayvoronskaya** [comment]
We also have this problem

**Comment by epszaw** [comment]
Hey, @sam-viz! Feel free to open PR with the changes you proposed in above. Additionally, it would be great if you provide tests for the changes as proof of work. Then just ask me to review when the PR is ready.

**Comment by baev** [comment]
Works as expected using `playwright@1.45.0` and `allure-playwright@3.0.0-beta.4`

<img width="753" alt="Screenshot 2024-07-01 at 17 51 27" src="https://github.com/allure-framework/allure-js/assets/2149631/2a0fce13-d6b2-4fbc-ae69-7803d3df8a2a">
