### ISSUE TITLE
Add ability to assign custom names for any attachments

### ISSUE THREAD

**Issue by epszaw** [allure-framework/allure-js#801]
The features should work with any javascript integration

**Comment by Louis-Wu-Sea** [comment]
It's not working for me at:
```
 "allure-jest": "^2.9.2",
 "allure-js-commons": "^2.9.2",
```

I do it this way, for example:
`await allure.sendMetadata({
            attachments: [
                {
                    name: 'Request body',
                    content: JSON.stringify(response.data),
                    encoding: 'utf-8',
                    type: 'application/json',
                },
            ],
        });`
        
Since the "attachment" method does not accept the "name" parameter
` attachment(content: string | Buffer, type: string): void;`

**Comment by ivankarabutov1** [comment]
I'm looking forward to the release of this feature! I wish she'd come out soon.

**Comment by Louis-Wu-Sea** [comment]
Made a  pull requests - https://github.com/allure-framework/allure-js/pull/819

**Comment by SANTANYN** [comment]
I have this problem too, hope soon feature will able.
