### ISSUE TITLE
Allure reports showing "unknown" Time-Duration for Before and After Hook

### ISSUE THREAD

**Issue by paresh-celigo** [allure-framework/allure-js#809]
System info
Playwright Version: 1.32.3
Operating System: macOS 13.3.1
Browser: Chromium

<img width="628" alt="image" src="https://github.com/allure-framework/allure-js/assets/141011973/8f6937e2-5b38-48ac-b820-cd7b8793a376">

, 
This is my config details for allure: 
<img width="492" alt="image" src="https://github.com/allure-framework/allure-js/assets/141011973/40f40298-ec0e-4979-b954-94faa8b772a0">

@baev  @epszaw , Please suggest a solution for this I want to hide details but its hiding time taken for before hook and after hook and showing unknown.

**Comment by paresh-celigo** [comment]
@baev , can you please help me with this issue

**Comment by epszaw** [comment]
@paresh-celigo thank you for the issue! Will try to figure out, what's going wrong. Will let you know when I get some details.

**Comment by epszaw** [comment]
So, I added some tests, which check `start` and `stop` time for the hooks [here](https://github.com/allure-framework/allure-js/pull/828/files#diff-ea42407c136b51f2bc8e00c123118ed7909787429ebf6a36ef48982dc982ff03R21) and everything seems ok. Could you please provide a repository where I'll be able reproduce the problem?

**Comment by paresh-celigo** [comment]
Hello @epszaw Thank you for your response, I dont have demo project to reproduce the issue and my working project is confidential so I cant share the repo, but I am facing this issue when I add details : false  in allure-playwright config

**Comment by epszaw** [comment]
@paresh-celigo try to use `detail: false` option instead

**Comment by paresh-celigo** [comment]
@epszaw  I already tried with detail: false, but got same result. it did not worked

**Comment by epszaw** [comment]
Here I've created an example repo https://github.com/epszaw/issue-809-playwright-hooks-reporting.
I'm not able to reproduce your problem because [`detail: false` flag](https://github.com/epszaw/issue-809-playwright-hooks-reporting/blob/master/playwright.config.js#L25) fully disables hooks reporting.
