### ISSUE TITLE
Unable to delete old generated allure files from all-results and allure report

### ISSUE THREAD

**Issue by nirmalprojects1988** [allure-framework/allure-js#814]
**Describe the bug**
Generated allure report files doesnot get clean when used clean command 

**To Reproduce**
1. I used this command to install npm package of allure report npm i allure-playwright
2. Made changes in the playwright.config.ts file as reporter: "allure-playwright";
3. Ran the command to execute tests and generate file to all-results folder **npx playwright test --reporter=line,allure-playwright**
4. Ran the command to generate report file **allure generate my-allure-results -o allure-report --clean**

Actual behaviour
On each run i.e allure generate my-allure-results -o allure-report --clean , i see allure-results folder keeps growing with each new test run, even though I'm using the --clean command.

**Expected behaviour**
Upon running the clean command allure-results folder should be cleaned 

**Screenshots**
as you can see on each run files are getting added to the folder,The count what i marked is just show the allure-results files count
<img width="624" alt="image" src="https://github.com/allure-framework/allure-js/assets/43513314/d6609e83-9ec7-4e74-83a7-0ba261bb9e6a">

**Comment by NikolaQAautomation** [comment]
I am having exactly the same problem with --clean. Any response on this one?

**Comment by epszaw** [comment]
The issue relates to [allure-framework/allure2](https://github.com/allure-framework/allure2). Have just created an issue and linked it here.

**Comment by baev** [comment]
Simply delete the `allure-results` directory before the tests run.
