### ISSUE TITLE
Use 'stack' property of error instead of 'trace'

### ISSUE THREAD

**Issue by vitaly-kiselev-qa** [allure-framework/allure-js#821]
Looks like wrong property is used to get the error stack:
https://github.com/allure-framework/allure-js/blob/f8552fd003bb0c2890e7823716d784147f28fe68/packages/allure-js-commons/src/AllureCommandStep.ts#L271

There is `e.trace`, but it should be probably `e.stack`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack

**To Reproduce**
1. Run any test which fails with an error inside a step.
2. Open the failed step in the generated Allure report.
3. Click the error message within the step.
4. The "Empty status details" message is shown.

**Expected behavior**
The error stack is shown.

**Screenshots**
![empty_status_detail](https://github.com/allure-framework/allure-js/assets/104146273/bc202fcb-d136-43ab-9122-42d474a94f3b)

**Desktop**
 - OS: macOS Ventura 13.6.1
 - Chrome
 - Version 120.0.6099.109 (Official Build) (x86_64)

**Comment by epszaw** [comment]
We can't rely on the property right now because it's now widely supported, but we can use it with fallback on `trace` one, like this `e.stack ?? e.trace`

**Comment by epszaw** [comment]
We don't use `trace` property anymore
