### ISSUE TITLE
 Problem with restarting and running tests

### ISSUE THREAD

**Issue by snataCRPO** [allure-framework/allure-js#829]
**Describe the bug**
You have changed the regex for testplan.js to restart/run tests https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/src/testplan.ts#L11 (or https: //www.npmjs.com/package/allure-playwright?activeTab=code), used to be more loyal.
Now the test plan does not find tests. Through experimentation, it turned out that not the full path to the test is passed to the selector, for example, the first picture displays the path avia/search/webview.avia.search.test.ts..., but in fact it is webview/avia/search/webview. avia.search.test.ts... (when adding webview to the selector, the test was found and run)

**To Reproduce**
1. Go to launches
2. Click on rerun test
3. A job in GitLab receives a test plan, but cannot find tests based on the passed selectors

**Expected behavior**
Tests from the test plan are launched

**Screenshots**
Test:
![photo1703262720](https://github.com/allure-framework/allure-js/assets/123930035/13b844d6-a17a-4e25-b981-1232c43ae276)

Test plan transferred to GitLab job:
![photo1703262720 (3)](https://github.com/allure-framework/allure-js/assets/123930035/32653c84-0529-4808-8e91-d02fd859d50d)

Path to the folder with tests:
![photo1703262720 (1)](https://github.com/allure-framework/allure-js/assets/123930035/cd2001b2-3e80-42b8-ac3a-91223895ad36)

Path when running the test:
![Снимок экрана от 2024-01-09 11-46-29](https://github.com/allure-framework/allure-js/assets/123930035/1adb05ff-b5e3-4c7e-a54c-f99a333207d9)

**Comment by epszaw** [comment]
@snataCRPO thank you for the issue! Will investigate the problem as soon as possible

**Comment by baev** [comment]
Fixed in 3.0.0 

Note: The grep configuration option isn't required anymore; the filter is configured via the reporter plugin by default. Playwright test full names format is changed as well; make sure you update your test cases first
