### ISSUE TITLE
Cannot add JSON/TXT attachments

### ISSUE THREAD

**Issue by harmin-parra** [allure-framework/allure-js#852]
**Describe the bug**

**To Reproduce**

Write a test with a text or a json attachment

```
When('I add a pet', async () => {
  payload = {
    "id": ID,
    "name": "doggie",
    "status": "available"
  };
  this.attach(payload, "application/json");
  // etc....
}
```

Generate and open the report

Result:
`TypeError: this.attach is not a function`

Same thing if I try
`this.attach("random text", "plain/text");`

**Expected behavior**
I can attach text, console output, log output and CSV content to Allure report.

**Screenshots**
![image](https://github.com/allure-framework/allure-js/assets/16239820/db223501-28ce-4d69-94d5-1e7c97b69d8b)

**Desktop (please complete the following information):**
 - OS: Debian 12 Bookworm
 - Browser: Chrome
 - Allure: 2.25.0
 - Allure-cucumberjs: 2.11.1

**Additional context**

**Comment by epszaw** [comment]
Hey there! You can't use `this` with arrow functions in step definitions ([see official docs](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/step_definitions.md#cucumber-expressions)). Change arrow function on plan one and functionality should work as expected

**Comment by harmin-parra** [comment]
https://github.com/harmin-parra/calculator

Can be used for both #851 and #852

**Comment by epszaw** [comment]
I made PR into your repository https://github.com/harmin-parra/calculator/pull/1.

Foremost – forget about arrows when you want to use `this` in your step definitions, it relates to cucumber overall, it's not an Allure integration limitations. 

So, in the PR I added a test script and below you can see the generated allure report, so integration works correctly, but it can't find step definitions for the scenario. 

<img width="1335" alt="image" src="https://github.com/allure-framework/allure-js/assets/13414205/f20acb0f-3f9b-472f-8423-df00551b4765">

**Comment by epszaw** [comment]
I made a PR into the repository – https://github.com/harmin-parra/calculator/pull/1/files

Maybe, something was changed in latest cucumber releases and `CucumberAllureWorld` doesn't inject by default, so I recommend you to use `setWorldConstructro` function from the cucumber package and pass `CucumberAllureWorld` into right in your step definition file.

Of course, you can use a global setup file to avoid setting the world manually in each steps defs file, but it won't work in parallel either.

There is a report generated after `npm t` in my fork:

<img width="1336" alt="image" src="https://github.com/allure-framework/allure-js/assets/13414205/23b9de9b-6355-402e-900f-6be464c3a6fc">

**Comment by harmin-parra** [comment]
It works better.

Nevertheless, I noticed that cucumber tests are included twice in the report. Why ?

![image](https://github.com/allure-framework/allure-js/assets/16239820/317ff561-bd18-4bbb-bdc4-e3f97c3ee547)

![image](https://github.com/allure-framework/allure-js/assets/16239820/46c034af-958a-42ad-aa9e-4d4e57efd760)

**Comment by harmin-parra** [comment]
```
  this.feature();
  this.story();
  this.suite();
```
need to be avoided in order to prevent the tests to appear twice in the report.

**Comment by epszaw** [comment]
In the example with calculator, it happens due to `this.suite("Calculator")` call. By default, the reporter uses `Scenario` or `Scenario Outline` for the label. Just don't call `suite` method to avoid data duplication
