### ISSUE TITLE
No steps in allure report in with allure-hermione 2.8.0 and higher

### ISSUE THREAD

**Issue by IlyaAst** [allure-framework/allure-js#863]
Use allure with hermione. And after increase version from 2.6.0 to 2.9.2 steps are disappeared from our reports.
We try different versions and with allure-hermione 2.7.0 steps are ok but if increase version they are disappered.

In report json in part steps no data.

**To Reproduce**
1. Set allure-hermione version 2.8.0
2. Start tests
3. See allure report
4. No steps in allure report

**Expected behavior**
Steps are presented in report

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chrome
 - Version allure-hermione 2.8.0, hermione 7.3.0

**Comment by dicrtarasov** [comment]
same issue

**Comment by dicrtarasov** [comment]
Please, reopen bug, no changes inn version 2.13.0.

```typescript
await browser.step(currentTest.id, "Some step", async () => {
    ...
});
```

![telegram-cloud-photo-size-2-5440669287456036096-x](https://github.com/allure-framework/allure-js/assets/35159934/e8628066-e7c6-4157-a49b-afbb8dd84ae3)
