### ISSUE TITLE
Not possible to generate allure report using docker container for playwright

### ISSUE THREAD

**Issue by nizzel55** [allure-framework/allure-js#868]
**Describe the bug**
Not possible to generate allure report using docker container for playwright.

ERROR:
````$ allure generate ./reports/allure-results -o ./reports/allure-report --clean

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.````


Dependencies:

  "dependencies": {
    "@playwright/test": "^1.41.1",
    "@types/node": "^20.11.13",
    "@typescript-eslint/eslint-plugin": "^6.20.0",
    "@typescript-eslint/parser": "^6.20.0",
    "allure-commandline": "2.27.0",
    "allure-playwright": "^2.12.0",
    "dotenv": "^16.4.1",
    "eslint": "^8.56.0",
    "playwright": "^1.41.1",
    "typescript": "^5.3.3"
  },


Docker:
container: mcr.microsoft.com/playwright:v1.41.1-jammy


(Allure is working when NOT using the docker container.) 





**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by epszaw** [comment]
Hey there! Could you provide your `Dockerfile` content here?

**Comment by nizzel55** [comment]
Hello.
I am only using the
container: mcr.microsoft.com/playwright:v1.41.1-jammy

As documented in the Azure docs
https://playwright.dev/docs/docker

Have a nice weekend.

BR / Nils
[https://repository-images.githubusercontent.com/221981891/8c5c6942-c91f-4df1-825f-4cf474056bd7]<https://playwright.dev/docs/docker>
Docker | Playwright<https://playwright.dev/docs/docker>
Introduction
playwright.dev

________________________________

**Comment by sumitsarkar** [comment]
@nizzel55 The offiicial docker container doesn't contain Java. And Allure reporter requires Java as a dependency. You'd need to build your own Docker container containing both Playwright and Java.

**Comment by epszaw** [comment]
@sumitsarkar is right
