### ISSUE TITLE
Some random special character is getting displayed in allure report

### ISSUE THREAD

**Issue by mayank2708** [allure-framework/allure-js#888]
**Describe the bug**
Some random special character is getting displayed in allure report

**To Reproduce**
Create testcase which is getting failed

**Expected behavior**
Report must show expected output

<img width="405" alt="image" src="https://github.com/allure-framework/allure-js/assets/106744992/86bc6ab6-9ecc-44c4-9196-01578a0ae399">

**Comment by epszaw** [comment]
I closed the issue due to lack of additional details. Feel free to reopen the issue if the problem is still actual for you after update to the latest version of the integration.
