### ISSUE TITLE
I receive "Error: No tests found" trying to perform selective run of playwright autotests

### ISSUE THREAD

**Issue by dolkonsVK** [allure-framework/allure-js#889]
**Describe the bug**
In my project repository tests are organized the following way:
```
project1
   - tests/...
   - playwright.config.ts
project2
   - tests
   - playwright.config.ts
project3
   - tests
   - playwright.config.ts
```
Each playwright.config.ts file has `grep: testPlanFilter(),` added according to the documentation (https://github.com/allure-framework/allure-js/blob/main/packages/allure-playwright/README.md#selective-test-execution) but every time I try to selectively run tests on either CICD or locally (through the testplan.json file) I'm always getting the error "Error: No tests found". It seems like somehow the parsing of tests selectors does not work as expected. Any help, advice or some information would be really appreciated, thx. 

**To Reproduce**
1. Use playwright framework 
2. Try to organize the test the way described above
3. Try to run tests locally through the testplan.json

**Expected behavior**
Tests are running as expected

**Additional context**
pw version: "@playwright/test": "^1.41.0",
The content of "testplan.json" is the following:
`{"version":"1.0","tests":[{"id":123,"selector":"tests/tests.spec.ts#smth from describe GIVEN smth WHEN smth THEN smth"}]}`

**Comment by dolkonsVK** [comment]
I managed to reproduce the issue on a dummy project that I attached.
This project contains two folders "project1" and "project2". Each "project" folder has its own "tests" folder and playwright.config.ts respectively. 
Also I pasted testplan.json file in both root and "project1" directories. Attempt to run test using testplan.json from both root and "project1" repository had no luck.
[test_project.zip](https://github.com/allure-framework/allure-js/files/14458044/test_project.zip)

Also I can attach video with the steps I followed

**Comment by dolkonsVK** [comment]
any update on that?

**Comment by epszaw** [comment]
Hey, @dolkonsVK! Unfortunately, there isn't any update now. I'll notify you when I start investigating the problem.

**Comment by Viktor-Pylypenko** [comment]
Hi, @epszaw! Any updates on this one?
I also tried to configure selective testplan execution in my project using https://github.com/allure-framework/allure-js/blob/main/packages/allure-playwright/README.md#selective-test-execution and faced with the same problem described above.

In my project I use allurectl action

```
      - name: Install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ vars.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 70
          allurectl-version: 2.15.1
``` 

and latest version of "`allure-playwright`" library: `2.15.1` 

**Perhaps is there a way for workaround this problem?**

<img width="1082" alt="Screenshot 2024-05-27 at 09 16 25" src="https://github.com/allure-framework/allure-js/assets/34416976/3fb2948b-b5b1-4c1e-9ae7-d629552d513a">

**Comment by todti** [comment]
Hi, @dolkonsVK!

Could you please provide more details about the source of the testplan.json? I suspect there might be an incorrect selector in the testplan.json. For context, could you let me know which version of Allure TestOps you are using?

Thank you!

**Comment by baev** [comment]
@dolkonsVK the feature works as expected, please contact Allure TestOps support if you still having troubles with selective runs
