### ISSUE TITLE
Allure adds the “@” prefix to tags

### ISSUE THREAD

**Issue by documentat-alibaev** [allure-framework/allure-js#891]
**Describe the bug**
If I use the free form tags (without `@allure.label.tag:`), Allure adds the “@” prefix to them.

**To Reproduce**
Create and run a scenario with these tags:
```js
Scenario(...)
  .tag("Web Interface")
  .tag("Authentication");
```

**Expected behavior**
Tags: `Web Interface`, `Authentication`.

**Actual behavior**
Tags: `@Web Interface`, `@Authentication`.

**Comment by baev** [comment]
fixed via #1021
