### ISSUE TITLE
Replace documentation in packages' READMEs with the link to the doc at allurereport.org

### ISSUE THREAD

**Issue by delatrie** [allure-framework/allure-js#893]
From [https://github.com/allure-framework/allure-js/pull/815#discussion_r1504714275](https://github.com/allure-framework/allure-js/pull/815#discussion_r1504714275):

Currently, each package's README contains documentation that describes how to use the package. It overlaps with the corresponding documentation pages at allurereport.org.

We should shorten the documentation part to a simple instruction on how to start using the package. The rest should be replaced with the link to the appropriate page on the website. That would reduce duplication and prevent stalled docs and examples in README files.

**Comment by baev** [comment]
done
