### ISSUE TITLE
Test execution duration is displayed incorrectly for allure-vitest/reporter

### ISSUE THREAD

**Issue by dzianisMazhuhou** [allure-framework/allure-js#899]
**Describe the bug**
I ran integration tests that run on average for a minute and a half, but after generating the report it shows that it took several days.

**Screenshots**
![image](https://github.com/allure-framework/allure-js/assets/153908414/5e832037-5e1c-4181-bb8d-fc15f8c8d195)
![image](https://github.com/allure-framework/allure-js/assets/153908414/352741d9-0bff-4c25-9ad1-6cf5df8a7b7c)

**Comment by baev** [comment]
@dzianisMazhuhou, please make sure you're using the latest versions of vitest and allure-vitest. The issue should be fixed in `allure-vitest@v2.13.0`; see https://github.com/allure-framework/allure-js/pull/885.

**Comment by dzianisMazhuhou** [comment]
I am sorry for not providing this information right away. Currently i am using version 2.13.0
![image](https://github.com/allure-framework/allure-js/assets/153908414/6209b378-ef26-4632-839e-1075551cc2a9)

**Comment by epszaw** [comment]
I made a fix that makes tests duration in the report the same as in the console, but please attach a timeline from the report you made screenshots from to make it easier to figure out what's going wrong.

**Comment by dzianisMazhuhou** [comment]
I checked my `duration-trend.json` in history folder and i have big values for `duration`
`[{"data":{"duration":543212952}},{"data":{"duration":543212952}},{"data":{"duration":533489216}},{"data":{"duration":530802149}},{"data":{"duration":527148998}},{"data":{"duration":526620680}},{"data":{"duration":526620680}},{"data":{"duration":526011346}},{"data":{"duration":525274530}},{"data":{"duration":524956265}},{"data":{"duration":524578874}},{"data":{"duration":523736400}},{"data":{"duration":522869809}},{"data":{"duration":97793166}},{"data":{"duration":244638671}},{"data":{"duration":243285304}},{"data":{"duration":95373}},{"data":{"duration":72856600}},{"data":{"duration":72609777}},{"data":{"duration":72501683}}]`
I am using this script in `package.json `to store test run history: 
`"test:allure": "npm run test:integration || true && allure generate allure-results --clean && mkdir -p allure-results/history && mv allure-report/history/* allure-results/history && allure open"`. Perhaps the time is displayed incorrectly due to this command?

**Comment by baev** [comment]
The report duration is the time between the very first test start and the very last test stop. In case you preserve `allure-results` folder between the runs, it may show accumulated duration. The work around would be to remove `allure-results` directory before the tests run:

```json
{
   ...
   "scripts": {
     ...
      "test:clear": "rimraf allure-results",
      "test:allure": "run-s --continue-on-error test:clear test:integration test:allure-generate test:allure-open",
      "test:allure-generate": "allure generate allure-results --clean && mkdir -p allure-results/history && mv allure-report/history/* allure-results/history",
      "test:allure-open": "allure open"
   }
}
```
