### ISSUE TITLE
allure-hermione: no steps in report

### ISSUE THREAD

**Issue by dicrtarasov** [allure-framework/allure-js#906]
Hermione 8.3.0
Hermione-Allure: 2.13.0

Previous bug report: https://github.com/allure-framework/allure-js/issues/863

@epszaw Please, reopen bug, no changes inn version 2.13.0.

```typescript
await browser.step(currentTest.id, "Some step", async () => {
    ...
});
```

Empty `steps` in json report.

![telegram-cloud-photo-size-2-5440669287456036090-y](https://github.com/allure-framework/allure-js/assets/35159934/dc1c89d0-ef35-4879-84b7-a0376ebea8f5)

**Comment by epszaw** [comment]
Hey there! Signatures of the Runtime API have changed.

To add step try to use following code, [as documented here](https://github.com/allure-framework/allure-js/tree/main/packages/hermione-allure#steps)

```js
import { allure } from "hermione-allure/runtime";

it("my test", async ({ browser, currentTest }) => {
  await allure(currentTest).step("Some step", async () => {
    
  });
});
```
