### ISSUE TITLE
"cypress run" and "npx allure serve" treats "resultsDir" config key differently

### ISSUE THREAD

**Issue by tomaszwojciechowski** [allure-framework/allure-js#912]
**Describe the bug**
In config file projectDirectory\cypress\config\config.ts I have default configuration:
`allureCypress(on);
`

For "cypress run":
allure-results directory is: projectDirectory\cypress\config\allure-results\

For "npx allure serve allure-results" (default):
allure-results directory is: projectDirectory\allure-results\

**Expected behavior**
For both commands, default resultsDir value should be treated same as link to same directory ( e.g. projectDirectory\allure-results\ ).

**Comment by epszaw** [comment]
Hey there! In which directory you run cypress?

**Comment by baev** [comment]
Closed due to no response. BTW, it should be fixed in 3.0.0-beta.5
