### ISSUE TITLE
Cypress: Video attachment in report

### ISSUE THREAD

**Issue by mchen404** [allure-framework/allure-js#918]
**Is your feature request related to a problem? Please describe.**
Coming from `shelex/cypress-allure-plugin/writer`, one feature I notice missing in the new `allure-cypress/reporter` is video attachment.

Are there any plans to bring video attachment to `allure-cypress/reporter`?

**Describe the solution you'd like**
After generating an allure report from cypress test run, I see a video attachment in the allure report for each executed tests.

**Describe alternatives you've considered**
Continue using `shelex/cypress-allure-plugin/writer` with a limitation on an older cypress version.

**Additional context**

**Comment by epszaw** [comment]
Hey there! Yes, we plan to support video attachments. Bear with us for updates 🙏

**Comment by epszaw** [comment]
@mchen404 videos attachment is implemented in #919 and will be available right in the next release

**Comment by mchen404** [comment]
Nice! Appreciates the quick turn around.

**Comment by epszaw** [comment]
All the changes were moved to #924

**Comment by epszaw** [comment]
The feature is ready and will be available in the next integration version

**Comment by epszaw** [comment]
The feature is available in the latest version
