### ISSUE TITLE
Cypress: Error happened in task "allureReportTest" when the test is skipped in beforeEach()

### ISSUE THREAD

**Issue by jillyj** [allure-framework/allure-js#930]
**Describe the bug**
Error happened in task "allureReportTest" when the test is skipped in beforeEach()

**To Reproduce**
1. Set env var `SKIP_TESTS` to `true`.
2. Run the test which has a logic to conditionally skip the tests in `beforeEach()`
```
context('Conditional run', () => {
  let skip = false;
  before(() => {
    cy.get('div').then(($div) => {
      if (Cypress.env('SKIP_TESTS')) {
        skip = true;
      } else {
        skip = false;
      }
    });
  });

  beforeEach(function () {
    // use regular function here
    if (skip) this.skip();
  });
  it('some test', () => {
    expect(true).to.be.true;
  });
});
```
3. Error occurred as below.
![image](https://github.com/allure-framework/allure-js/assets/47232763/3d44c552-a18c-48ab-8fb3-76425ac27bc8)

**Expected behavior**
Test can be skipped successfully and the result/report is generated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 123.0.6312.107

**Smartphone (please complete the following information):**

**Additional context**
 "allure-cypress": "^2.15.1",

**Comment by mihaicerchez** [comment]
@epszaw This issue happens also when the Cypress test retries are enabled and an assertion from the first test attempts fails:
![image](https://github.com/allure-framework/allure-js/assets/68686291/69b646b2-555c-4b71-a861-51b1f4a795d0)

**Comment by epszaw** [comment]
Hey there!

@jillyj, I added some tests which checks, that the latest version of the integration works correctly with skips inside hooks.

@mihaicerchez, I also added some tests to check the described case. The problem doesn't exist anymore, but I decided to add `Retries` parameter to tests to make possible to know, how many retries were.
