### ISSUE TITLE
JEST not recognizes the Allure

### ISSUE THREAD

**Issue by liliancunha** [allure-framework/allure-js#933]
**Describe the bug**
I was trying to follow the configuration related to this repo https://github.com/allure-examples/allure-jest-example

The vs code did not recognize the library allure, so no methods are allowed

 
**Expected behavior**
The methods have been recognized at the VS CODE.

**Screenshots** 
![image](https://github.com/allure-framework/allure-js/assets/15097062/72954ff3-0485-4f9d-8792-30263cef627e)
![image](https://github.com/allure-framework/allure-js/assets/15097062/5c3f8dc4-78aa-4d49-9bec-acafa817ab0a)
![image](https://github.com/allure-framework/allure-js/assets/15097062/6662868d-8e3b-4a9e-a390-8146ede3d7f3)
![image](https://github.com/allure-framework/allure-js/assets/15097062/06ffdf56-a427-41a0-a1c3-6b4a98e4b437)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by eroshenkoam** [comment]
Hi, could you try our project generator, please: 
https://allurereport.org/start/

**Comment by liliancunha** [comment]
Hey @eroshenkoam,

This site only created empty projects, and unfortunately was not helpful. I tried using Javascript -> Mocha, Javascript -> Jest -> both formats browser and NodeJs
Here are the files generated:
[project browser.zip](https://github.com/allure-framework/allure-js/files/15220519/project.browser.zip)
[project.zip](https://github.com/allure-framework/allure-js/files/15220520/project.zip)
[project (1).zip](https://github.com/allure-framework/allure-js/files/15220521/project.1.zip)

**Comment by epszaw** [comment]
Hey there. Try to add next import somewhere in your test setup files:

```js
import "allure-jest"
```

The import will let vscode know about the types definitions

**Comment by baev** [comment]
starting 3.0.0, you can import Allure Runtime API from `allure-js-commons`:

```ts
import {
  label,
  link,
  issue,
  tms,
  step,
  attachment,
} from "allure-js-commons";
// or
import * as allure from "allure-js-commons";
```
