### ISSUE TITLE
allure-mocha package runtime "allure.step" return type "any"

### ISSUE THREAD

**Issue by obezglavlen** [allure-framework/allure-js#945]
**Describe the bug**
When i pass my type in "allure.step" generic, it still returns "any" type. Because of that if my body is async function if i dont write await before "allure.step", this will be problem.

**To Reproduce**
1. Import allure from "allure-mocha/runtime"
2. Call allure.step few times and pass async functions
3. They will not be executed sequentaly and linter doesn't lint any errors about "forgot await"

**Expected behavior**
If i pass my type to "allure.step" generic, it should show in typelint this type, not any

**Screenshots**
<img width="723" alt="image" src="https://github.com/allure-framework/allure-js/assets/29686964/cc020343-5af8-4c04-b19e-0116d082187b">
<img width="787" alt="image" src="https://github.com/allure-framework/allure-js/assets/29686964/5e55d186-ccfc-47a7-885b-932b8868390a">

**Desktop (please complete the following information):**
 - OS: MacOs 14.4.1
 - Typescript 5.4.5

**Comment by baev** [comment]
Fixed in 3.0.0-beta.1
