### ISSUE TITLE
Squish test report integrate with Allure report

### ISSUE THREAD

**Issue by amol-54** [allure-framework/allure-js#977]
Hi Team, 

I was trying to convert squish XML report to allure report. It's converted into allure xml format, but after generating HTML report from this converted XML file I am not able to see anything on web browser. It is continuously loading and in another section I am getting 404 error.

Squish provides multiple results file. I tried with json as well but same issue. 

Will you please help on this issue.?

**Comment by baev** [comment]
https://stackoverflow.com/a/78205486/3915166
