### ISSUE TITLE
Cypress: Please add an option whether to include video in the allure report. If the input parameter is false, video should not attach in the allure report

### ISSUE THREAD

**Issue by sadhishsk** [allure-framework/allure-js#980]
**Is your feature request related to a problem? Please describe.**
Currently video is attached for all the executions including Passed scenarios. When we try to artifact the report, its a bulk file. So we want to store only the report with no videos attached to it

**Describe the solution you'd like**
We would like to have an optional parameter flag that can be passed from the Cypress Config file and based on it, video should be attached to the report.

**Describe alternatives you've considered**
As of now, I don't have any alternatives.

**Additional context**
No additional context and I'm requesting for an feature

**Comment by epszaw** [comment]
If you want to prevent cypress from videos generation, you can pass `video: false` in the `e2e` section in your cypress config:

```js
// cypress.config.js
modules.export = {
  e2e: {
    video: false
  }
}
```

**Comment by epszaw** [comment]
Sorry for misunderstood! I added `videoOnFailOnly` option for the integration. You can observe the feature delivering process in the linked PR. The feature will be available in the next version.
