### ISSUE TITLE
Playwright cucumber allure report issue

### ISSUE THREAD

**Issue by siva90144** [allure-framework/allure-js#982]
I am running my project with Playwright, Cucumber, and Allure Report. I have a feature file as shown below and I am running tests with specific tags, but it is printing all the examples, including those which are not executed.

**To Reproduce**
1. create a feature file like below
  '@Search @regression
Feature: Search - Verify end to end flow
    I want to verify Search flow

    @actual @validate-e2e @search
    Scenario Outline: Search - I am able to search in the web "<client>"
        Given I login the application for "<client>"
        When I get the page title
        Then I verify details "<pagetitle>"
        @google
        Examples:
            | client | pagetitle |
            | google | Google    |
        @amazon
        Examples:
            | client | pagetitle |
            | amazon | Amazon    |
        @facebook
        Examples:
            | client   | pagetitle |
            | facebook | Facebok  |
'
<img width="575" alt="image" src="https://github.com/allure-framework/allure-js/assets/19613704/1f012b87-7f0a-499f-9158-16565ab32a9a">

3. I executed the tags with  '@search and @amazon'  and here is the run command: **npm test run --tags="@search and @amazon"**
4. it picked the right scenario and executed only amazon scenario.
5. but in the reprot its showing all the clinets related to google and facebook along with the amazon

**Expected behavior**
It should display only content related to amazon in example section

**Screenshots**
please see the attached screenshot and highlighted in red color should not be displayed
<img width="1119" alt="image" src="https://github.com/allure-framework/allure-js/assets/19613704/e1478a19-a7db-4012-88e0-977c0e0156b2">

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version [latest]

**Additional context**
please see the attached sample project

**Comment by Zychkov** [comment]
This issue was reported in the task https://github.com/allure-framework/allure-js/issues/625, but closed with the resolution Fixed in 3.0.0-beta.11.
I have updated to version 3.0.1. The bug is still relevant.

**Comment by baev** [comment]
@Zychkov, are you sure? #625 was about missed parameters for Scenario Outline for cucumbers integration. It was fixed. There is a test: https://github.com/allure-framework/allure-js/blob/main/packages/allure-cucumberjs/test/spec/examples.test.ts ([The feature file](https://github.com/allure-framework/allure-js/blob/main/packages/allure-cucumberjs/test/samples/features/examples.feature#L3-L12))

**Comment by Zychkov** [comment]
@baev, yeah, I'm sure. Attached are package.json and the fiche file.
Feature
```
Feature: allure-test
  Feature's description

  @example @tms=ABC-222 @issue=ABC-333
  Scenario Outline: Allure Tests
    Given The sum of the numbers <a> and <b> must be equal to <c>

    Examples:
      | a | b | c |
      | 1 | 2 | 3 |
      | 2 | 2 | 4 |

    Examples:
      | a | b | c |
      | 3 | 2 | 5 |
      | 4 | 2 | 7 |
```
      
Dependencies:
```    
   "@cucumber/cucumber": "^10.8.0",
    "@cucumber/messages": "^24.1.0",
    "allure-commandline": "^2.30.0",
    "allure-cucumberjs": "^3.0.1",
    "allure-js-commons": "^3.0.1"
```

How the report looks:
![image](https://github.com/user-attachments/assets/ddc8dacf-0452-4458-be53-228a5ed52b4c)


What I expect it should look like (same scenario, but in Java):
![image](https://github.com/user-attachments/assets/188af371-1756-4e39-9e8a-d4136caf81ba)

**Comment by baev** [comment]
@Zychkov thanks! It wasn't working correctly. I provided a pull request with the fixes https://github.com/allure-framework/allure-js/pull/1153
