### ISSUE TITLE
newman-reporter-allure v.2.15.1: historyId is overwritten for an each new run

### ISSUE THREAD

**Issue by dimaklepikov** [allure-framework/allure-js#984]
**Describe the bug**
In the results json file (related to test suite ran), we can see the historyId key (https://allurereport.org/docs/how-it-works-test-result-file/#historyid-string), which is same for the testCase across all runs (So, if I delete the results of my current run, and will make another run, this ID will remain the same. 

for Newman plugin, the history id is overwritten each new run, and has different format than python's plugin:
`"historyId":"bfd9e829-eb96-489f-b80c-ccf3a4b2d045"` - Newman
`"historyId":"a95492b65489dda25400f15ea5af26cc"` - Python

**To Reproduce**
1. ```newman run --reporters allure --reporter-allure-export r/ -e env.json collection.json```
2. ```cat *-result.json```
3. Fetch `testCaseId` and `historyId`
4. Remove results dir `rm -rf r/`
5. re-run 1st step
6. repeat 2nd step
7. Compare the `historyId` with result fetched from 3rd step, see the difference

**Expected behavior**
Histroy Id should be same for each test case and History tab should be correctly displayed

**Screenshots**
<img width="1228" alt="Screenshot 2024-05-30 at 21 30 53" src="https://github.com/allure-framework/allure-js/assets/66633028/f4333a7d-b236-4e39-a3f8-89eb92011e77">

**Comment by baev** [comment]
fixed in `3.0.0-beta.3`
