### ISSUE TITLE
Cypress: create steps from Cypress commands

### ISSUE THREAD

**Issue by delatrie** [allure-framework/allure-js#990]
### Discussed in https://github.com/orgs/allure-framework/discussions/2508

<div type='discussions-op-text'>

<sup>Originally posted by **lynnismetw** April 15, 2024</sup>
As PieterGrobler mentioned in https://github.com/cypress-io/cypress/issues/27113#issuecomment-2033129596, allure-cypress lost the automatic annotation of each test step which we got from cypress-allure-plugin.

My project just upgraded Cypress to 13 and also replaced **cypress-allure-plugin** with **allure-cypress** but found NO test body with each step automatically generated in the allure result. Will you consider add this feature to allure-cypress?
</div>

**Comment by epszaw** [comment]
The latest version of the integration reports commands.
