### ISSUE TITLE
The latest version of newman-reporter-allure library is not generating results in specified directory

### ISSUE THREAD

**Issue by abhi2495** [allure-framework/allure-js#992]
**Describe the bug**
I am using the latest  (3.0.0-beta.1) version of `newman-reporter-allure` library and node v16.17.0, npm 8.15.0. I tried to generate the results in a specified directory using the `reporter-allure-export` option. This used to work before , but with this latest version now, it is no longer respecting the option and generating the results in the default directory i.e `allure-results`

**To Reproduce**
1. Install the allure and newman libraries:
          npm install -g newman
          npm install -g newman-reporter-allure
          npm install -g allure-commandline
2. Run `newman run postman_collection.json -e postman_environment.json --silent -r allure --reporter-allure-export 'Results/'`

**Expected behavior**
The result files should get generated inside the 'Results/' directory

**Screenshots**
<img width="330" alt="Screenshot 2024-06-04 at 6 52 18 PM" src="https://github.com/allure-framework/allure-js/assets/26816172/90199ea6-3829-4724-98a0-068a39321aaf">

**Desktop:**
 - OS: MacOS/Ubuntu
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**

**Additional context**

**Comment by baev** [comment]
The property `export` was renamed to `resultsDir` to align the naming across the different frameworks

**Comment by cryptton2004** [comment]
This should be specified somewhere in the docs.
https://www.npmjs.com/package/newman-reporter-allure
